#!/usr/bin/env python3
"""
Amplify Science K-8 Curriculum Scraper
Scrapes NGSS-aligned science curriculum units for grades K-8
Saves to: data/amplify_science.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class AmplifyScienceScraper:
    def __init__(self):
        self.base_url = "https://amplify.com"
        self.target_urls = [
            "https://amplify.com/programs/amplify-science",
            "https://amplify.com/science-units",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_amplify_science_units(self) -> List[Dict]:
        """Create Amplify Science curriculum unit resources."""
        resources = [
            # Kindergarten Units
            {
                'name': 'Amplify Science K - Needs of Plants and Animals',
                'description': 'Investigate what plants and animals need to survive and grow. Students observe living things, test environmental factors, and design solutions for animal care. Hands-on investigation with digital simulations. 6-8 weeks NGSS-aligned unit.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Biology, Ecology, Environmental Science',
                'target_grade': 'K',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '6-8 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science K - Pushes and Pulls',
                'description': 'Explore forces through investigation and design challenges. Test how pushes and pulls affect object motion. Design and build solutions using force concepts. Includes physical materials and digital modeling. 6-8 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Physics, Forces, Motion, Engineering Design',
                'target_grade': 'K',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '6-8 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science K - Sunlight and Weather',
                'description': 'Investigate how sunlight affects Earth and causes weather patterns. Observe sky phenomena, track weather changes, and model seasonal patterns. Combines outdoor observation with digital tools. 6-8 weeks unit.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Earth Science, Weather, Astronomy, Climate',
                'target_grade': 'K',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '6-8 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # 1st Grade Units
            {
                'name': 'Amplify Science 1 - Light and Sound',
                'description': 'Investigate properties of light and sound through investigation. Design communication devices using light and sound. Study waves, vibration, and transmission. Interactive simulations and hands-on experiments. 8 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Physics, Light, Sound, Waves, Engineering',
                'target_grade': '1',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 1 - Animal and Plant Defenses',
                'description': 'Explore how organisms use body parts and behaviors to survive. Study camouflage, mimicry, and defense mechanisms. Biomimicry design challenge. Includes observation activities and digital modeling. 8 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Biology, Adaptations, Biomimicry',
                'target_grade': '1',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 1 - Spinning Earth',
                'description': 'Investigate patterns in sky including day/night cycle and seasonal changes. Model Earth\'s rotation and orbit. Study how sunlight affects different locations. Digital simulations and hands-on modeling. 8 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Astronomy, Earth Science, Space Science, Patterns',
                'target_grade': '1',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # 2nd Grade Units
            {
                'name': 'Amplify Science 2 - Properties of Materials',
                'description': 'Test and compare material properties. Design solutions using appropriate materials for specific purposes. Investigate reversible and irreversible changes. Hands-on testing with digital documentation. 8 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Chemistry, Materials Science, Engineering, Physical Science',
                'target_grade': '2',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 2 - Plant and Animal Relationships',
                'description': 'Study how plants and animals depend on each other and environment. Investigate pollination, seed dispersal, and interdependence. Design pollinator gardens. Outdoor investigations and digital simulations. 8 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Ecology, Biology, Interdependence',
                'target_grade': '2',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 2 - Changing Landforms',
                'description': 'Investigate how wind, water, and ice shape Earth\'s surface. Model erosion and weathering processes. Design solutions to prevent erosion. Includes landform mapping and change modeling. 8 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Earth Science, Geology, Erosion, Engineering',
                'target_grade': '2',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # 3rd Grade Units
            {
                'name': 'Amplify Science 3 - Balancing Forces',
                'description': 'Investigate balanced and unbalanced forces. Design and test structures for stability. Study magnetic forces and patterns. Engineering challenges with digital force modeling. 8-10 weeks unit.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Physics, Forces, Magnetism, Engineering Design',
                'target_grade': '3',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 3 - Inheritance and Traits',
                'description': 'Study how traits pass from parents to offspring. Investigate variation within species and adaptation advantages. Fossil evidence of inherited traits. Includes breeding simulations and data analysis. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Genetics, Biology, Evolution',
                'target_grade': '3',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 3 - Weather and Climate',
                'description': 'Investigate weather patterns and climate differences. Collect and analyze weather data over time. Study how climate affects living things. Digital weather simulations and data graphing. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Earth Science, Meteorology, Climate Science, Data Analysis',
                'target_grade': '3',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 3 - Environments and Survival',
                'description': 'Study how organisms survive in different environments. Investigate adaptations, habitat requirements, and environmental changes. Design solutions for habitat protection. Field observations and digital ecosystem modeling. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Ecology, Adaptations, Conservation',
                'target_grade': '3',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # 4th Grade Units
            {
                'name': 'Amplify Science 4 - Energy Conversions',
                'description': 'Investigate how energy transfers and converts between forms. Study collisions, sound, light, and electrical energy. Design energy conversion devices. Hands-on experiments with digital energy modeling. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Physics, Energy, Engineering, Physical Science',
                'target_grade': '4',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 4 - Vision and Light',
                'description': 'Study how eyes detect light and enable vision. Investigate light behavior including reflection and refraction. Design optical devices. Interactive eye models and light pathway experiments. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Physics, Biology, Light, Vision, Engineering',
                'target_grade': '4',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 4 - Earth\'s Features',
                'description': 'Investigate how Earth\'s surface changes through weathering, erosion, and plate tectonics. Model volcanic eruptions and earthquakes. Map geological hazards and design safety solutions. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Earth Science, Geology, Plate Tectonics, Natural Hazards',
                'target_grade': '4',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 4 - Waves, Energy, and Information',
                'description': 'Explore how waves transfer energy and encode information. Design communication devices using light and sound waves. Study wave patterns and digital encoding. Engineering challenges with wave applications. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Physics, Waves, Communication Technology, Engineering',
                'target_grade': '4',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # 5th Grade Units
            {
                'name': 'Amplify Science 5 - Patterns of Earth and Sky',
                'description': 'Study Earth-Sun-Moon system and patterns in space. Investigate seasons, phases, eclipses, and star motion. Build scale models of solar system. Digital planetarium simulations. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Astronomy, Earth Science, Space Science, Patterns',
                'target_grade': '5',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 5 - Modeling Matter',
                'description': 'Investigate particle nature of matter and chemical reactions. Study phase changes, conservation of mass, and molecular interactions. Conduct experiments testing matter properties. Digital particle modeling. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Chemistry, Matter, Physical Science, Molecular Science',
                'target_grade': '5',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 5 - Ecosystem Restoration',
                'description': 'Study matter and energy flow through ecosystems. Investigate food webs, decomposition, and nutrient cycling. Design ecosystem restoration plans. Field ecology and digital ecosystem modeling. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Ecology, Environmental Science, Conservation',
                'target_grade': '5',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 5 - Earth\'s Water',
                'description': 'Investigate how water moves through Earth systems. Study water cycle, watersheds, and water conservation. Test water purification methods. Includes watershed mapping and digital water cycle simulation. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Earth Science, Hydrology, Environmental Science, Engineering',
                'target_grade': '5',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # 6th Grade Units
            {
                'name': 'Amplify Science 6 - Cells and Systems',
                'description': 'Study structure and function of cells, organs, and body systems. Investigate how systems work together for survival. Model cellular processes and system interactions. Microscopy and digital anatomy. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Biology, Anatomy, Physiology',
                'target_grade': '6',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 6 - Plate Tectonics and Rock Cycling',
                'description': 'Investigate plate boundaries, earthquakes, and rock formation. Model convection currents and tectonic movement. Study rock cycle and geological time. Includes rock identification and digital plate modeling. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Earth Science, Geology, Plate Tectonics, Geophysics',
                'target_grade': '6',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 6 - Thermal Energy',
                'description': 'Study heat transfer and thermal equilibrium. Design insulation systems and cooling devices. Investigate molecular motion and temperature. Hands-on thermal experiments with particle modeling. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Physics, Thermodynamics, Energy, Engineering',
                'target_grade': '6',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 6 - Weather Patterns',
                'description': 'Investigate atmospheric circulation, air masses, and severe weather. Analyze weather maps and predict conditions. Study climate zones and global wind patterns. Digital weather modeling and forecasting. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Earth Science, Meteorology, Atmospheric Science, Data Analysis',
                'target_grade': '6',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # 7th Grade Units
            {
                'name': 'Amplify Science 7 - Chemical Reactions',
                'description': 'Investigate how substances interact and transform. Study conservation of mass, energy in reactions, and molecular rearrangement. Conduct synthesis and decomposition experiments. Digital molecular modeling. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Chemistry, Chemical Reactions, Physical Science, Molecular Science',
                'target_grade': '7',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 7 - Populations and Resources',
                'description': 'Study population dynamics and ecosystem carrying capacity. Investigate competition, predation, and resource availability. Analyze human impact on ecosystems. Population modeling and field ecology. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Ecology, Population Biology, Environmental Science',
                'target_grade': '7',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 7 - Rock Transformations',
                'description': 'Investigate rock cycle and mineral formation processes. Study metamorphism, crystallization, and geological processes. Identify rocks and minerals. Includes geological timescale and Earth history. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Earth Science, Geology, Mineralogy, Petrology',
                'target_grade': '7',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 7 - Metabolism',
                'description': 'Study how organisms obtain and use energy. Investigate photosynthesis, cellular respiration, and digestion. Model molecular processes in cells. Lab investigations with digital cellular modeling. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Biology, Cellular Biology, Biochemistry',
                'target_grade': '7',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # 8th Grade Units
            {
                'name': 'Amplify Science 8 - Forces and Motion',
                'description': 'Investigate Newton\'s laws through experimentation and modeling. Study velocity, acceleration, and force relationships. Design collision safety systems. Includes motion analysis and force modeling. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Physics, Forces, Motion, Engineering Design',
                'target_grade': '8',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 8 - Genetics',
                'description': 'Study DNA structure, protein synthesis, and inheritance patterns. Investigate mutations and genetic variation. Analyze pedigrees and conduct genetic crosses. Digital DNA modeling and data analysis. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Genetics, Molecular Biology, Biotechnology',
                'target_grade': '8',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 8 - Earth History',
                'description': 'Investigate fossil record and geological evidence of Earth\'s past. Study radiometric dating, fossil formation, and mass extinctions. Reconstruct ancient environments. Includes fossil analysis and timeline construction. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Earth Science, Paleontology, Geology, Evolution',
                'target_grade': '8',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Amplify Science 8 - Natural Selection and Adaptation',
                'description': 'Study mechanisms of evolution and natural selection. Investigate adaptation, speciation, and biodiversity. Analyze evidence from fossils, anatomy, and DNA. Population modeling and evolutionary simulations. 8-10 weeks.',
                'url': 'https://amplify.com/programs/amplify-science',
                'source': 'Amplify Science',
                'category': 'Curriculum',
                'stem_fields': 'Life Science, Evolution, Genetics, Ecology',
                'target_grade': '8',
                'cost': 'School-Purchase',
                'location_type': 'Classroom',
                'time_commitment': '8-10 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School-Based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'School-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'School-Based',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Amplify Science scraping...")
        print("Note: Creating Amplify Science curriculum unit resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Amplify Science entries...")
        self.resources = self.create_amplify_science_units()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/amplify_science.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = AmplifyScienceScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
