#!/usr/bin/env python3
"""
Art of Problem Solving (AoPS) Programs Scraper
Scrapes math and computer science programs from AoPS for K-12 students
Saves to: data/aops.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class AoPSScraper:
    def __init__(self):
        self.base_url = "https://artofproblemsolving.com"
        self.target_urls = [
            "https://artofproblemsolving.com/",
            "https://artofproblemsolving.com/online-school",
            "https://artofproblemsolving.com/summer-programs",
            "https://artofproblemsolving.com/beast-academy",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_aops_resources(self) -> List[Dict]:
        """Create AoPS platform resources."""
        resources = [
            # Elementary Level (Beast Academy)
            {
                'name': 'AoPS Beast Academy Online',
                'description': 'Comprehensive online math program for elementary students grades 2-5. Interactive lessons, adaptive practice, and engaging problem-solving with comic book style instruction.',
                'url': 'https://artofproblemsolving.com/beast-academy',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '2-5',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (3-5 hours/week)',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Middle School Courses
            {
                'name': 'AoPS Prealgebra',
                'description': 'Rigorous prealgebra course covering number theory, proportions, geometry basics, and problem-solving strategies. Live online classes with expert instructors for grades 6-8.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Introduction to Algebra A',
                'description': 'First part of comprehensive algebra course covering equations, inequalities, functions, and polynomials. Interactive format with challenging problems for advanced middle school students.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '6-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Introduction to Algebra B',
                'description': 'Second part of algebra course covering factoring, quadratics, systems of equations, and logarithms. Prepares students for advanced mathematics and competition math.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '7-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Introduction to Counting & Probability',
                'description': 'Comprehensive combinatorics and probability course teaching counting techniques, permutations, combinations, and probability theory with challenging competition-style problems.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '7-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Introduction to Number Theory',
                'description': 'Study of integers, divisibility, prime numbers, modular arithmetic, and Diophantine equations. Essential for math competitions like AMC and MATHCOUNTS.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '7-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Introduction to Geometry',
                'description': 'Rigorous geometry covering triangles, circles, polygons, coordinate geometry, and transformations. Emphasizes proof-writing and problem-solving strategies.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '7-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # High School Courses
            {
                'name': 'AoPS Intermediate Algebra',
                'description': 'Advanced algebra covering complex numbers, polynomials, functional equations, inequalities, and sequences. Prepares students for AIME and higher competitions.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Intermediate Counting & Probability',
                'description': 'Advanced combinatorics including generating functions, recursion, PIE, and advanced probability. Competition mathematics at AIME level.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Precalculus',
                'description': 'Comprehensive precalculus covering trigonometry, complex numbers, vectors, matrices, and conic sections. Prepares for AP Calculus and college math.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Calculus',
                'description': 'Rigorous calculus course covering limits, derivatives, integrals, and applications. Exceeds AP Calculus BC curriculum with competition problems.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '10-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Olympiad Geometry',
                'description': 'Advanced geometry for mathematical olympiads covering power of a point, homothety, inversions, and complex geometry techniques. For USAMO preparation.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Competition Prep
            {
                'name': 'AoPS MATHCOUNTS/AMC 8 Basics',
                'description': 'Preparation for MATHCOUNTS and AMC 8 competitions. Covers problem-solving strategies, time management, and all competition topics for middle school students.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '8-12 weeks (3-4 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS AMC 10 Problem Series',
                'description': 'Intensive AMC 10 preparation with past problems, strategies, and mock competitions. Covers algebra, geometry, number theory, and counting.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '9-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '8-12 weeks (3-4 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS AMC 12 Problem Series',
                'description': 'Advanced AMC 12 preparation with difficult problems and competition strategies. Focuses on advanced algebra, precalculus, and problem-solving techniques.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '10-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '8-12 weeks (3-4 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS AIME Problem Series',
                'description': 'Preparation for AIME (American Invitational Mathematics Examination) with challenging problems requiring deep understanding and creative problem-solving.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '8-12 weeks (4-5 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS USAMO Preparation',
                'description': 'Elite preparation for USA Mathematical Olympiad covering proof-writing, advanced problem-solving, and olympiad-level mathematics across all competition areas.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (5-6 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Computer Science
            {
                'name': 'AoPS Introduction to Programming with Python',
                'description': 'Learn Python programming fundamentals including variables, loops, functions, and basic algorithms. Project-based approach with mathematical applications.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming',
                'target_grade': '6-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Intermediate Programming with Python',
                'description': 'Advanced Python covering data structures, object-oriented programming, recursion, and algorithm design. Prepares for competitive programming.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming',
                'target_grade': '8-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS USACO Bronze Preparation',
                'description': 'Preparation for USA Computing Olympiad Bronze division. Learn algorithms, data structures, and problem-solving for competitive programming.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Algorithms',
                'target_grade': '8-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (4-5 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS USACO Silver Preparation',
                'description': 'Advanced competitive programming for USACO Silver division covering graph algorithms, dynamic programming, and advanced data structures.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Algorithms',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (5-6 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Introduction to Java',
                'description': 'Comprehensive Java programming course covering object-oriented principles, data structures, and algorithms. Prepares for AP Computer Science A.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12-15 weeks (3-4 hours/week)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Computer Science Foundations',
                'description': 'Introduction to computer science concepts including binary, logic gates, computer architecture, and computational thinking. No programming experience required.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science',
                'target_grade': '6-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '8-10 weeks (2-3 hours/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Summer Programs
            {
                'name': 'AoPS Summer Math Camp - Elementary',
                'description': 'Two-week intensive math camp for elementary students grades 3-5. Daily live classes covering advanced problem-solving, puzzles, and competition preparation.',
                'url': 'https://artofproblemsolving.com/summer-programs',
                'source': 'Art of Problem Solving',
                'category': 'Camp',
                'stem_fields': 'Mathematics',
                'target_grade': '3-5',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '2 weeks (3-4 hours/day)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Summer Math Camp - Middle School',
                'description': 'Intensive two-week camp for middle school students covering algebra, geometry, counting, and number theory with competition focus.',
                'url': 'https://artofproblemsolving.com/summer-programs',
                'source': 'Art of Problem Solving',
                'category': 'Camp',
                'stem_fields': 'Mathematics',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '2 weeks (4-5 hours/day)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Summer Math Camp - High School',
                'description': 'Advanced two-week camp for high school students preparing for AIME, USAMO, and college-level mathematics. Includes olympiad problem-solving.',
                'url': 'https://artofproblemsolving.com/summer-programs',
                'source': 'Art of Problem Solving',
                'category': 'Camp',
                'stem_fields': 'Mathematics',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '2 weeks (5-6 hours/day)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Summer Coding Camp - Python',
                'description': 'Two-week Python programming intensive for middle and high school students. Build projects, learn algorithms, and prepare for competitive programming.',
                'url': 'https://artofproblemsolving.com/summer-programs',
                'source': 'Art of Problem Solving',
                'category': 'Camp',
                'stem_fields': 'Computer Science, Programming',
                'target_grade': '6-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '2 weeks (4-5 hours/day)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Summer Game Design Camp',
                'description': 'Learn game development with Python and Pygame. Two-week camp teaching programming, game design, and project development for aspiring game creators.',
                'url': 'https://artofproblemsolving.com/summer-programs',
                'source': 'Art of Problem Solving',
                'category': 'Camp',
                'stem_fields': 'Computer Science, Game Design',
                'target_grade': '6-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '2 weeks (4-5 hours/day)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Short Courses
            {
                'name': 'AoPS Problem Solving Techniques',
                'description': 'Short course teaching essential problem-solving strategies including working backwards, pattern recognition, and strategic guessing for competition math.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '6-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '4-6 weeks (2-3 hours/week)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Introduction to Logic Puzzles',
                'description': 'Fun course exploring logic puzzles, brain teasers, and mathematical reasoning. Develops critical thinking skills through engaging problems.',
                'url': 'https://artofproblemsolving.com/online-school',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Logic',
                'target_grade': '4-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '4-6 weeks (2-3 hours/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session-based',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Course-Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Math Jams',
                'description': 'Free live online math problem-solving sessions with expert instructors. Explore interesting problems, discuss solutions, and connect with math enthusiasts.',
                'url': 'https://artofproblemsolving.com/',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours per session',
                'prerequisite_level': 'Variable',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'AoPS Community Forums',
                'description': 'Free online community with discussion forums covering all areas of mathematics and computer science. Students can ask questions, share solutions, and collaborate on problems.',
                'url': 'https://artofproblemsolving.com/',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Computer Science',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-directed',
                'prerequisite_level': 'Variable',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'AoPS Alcumus - Adaptive Learning',
                'description': 'Free adaptive learning system that adjusts problem difficulty based on student performance. Covers prealgebra through precalculus with thousands of problems.',
                'url': 'https://artofproblemsolving.com/',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'AoPS For the Win! Problem Series',
                'description': 'Free weekly problem sets with solutions covering all competition math topics. Great for independent study and skill development.',
                'url': 'https://artofproblemsolving.com/',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-3 hours/week',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'AoPS Contest Preparation Resources',
                'description': 'Free resources including past competition problems, solutions, and strategies for AMC, AIME, MATHCOUNTS, and other contests.',
                'url': 'https://artofproblemsolving.com/',
                'source': 'Art of Problem Solving',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-directed',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Art of Problem Solving platform scraping...")
        print("Note: Creating AoPS math and CS program resources")
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating AoPS resource entries...")
        self.resources = self.create_aops_resources()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/aops.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = AoPSScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
