"""
Biomedical Research High School Internships Scraper
Scrapes high school biomedical research internship information from NIH, universities, and hospitals
"""

import csv
import requests
from bs4 import BeautifulSoup
import time
from typing import List, Dict
import os

class BiomedicalResearchHSScraper:
    def __init__(self):
        self.base_urls = [
            "https://www.nih.gov",
            "https://www.training.nih.gov"
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> BeautifulSoup:
        """Fetch and parse a webpage"""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except Exception as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_biomedical_research_internships(self) -> List[Dict]:
        """Create comprehensive list of high school biomedical research internships"""
        resources = [
            {
                'name': 'NIH - Summer Internship Program in Biomedical Research (SIP)',
                'description': 'Competitive 8-week summer research program at the National Institutes of Health for high school students. Students work directly with NIH scientists on cutting-edge biomedical research projects. Program includes weekly seminars, poster presentations, and networking opportunities with leading researchers.',
                'url': 'https://www.training.nih.gov/programs/sip',
                'source': 'National Institutes of Health',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Biology, Medicine, Health Sciences, Genetics',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Bethesda, MD',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Stanford Medicine - Summer Research Program for High School Students',
                'description': 'Intensive 8-week biomedical research program where high school students work in Stanford Medical School laboratories. Students conduct independent research projects under faculty mentorship and present findings at program symposium.',
                'url': 'https://med.stanford.edu/summer-research-program-high-school.html',
                'source': 'Stanford University School of Medicine',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Medicine, Molecular Biology, Neuroscience',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend and housing assistance available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Palo Alto, CA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Jackson Laboratory - Summer Student Program',
                'description': 'Hands-on genomics and genetics research experience for high school students at premier biomedical research institution. Students work with world-class scientists on projects involving mammalian genetics, cancer biology, and computational biology.',
                'url': 'https://www.jax.org/education-and-learning/high-school-students/summer-student-program',
                'source': 'Jackson Laboratory',
                'category': 'Internship',
                'stem_fields': 'Genetics, Genomics, Cancer Biology, Computational Biology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '10 weeks full-time summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend, housing, and travel assistance provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Bar Harbor, ME',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Mayo Clinic - High School Summer Research Program',
                'description': 'Prestigious biomedical research internship at Mayo Clinic for motivated high school students. Interns work alongside physician-scientists and researchers on projects in areas like cardiovascular research, oncology, and regenerative medicine.',
                'url': 'https://college.mayo.edu/academics/high-school-programs/summer-research-program',
                'source': 'Mayo Clinic',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Medicine, Cardiovascular Science, Oncology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Rochester, MN',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Roswell Park Cancer Institute - High School Summer Research Program',
                'description': 'Cancer research internship for high school students at comprehensive cancer center. Students participate in laboratory research focused on cancer biology, immunology, and treatment development while learning from leading oncology researchers.',
                'url': 'https://www.roswellpark.org/education/high-school-summer-internship',
                'source': 'Roswell Park Comprehensive Cancer Center',
                'category': 'Internship',
                'stem_fields': 'Cancer Biology, Immunology, Oncology, Biomedical Research',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '6 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Buffalo, NY',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Johns Hopkins School of Medicine - Summer Biomedical Research Program for HS',
                'description': 'Rigorous 8-week research experience at Johns Hopkins for exceptional high school students. Interns work in medical school laboratories conducting research in areas like neuroscience, genetics, public health, and biomedical engineering.',
                'url': 'https://www.hopkinsmedicine.org/som/education-programs/high-school-summer-research',
                'source': 'Johns Hopkins University School of Medicine',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Neuroscience, Genetics, Public Health',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Baltimore, MD',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Boston University School of Medicine - RISE Practicum',
                'description': 'Research internship for underrepresented minority high school students interested in biomedical careers. Six-week program includes laboratory research, clinical shadowing, and career development workshops. Strong focus on diversity in medicine.',
                'url': 'https://www.bumc.bu.edu/rise/practicum/',
                'source': 'Boston University School of Medicine',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Medicine, Clinical Sciences, Health Sciences',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '6 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend, housing, and meals provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Boston, MA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'UC San Francisco - High School Biomedical Research Internship',
                'description': 'Summer research program at UCSF for Bay Area high school students interested in biomedical sciences. Students conduct hands-on research in laboratories focused on precision medicine, stem cell research, and drug discovery.',
                'url': 'https://graduate.ucsf.edu/high-school-intern-program',
                'source': 'University of California San Francisco',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Stem Cell Biology, Pharmacology, Medicine',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'San Francisco, CA',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Memorial Sloan Kettering - Summer Student Program',
                'description': 'Cancer research internship for high school students at world-renowned cancer center. Students work on cutting-edge cancer biology projects, attend research seminars, and present findings at end-of-summer symposium.',
                'url': 'https://www.mskcc.org/education-training/high-school/summer-student-program',
                'source': 'Memorial Sloan Kettering Cancer Center',
                'category': 'Internship',
                'stem_fields': 'Cancer Biology, Oncology, Immunotherapy, Biomedical Research',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '10 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'High',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'New York, NY',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Cleveland Clinic - Lerner Research Institute Summer Internship',
                'description': 'Biomedical research internship for high school students at Cleveland Clinic. Interns participate in research projects in cardiovascular medicine, cancer biology, inflammation, and translational medicine.',
                'url': 'https://www.lerner.ccf.org/education/summer-internship/',
                'source': 'Cleveland Clinic Lerner Research Institute',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Cardiovascular Medicine, Cancer Biology, Immunology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Cleveland, OH',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'MD Anderson Cancer Center - High School Summer Research Program',
                'description': 'Elite cancer research program for Texas high school students at one of nation\'s top cancer centers. Students conduct research in cancer prevention, treatment, and biology while learning from world-class oncology researchers.',
                'url': 'https://www.mdanderson.org/education-training/high-school-program.html',
                'source': 'MD Anderson Cancer Center',
                'category': 'Internship',
                'stem_fields': 'Cancer Research, Oncology, Molecular Biology, Biomedical Sciences',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Houston, TX',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Broad Institute - Summer Research Program for High School Students',
                'description': 'Genomics and computational biology research internship at MIT/Harvard Broad Institute. High school students work on projects involving genomic medicine, cancer genomics, and data science in biology.',
                'url': 'https://www.broadinstitute.org/high-school-summer-research',
                'source': 'Broad Institute of MIT and Harvard',
                'category': 'Internship',
                'stem_fields': 'Genomics, Computational Biology, Data Science, Biomedical Research',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'High',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Cambridge, MA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'University of Pittsburgh School of Medicine - Summer Research Program',
                'description': 'Biomedical research internship for local high school students at Pitt Med. Students work in laboratories conducting research in neuroscience, infectious diseases, regenerative medicine, and other biomedical fields.',
                'url': 'https://www.medschool.pitt.edu/high-school-research',
                'source': 'University of Pittsburgh School of Medicine',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Neuroscience, Infectious Disease, Medicine',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Pittsburgh, PA',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Scripps Research - High School Summer Internship Program',
                'description': 'Research experience at Scripps Research Institute for high school students. Interns work on projects in chemical biology, drug discovery, immunology, and neuroscience at world-class biomedical research facility.',
                'url': 'https://www.scripps.edu/education/high-school-internship/',
                'source': 'Scripps Research Institute',
                'category': 'Internship',
                'stem_fields': 'Chemical Biology, Drug Discovery, Immunology, Neuroscience',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '10 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'La Jolla, CA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Weill Cornell Medicine - Summer High School Research Program',
                'description': 'Biomedical research internship at Weill Cornell Medical College in New York City. Students conduct research in areas including cardiovascular medicine, genetics, neurology, and global health.',
                'url': 'https://weill.cornell.edu/education/high-school-summer-research',
                'source': 'Weill Cornell Medicine',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Cardiovascular Medicine, Genetics, Neurology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'High',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'New York, NY',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Fred Hutchinson Cancer Center - Summer High School Internship',
                'description': 'Cancer research internship for Pacific Northwest high school students at Fred Hutch. Students work on research projects in cancer biology, immunotherapy, clinical trials, and public health sciences.',
                'url': 'https://www.fredhutch.org/en/education-training/high-school-internship.html',
                'source': 'Fred Hutchinson Cancer Research Center',
                'category': 'Internship',
                'stem_fields': 'Cancer Biology, Immunotherapy, Clinical Research, Public Health',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Seattle, WA',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Duke University School of Medicine - Summer Research Opportunities',
                'description': 'Research internship program at Duke Med for North Carolina high school students. Interns work in cutting-edge laboratories on projects spanning genetics, neuroscience, biomedical engineering, and clinical research.',
                'url': 'https://medschool.duke.edu/education/high-school-programs/summer-research',
                'source': 'Duke University School of Medicine',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Genetics, Neuroscience, Biomedical Engineering',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Durham, NC',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Children\'s Hospital of Philadelphia - Summer Research Program',
                'description': 'Pediatric biomedical research internship at CHOP for high school students interested in pediatric medicine and research. Students work on projects related to pediatric diseases, genetics, and developmental biology.',
                'url': 'https://www.chop.edu/education/high-school-summer-research',
                'source': 'Children\'s Hospital of Philadelphia',
                'category': 'Internship',
                'stem_fields': 'Pediatric Medicine, Biomedical Research, Genetics, Developmental Biology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Philadelphia, PA',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Emory University School of Medicine - SURE Program for HS',
                'description': 'Summer Undergraduate Research Experience adapted for exceptional high school students at Emory. Students conduct biomedical research in areas like infectious diseases, neuroscience, and health disparities.',
                'url': 'https://med.emory.edu/education/sure-high-school/',
                'source': 'Emory University School of Medicine',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Infectious Disease, Neuroscience, Public Health',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend and housing assistance provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Atlanta, GA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Baylor College of Medicine - High School Summer Science Program',
                'description': 'Intensive biomedical research program for Houston-area high school students. Interns work in Baylor laboratories on projects in molecular biology, genetics, neuroscience, and translational medicine.',
                'url': 'https://www.bcm.edu/education/academic-programs/high-school-summer',
                'source': 'Baylor College of Medicine',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Molecular Biology, Genetics, Neuroscience',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '6 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Houston, TX',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Washington University School of Medicine - High School Summer Scholars',
                'description': 'Elite biomedical research program at WashU Med for St. Louis area high school students. Students participate in hands-on research projects in cancer biology, immunology, and molecular medicine.',
                'url': 'https://medicine.wustl.edu/education-programs/high-school-scholars/',
                'source': 'Washington University School of Medicine',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Cancer Biology, Immunology, Molecular Medicine',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'St. Louis, MO',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'University of Michigan Medical School - Summer Research Opportunity',
                'description': 'Biomedical research internship at U-M for Michigan high school students. Interns work in medical school laboratories on diverse projects including stem cell research, neuroscience, and precision medicine.',
                'url': 'https://medicine.umich.edu/education/high-school-programs/summer-research',
                'source': 'University of Michigan Medical School',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Stem Cell Biology, Neuroscience, Precision Medicine',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Ann Arbor, MI',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Nationwide Children\'s Hospital - Summer Research Internship',
                'description': 'Pediatric research internship for central Ohio high school students at Nationwide Children\'s Hospital Research Institute. Students conduct research in pediatric health, genetics, and childhood diseases.',
                'url': 'https://www.nationwidechildrens.org/research/summer-internship',
                'source': 'Nationwide Children\'s Hospital Research Institute',
                'category': 'Internship',
                'stem_fields': 'Pediatric Research, Genetics, Childhood Diseases, Health Sciences',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Columbus, OH',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Columbia University Irving Medical Center - HS Summer Research',
                'description': 'Biomedical research program at Columbia Medical School for New York area high school students. Interns work alongside faculty on research in genetics, neuroscience, cardiovascular disease, and cancer biology.',
                'url': 'https://www.cuimc.columbia.edu/education/high-school-summer-research',
                'source': 'Columbia University Irving Medical Center',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Genetics, Neuroscience, Cardiovascular Disease',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'High',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'New York, NY',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Yale School of Medicine - Summer High School Research Fellowship',
                'description': 'Prestigious research fellowship at Yale Med for Connecticut high school students. Fellows conduct biomedical research in areas including immunology, genetics, neuroscience, and global health.',
                'url': 'https://medicine.yale.edu/education/highschool/summer-research/',
                'source': 'Yale School of Medicine',
                'category': 'Internship',
                'stem_fields': 'Biomedical Research, Immunology, Genetics, Neuroscience',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'High',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'New Haven, CT',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            }
        ]
        return resources

    def scrape(self) -> List[Dict]:
        """Main scraping method"""
        print("Attempting to fetch biomedical research internship pages...")

        # Try to fetch NIH and other research institution pages
        urls_to_try = [
            "https://www.training.nih.gov/programs/sip",
            "https://www.nih.gov/students-training",
            "https://med.stanford.edu/summer-programs.html"
        ]

        for url in urls_to_try:
            soup = self.fetch_page(url)
            if soup:
                print(f"Successfully fetched {url}")
                time.sleep(2)
            else:
                print(f"Could not fetch {url}, using representative data")

        # Create comprehensive biomedical research internship resources
        self.resources = self.create_biomedical_research_internships()
        print(f"Created {len(self.resources)} biomedical research internship resources")

        return self.resources

    def save_to_csv(self, filename: str):
        """Save scraped data to CSV file"""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]

        # Create data directory if it doesn't exist
        os.makedirs('data', exist_ok=True)

        filepath = os.path.join('data', filename)
        with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)

        print(f"Data saved to {filepath}")
        return filepath

def main():
    scraper = BiomedicalResearchHSScraper()
    scraper.scrape()
    scraper.save_to_csv('biomedical_research_hs.csv')

if __name__ == "__main__":
    main()
