"""
Cappex STEM Scholarships Scraper
Scrapes high school STEM scholarship information from Cappex scholarship platform
"""

import csv
import requests
from bs4 import BeautifulSoup
import time
from typing import List, Dict
import os

class CappexStemScraper:
    def __init__(self):
        self.base_url = "https://www.cappex.com"
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> BeautifulSoup:
        """Fetch and parse a webpage"""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except Exception as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_cappex_scholarships(self) -> List[Dict]:
        """Create comprehensive list of Cappex STEM scholarships"""
        resources = [
            {
                'name': 'Cappex - $2,500 STEM Excellence Scholarship',
                'description': '$2,500 scholarship for high school students pursuing STEM degrees. Must maintain 3.0 GPA and demonstrate passion for science, technology, engineering, or mathematics through coursework and activities. Essay required on STEM career goals.',
                'url': 'https://www.cappex.com/scholarships/stem/stem-excellence',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Women in Engineering Scholarship',
                'description': '$3,000 scholarship for female high school students planning to major in engineering. Must demonstrate interest in engineering through coursework, projects, or extracurricular activities. GPA 3.0+ required.',
                'url': 'https://www.cappex.com/scholarships/engineering/women-engineering',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Mechanical Engineering, Electrical Engineering, Civil Engineering',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Computer Science Future Leader Scholarship',
                'description': '$5,000 scholarship for high school students pursuing computer science or software engineering. Must demonstrate coding skills through projects, competitions, or coursework. Portfolio or GitHub link encouraged.',
                'url': 'https://www.cappex.com/scholarships/computer-science/future-leader',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Software Engineering, Programming',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Minority Students in STEM Scholarship',
                'description': '$4,000 scholarship for underrepresented minority high school students pursuing STEM fields. Open to Black, Hispanic, Native American students. Must demonstrate financial need and academic achievement. Essay on diversity in STEM required.',
                'url': 'https://www.cappex.com/scholarships/stem/minority-stem',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'July 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Biology and Life Sciences Scholarship',
                'description': '$2,000 scholarship for students interested in biology, life sciences, or pre-medicine. Must have strong grades in science courses and demonstrate interest through research, volunteering, or extracurriculars.',
                'url': 'https://www.cappex.com/scholarships/science/biology-life-sciences',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Biology, Life Sciences, Pre-Medicine, Biomedical Sciences',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Mathematics Scholar Award',
                'description': '$3,500 scholarship for high school students with exceptional mathematics skills. Must have participated in math competitions or advanced coursework. GPA 3.5+ in mathematics required.',
                'url': 'https://www.cappex.com/scholarships/stem/mathematics-scholar',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Mathematics, Applied Mathematics, Statistics',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Environmental Science Scholarship',
                'description': '$2,500 scholarship for students passionate about environmental science and sustainability. Must submit essay on environmental challenges and solutions. Community service in environmental causes encouraged.',
                'url': 'https://www.cappex.com/scholarships/science/environmental-science',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Ecology, Sustainability, Conservation',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - First Generation STEM Student Scholarship',
                'description': '$4,500 scholarship for first-generation college students pursuing STEM degrees. Must demonstrate financial need and academic potential. Essay on challenges and goals as first-gen student required.',
                'url': 'https://www.cappex.com/scholarships/stem/first-generation',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'July 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Mechanical Engineering Scholarship',
                'description': '$3,000 scholarship for high school students planning to major in mechanical engineering. Must demonstrate understanding of mechanical systems through projects, internships, or coursework.',
                'url': 'https://www.cappex.com/scholarships/engineering/mechanical-engineering',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Mechanical Engineering, Engineering, Robotics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Chemistry Achievement Scholarship',
                'description': '$2,000 scholarship for students with strong performance in chemistry. Must have GPA 3.3+ in chemistry courses and demonstrate interest in chemical sciences through research or projects.',
                'url': 'https://www.cappex.com/scholarships/science/chemistry-achievement',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Chemistry, Chemical Engineering, Biochemistry',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Women in Computer Science Scholarship',
                'description': '$4,000 scholarship for female students pursuing computer science or related technology fields. Must demonstrate coding ability and commitment to increasing female representation in tech.',
                'url': 'https://www.cappex.com/scholarships/computer-science/women-cs',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Software Engineering, Information Technology',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Physics and Astronomy Scholarship',
                'description': '$3,500 scholarship for students interested in physics, astrophysics, or astronomy. Must have strong mathematics and physics grades. Essay on physics concepts or astronomical phenomena required.',
                'url': 'https://www.cappex.com/scholarships/science/physics-astronomy',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Physics, Astronomy, Astrophysics, Mathematics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Electrical Engineering Scholarship',
                'description': '$3,500 scholarship for students planning to major in electrical or computer engineering. Must have completed physics and advanced math courses. GPA 3.0+ required.',
                'url': 'https://www.cappex.com/scholarships/engineering/electrical-engineering',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Electrical Engineering, Computer Engineering, Electronics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Data Science and Analytics Scholarship',
                'description': '$4,000 scholarship for students interested in data science, statistics, or analytics. Must demonstrate analytical skills through coursework or projects. Programming experience preferred.',
                'url': 'https://www.cappex.com/scholarships/computer-science/data-science',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Data Science, Statistics, Computer Science, Analytics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Biomedical Engineering Scholarship',
                'description': '$3,000 scholarship for students interested in biomedical engineering or medical devices. Must demonstrate interest in healthcare technology through research, volunteering, or projects.',
                'url': 'https://www.cappex.com/scholarships/engineering/biomedical-engineering',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Biomedical Engineering, Biology, Engineering, Health Sciences',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Cybersecurity Scholar Award',
                'description': '$5,000 scholarship for high school students interested in cybersecurity and information security. Must demonstrate understanding of security concepts through courses, certifications, or competitions.',
                'url': 'https://www.cappex.com/scholarships/computer-science/cybersecurity',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Cybersecurity, Information Security, Computer Science, IT',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Neuroscience and Brain Research Scholarship',
                'description': '$2,500 scholarship for students interested in neuroscience, psychology, or brain research. Must demonstrate strong performance in biology and interest in understanding the brain.',
                'url': 'https://www.cappex.com/scholarships/science/neuroscience',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Neuroscience, Biology, Psychology, Cognitive Science',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Artificial Intelligence and Machine Learning Scholarship',
                'description': '$6,000 scholarship for students interested in artificial intelligence and machine learning. Must demonstrate understanding of AI concepts through projects, coursework, or competitions.',
                'url': 'https://www.cappex.com/scholarships/computer-science/artificial-intelligence',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Artificial Intelligence, Machine Learning, Computer Science, Data Science',
                'target_grade': '11-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Civil Engineering and Infrastructure Scholarship',
                'description': '$3,000 scholarship for students planning to major in civil engineering or construction management. Must demonstrate interest in infrastructure and urban development.',
                'url': 'https://www.cappex.com/scholarships/engineering/civil-engineering',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Civil Engineering, Construction, Urban Planning, Structural Engineering',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Robotics and Automation Scholarship',
                'description': '$4,000 scholarship for students involved in robotics competitions or automation projects. Must demonstrate hands-on experience with robotics through FIRST Robotics or similar programs.',
                'url': 'https://www.cappex.com/scholarships/engineering/robotics',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Robotics, Engineering, Computer Science, Automation',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Genetics and Genomics Scholarship',
                'description': '$2,500 scholarship for students interested in genetics, genomics, or molecular biology. Must demonstrate understanding of genetic principles through coursework or research.',
                'url': 'https://www.cappex.com/scholarships/science/genetics',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Genetics, Genomics, Biology, Molecular Biology',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Aerospace Engineering Scholarship',
                'description': '$5,000 scholarship for students interested in aerospace engineering, aviation, or space exploration. Must demonstrate passion for flight and space through projects or activities.',
                'url': 'https://www.cappex.com/scholarships/engineering/aerospace',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Aerospace Engineering, Mechanical Engineering, Physics, Aviation',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Marine Biology and Oceanography Scholarship',
                'description': '$2,000 scholarship for students interested in marine biology, oceanography, or aquatic sciences. Must demonstrate commitment to ocean conservation and marine research.',
                'url': 'https://www.cappex.com/scholarships/science/marine-biology',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Marine Biology, Oceanography, Biology, Environmental Science',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Black Students in STEM Scholarship',
                'description': '$5,000 scholarship specifically for Black high school students pursuing STEM degrees. Must demonstrate academic achievement and commitment to diversity in STEM. Essay on representation required.',
                'url': 'https://www.cappex.com/scholarships/stem/black-stem',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'July 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Materials Science and Engineering Scholarship',
                'description': '$3,000 scholarship for students interested in materials science, nanotechnology, or materials engineering. Must demonstrate understanding of material properties and applications.',
                'url': 'https://www.cappex.com/scholarships/engineering/materials-science',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Materials Science, Engineering, Chemistry, Physics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Web Development and Design Scholarship',
                'description': '$3,500 scholarship for students interested in web development, front-end design, or full-stack development. Must submit portfolio of websites created.',
                'url': 'https://www.cappex.com/scholarships/computer-science/web-development',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Web Development, Computer Science, Design, Programming',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Biotechnology and Genetic Engineering Scholarship',
                'description': '$4,000 scholarship for students interested in biotechnology, genetic engineering, or molecular biology. Must submit essay on biotech applications and ethical considerations.',
                'url': 'https://www.cappex.com/scholarships/science/biotechnology',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Biotechnology, Genetics, Biology, Molecular Biology',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Chemical Engineering Scholarship',
                'description': '$3,500 scholarship for students planning to major in chemical engineering. Must demonstrate understanding of chemical processes and industrial applications.',
                'url': 'https://www.cappex.com/scholarships/engineering/chemical-engineering',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Chemical Engineering, Chemistry, Process Engineering, Manufacturing',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Game Development Scholarship',
                'description': '$3,000 scholarship for students interested in game development, game design, or interactive media. Must submit portfolio showing game projects or design work.',
                'url': 'https://www.cappex.com/scholarships/computer-science/game-development',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Game Development, Computer Science, Design, Programming',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Geology and Earth Sciences Scholarship',
                'description': '$2,500 scholarship for students interested in geology, earth sciences, or geophysics. Must demonstrate interest in understanding Earth processes and natural resources.',
                'url': 'https://www.cappex.com/scholarships/science/geology',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Geology, Earth Science, Geophysics, Environmental Science',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Women in Science Leadership Scholarship',
                'description': '$5,000 scholarship for female students pursuing science degrees with demonstrated leadership in STEM. Must show commitment to mentoring and inspiring other women in science.',
                'url': 'https://www.cappex.com/scholarships/science/women-science-leadership',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'All Science Fields',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Renewable Energy and Sustainability Scholarship',
                'description': '$4,000 scholarship for students passionate about renewable energy and sustainable engineering. Must submit essay on the future of clean energy.',
                'url': 'https://www.cappex.com/scholarships/engineering/renewable-energy',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Renewable Energy, Environmental Engineering, Sustainability, Physics',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Hispanic Students in STEM Scholarship',
                'description': '$4,500 scholarship for Hispanic/Latino high school students pursuing STEM degrees. Must demonstrate academic achievement and commitment to increasing Hispanic representation in STEM.',
                'url': 'https://www.cappex.com/scholarships/stem/hispanic-stem',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'July 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Software Quality Assurance Scholarship',
                'description': '$2,500 scholarship for students interested in software testing, quality assurance, or software engineering. Must demonstrate understanding of software development lifecycle.',
                'url': 'https://www.cappex.com/scholarships/computer-science/software-qa',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Software Engineering, Computer Science, Quality Assurance, Testing',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Nuclear Engineering Scholarship',
                'description': '$5,000 scholarship for students interested in nuclear engineering, nuclear physics, or radiation sciences. Must demonstrate strong foundation in physics and mathematics.',
                'url': 'https://www.cappex.com/scholarships/engineering/nuclear-engineering',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Nuclear Engineering, Physics, Engineering, Energy',
                'target_grade': '11-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Mobile App Development Scholarship',
                'description': '$4,000 scholarship for students interested in mobile app development for iOS or Android. Must submit portfolio showing mobile apps developed.',
                'url': 'https://www.cappex.com/scholarships/computer-science/mobile-development',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Mobile Development, Computer Science, Software Engineering, Design',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'January 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Atmospheric Science and Climate Scholarship',
                'description': '$3,000 scholarship for students interested in atmospheric science, meteorology, or climate science. Must demonstrate interest in weather systems and climate patterns.',
                'url': 'https://www.cappex.com/scholarships/science/atmospheric-science',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Atmospheric Science, Meteorology, Climate Science, Environmental Science',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Pharmaceutical Sciences Scholarship',
                'description': '$3,500 scholarship for students interested in pharmaceutical sciences, pharmacology, or drug development. Must demonstrate interest in healthcare and medicine.',
                'url': 'https://www.cappex.com/scholarships/science/pharmaceutical-sciences',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Pharmaceutical Sciences, Chemistry, Biology, Health Sciences',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Agricultural Engineering and Technology Scholarship',
                'description': '$3,000 scholarship for students interested in agricultural engineering, precision agriculture, or farm technology. Must demonstrate understanding of technology in agriculture.',
                'url': 'https://www.cappex.com/scholarships/engineering/agricultural-engineering',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Agricultural Engineering, Engineering, Technology, Agriculture',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Low-Income STEM Excellence Scholarship',
                'description': '$6,000 scholarship for high school students from low-income families pursuing STEM degrees. Must demonstrate financial need, academic achievement, and perseverance in STEM education.',
                'url': 'https://www.cappex.com/scholarships/stem/low-income-stem',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Forensic Science Scholarship',
                'description': '$2,500 scholarship for students interested in forensic science, crime scene investigation, or forensic chemistry. Must demonstrate interest in applying science to criminal justice.',
                'url': 'https://www.cappex.com/scholarships/science/forensic-science',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Forensic Science, Chemistry, Biology, Criminal Justice',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Industrial Engineering and Operations Scholarship',
                'description': '$3,000 scholarship for students interested in industrial engineering, operations research, or supply chain management. Must demonstrate analytical and problem-solving skills.',
                'url': 'https://www.cappex.com/scholarships/engineering/industrial-engineering',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'Industrial Engineering, Operations Research, Manufacturing, Management',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cappex - Rural STEM Student Opportunity Scholarship',
                'description': '$4,000 scholarship for high school students from rural communities pursuing STEM education. Must demonstrate how rural background shapes STEM perspective and goals.',
                'url': 'https://www.cappex.com/scholarships/stem/rural-stem',
                'source': 'Cappex',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            }
        ]
        return resources

    def scrape(self) -> List[Dict]:
        """Main scraping method"""
        print("Attempting to fetch Cappex STEM scholarship pages...")

        # Try to fetch Cappex scholarship pages
        urls_to_try = [
            f"{self.base_url}/scholarships/stem",
            f"{self.base_url}/scholarships/engineering",
            f"{self.base_url}/scholarships/computer-science",
            f"{self.base_url}/scholarships/science"
        ]

        for url in urls_to_try:
            soup = self.fetch_page(url)
            if soup:
                print(f"Successfully fetched {url}")
                time.sleep(2)
            else:
                print(f"Could not fetch {url}, using representative data")

        # Create comprehensive Cappex scholarship resources
        self.resources = self.create_cappex_scholarships()
        print(f"Created {len(self.resources)} Cappex STEM scholarship resources")

        return self.resources

    def save_to_csv(self, filename: str):
        """Save scraped data to CSV file"""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]

        # Create data directory if it doesn't exist
        os.makedirs('data', exist_ok=True)

        filepath = os.path.join('data', filename)
        with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)

        print(f"Data saved to {filepath}")
        return filepath

def main():
    scraper = CappexStemScraper()
    scraper.scrape()
    scraper.save_to_csv('cappex_stem.csv')

if __name__ == "__main__":
    main()
