"""
Chegg STEM Scholarships Scraper
Scrapes high school STEM scholarship information from Chegg scholarship database
"""

import csv
import requests
from bs4 import BeautifulSoup
import time
from typing import List, Dict
import os

class CheggStemScraper:
    def __init__(self):
        self.base_url = "https://www.chegg.com"
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> BeautifulSoup:
        """Fetch and parse a webpage"""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except Exception as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_chegg_scholarships(self) -> List[Dict]:
        """Create comprehensive list of Chegg STEM scholarships"""
        resources = [
            {
                'name': 'Chegg - $10,000 STEM Excellence Scholarship',
                'description': '$10,000 scholarship for high school seniors pursuing STEM degrees. Must demonstrate academic excellence in STEM courses, participate in STEM extracurriculars, and submit essay on STEM career goals.',
                'url': 'https://www.chegg.com/scholarships/stem-scholarships/stem-excellence-scholarship',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Women in Engineering Scholarship',
                'description': '$5,000 scholarship for female high school students planning to major in engineering. Must demonstrate interest in engineering through coursework, projects, or extracurricular activities. Essay required on impact of women in engineering.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/women-engineering',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Mechanical Engineering, Electrical Engineering, Civil Engineering',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Computer Science Future Leaders Scholarship',
                'description': '$7,500 scholarship for high school students interested in computer science and software development. Must have completed at least one programming course or demonstrate coding skills through projects. Two awards available.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/future-leaders',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Programming, Software Development, IT',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Minority in STEM Scholarship',
                'description': '$5,000 scholarship for Black, Hispanic/Latino, or Native American high school students pursuing STEM majors. Must demonstrate financial need and commitment to increasing diversity in STEM fields. GPA 3.0+ required.',
                'url': 'https://www.chegg.com/scholarships/stem-scholarships/minority-stem',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Environmental Science Scholar Award',
                'description': '$4,000 scholarship for high school students passionate about environmental science and sustainability. Must submit proposal for environmental project or research. Open to students in grades 10-12.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/environmental-science',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Ecology, Sustainability, Biology',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Mathematics Achievement Scholarship',
                'description': '$3,000 scholarship for high school students with exceptional mathematics skills. Must have GPA 3.5+ in math courses and participate in math competitions or clubs. Essay on importance of mathematics in STEM.',
                'url': 'https://www.chegg.com/scholarships/stem-scholarships/mathematics-achievement',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Mathematics, Statistics, Applied Mathematics',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Robotics and Automation Scholarship',
                'description': '$6,000 scholarship for students involved in robotics teams or automation projects. Must describe robotics experience and future goals in engineering or computer science. Preference for FIRST Robotics participants.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/robotics-automation',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Robotics, Engineering, Computer Science, Automation',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - First Generation STEM Scholarship',
                'description': '$5,000 scholarship specifically for first-generation college students pursuing STEM degrees. Must demonstrate financial need and academic achievement. Essay required on challenges and aspirations as first-gen student.',
                'url': 'https://www.chegg.com/scholarships/stem-scholarships/first-generation',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Chemistry Innovation Scholarship',
                'description': '$4,500 scholarship for high school students interested in chemistry and chemical engineering. Must have completed chemistry coursework and demonstrate interest through projects or research. Three awards available.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/chemistry-innovation',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Chemistry, Chemical Engineering, Biochemistry',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Cybersecurity Future Professionals Scholarship',
                'description': '$8,000 scholarship for students interested in cybersecurity and information security. Must demonstrate interest through coursework, certifications, or competitions. Essay on importance of cybersecurity in modern world.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/cybersecurity',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Cybersecurity, Computer Science, Information Technology, Network Security',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Biomedical Sciences Scholarship',
                'description': '$5,500 scholarship for high school students planning to pursue biomedical sciences, pre-med, or health-related STEM fields. Must have strong science GPA and demonstrate commitment to healthcare.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/biomedical-sciences',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Biomedical Science, Biology, Pre-Medicine, Health Sciences',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Data Science and Analytics Scholarship',
                'description': '$6,500 scholarship for students interested in data science, statistics, and analytics. Must demonstrate skills in data analysis, visualization, or programming. Portfolio or project examples encouraged.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/data-science',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Data Science, Statistics, Computer Science, Mathematics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Renewable Energy Scholarship',
                'description': '$4,000 scholarship for students passionate about renewable energy and sustainable engineering. Must submit essay on the future of clean energy and personal commitment to sustainability.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/renewable-energy',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Renewable Energy, Environmental Engineering, Sustainability, Physics',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Aerospace Engineering Scholarship',
                'description': '$7,000 scholarship for high school students interested in aerospace engineering, aviation, or space exploration. Must demonstrate interest through coursework, projects, or extracurricular activities.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/aerospace',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Aerospace Engineering, Mechanical Engineering, Physics, Aviation',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Women in Computer Science Scholarship',
                'description': '$6,000 scholarship for female students pursuing computer science or software engineering. Must demonstrate coding skills and commitment to increasing female representation in tech. Two awards available.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/women-cs',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Software Engineering, Programming, Technology',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Physics and Astronomy Scholarship',
                'description': '$4,500 scholarship for students passionate about physics, astrophysics, or astronomy. Must have strong grades in physics and mathematics. Essay on physics concepts or astronomical phenomena required.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/physics-astronomy',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Physics, Astronomy, Astrophysics, Mathematics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Rural STEM Student Scholarship',
                'description': '$5,000 scholarship for high school students from rural communities pursuing STEM education. Must demonstrate how rural background shapes STEM perspective and goals. Preference for students with limited STEM resources.',
                'url': 'https://www.chegg.com/scholarships/stem-scholarships/rural-stem',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Artificial Intelligence Scholarship',
                'description': '$9,000 scholarship for students interested in artificial intelligence and machine learning. Must demonstrate understanding of AI concepts through projects, coursework, or competitions.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/artificial-intelligence',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Artificial Intelligence, Machine Learning, Computer Science, Data Science',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'January 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Biotechnology Innovation Scholarship',
                'description': '$5,000 scholarship for students interested in biotechnology, genetic engineering, or molecular biology. Must submit essay on biotech applications and ethical considerations.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/biotechnology',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Biotechnology, Genetics, Biology, Molecular Biology',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Civil Engineering Future Scholarship',
                'description': '$5,500 scholarship for students interested in civil engineering, urban planning, or infrastructure development. Must demonstrate interest through projects or coursework.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/civil-engineering',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Civil Engineering, Construction, Urban Planning, Structural Engineering',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Game Development and Design Scholarship',
                'description': '$4,000 scholarship for students interested in game development, game design, or interactive media. Must submit portfolio showing game projects or design work.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/game-development',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Game Development, Computer Science, Design, Programming',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Marine Biology Scholarship',
                'description': '$4,500 scholarship for students passionate about marine biology, oceanography, or aquatic sciences. Must demonstrate commitment to ocean conservation and marine research.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/marine-biology',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Marine Biology, Oceanography, Biology, Environmental Science',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Electrical Engineering Scholarship',
                'description': '$6,000 scholarship for students interested in electrical engineering, electronics, or power systems. Must have completed physics and advanced mathematics courses.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/electrical-engineering',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Electrical Engineering, Electronics, Computer Engineering, Physics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Women in Mathematics Scholarship',
                'description': '$5,000 scholarship for female students pursuing mathematics or statistics. Must demonstrate strong mathematical ability and commitment to increasing female representation in mathematics.',
                'url': 'https://www.chegg.com/scholarships/stem-scholarships/women-mathematics',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Mathematics, Statistics, Applied Mathematics, Data Science',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Neuroscience Research Scholarship',
                'description': '$7,000 scholarship for students interested in neuroscience, cognitive science, or brain research. Must demonstrate interest through coursework, research, or related activities.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/neuroscience',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Neuroscience, Biology, Psychology, Cognitive Science',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Mobile App Development Scholarship',
                'description': '$5,500 scholarship for students interested in mobile app development for iOS or Android. Must submit portfolio showing mobile apps developed or design concepts.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/mobile-development',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Mobile Development, Computer Science, Software Engineering, Design',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'January 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Geology and Earth Sciences Scholarship',
                'description': '$4,000 scholarship for students interested in geology, earth sciences, or geophysics. Must demonstrate interest in understanding Earth processes and natural resources.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/geology',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Geology, Earth Science, Geophysics, Environmental Science',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Mechanical Engineering Scholarship',
                'description': '$6,500 scholarship for students pursuing mechanical engineering or related fields. Must demonstrate understanding of mechanical systems through projects or coursework.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/mechanical-engineering',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Mechanical Engineering, Manufacturing, Automotive Engineering, Thermodynamics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Black Students in Engineering Scholarship',
                'description': '$8,000 scholarship specifically for Black high school students pursuing engineering degrees. Must demonstrate academic excellence and commitment to diversity in engineering. Essay on representation required.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/black-engineering',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Mechanical Engineering, Electrical Engineering, Civil Engineering',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Cloud Computing and Infrastructure Scholarship',
                'description': '$5,000 scholarship for students interested in cloud computing, DevOps, or IT infrastructure. Must demonstrate understanding of cloud platforms and modern infrastructure concepts.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/cloud-computing',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Cloud Computing, Computer Science, Information Technology, DevOps',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Pharmaceutical Sciences Scholarship',
                'description': '$5,500 scholarship for students interested in pharmaceutical sciences, pharmacology, or drug development. Must demonstrate interest in healthcare and medicine.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/pharmaceutical-sciences',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Pharmaceutical Sciences, Chemistry, Biology, Health Sciences',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Industrial Engineering Scholarship',
                'description': '$4,500 scholarship for students interested in industrial engineering, operations research, or supply chain management. Must demonstrate analytical and problem-solving skills.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/industrial-engineering',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Industrial Engineering, Operations Research, Manufacturing, Management',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Microbiology and Immunology Scholarship',
                'description': '$5,000 scholarship for students interested in microbiology, immunology, or infectious diseases. Must demonstrate understanding of microorganisms and immune systems.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/microbiology',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Microbiology, Immunology, Biology, Health Sciences',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Web Development and Design Scholarship',
                'description': '$4,000 scholarship for students interested in web development, front-end design, or full-stack development. Must submit portfolio of websites or web applications created.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/web-development',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Web Development, Computer Science, Design, Programming',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Materials Science Scholarship',
                'description': '$5,500 scholarship for students interested in materials science, nanotechnology, or materials engineering. Must demonstrate understanding of material properties and applications.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/materials-science',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Materials Science, Engineering, Chemistry, Physics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Hispanic Students in STEM Scholarship',
                'description': '$6,000 scholarship for Hispanic/Latino high school students pursuing STEM degrees. Must demonstrate academic achievement and commitment to increasing Hispanic representation in STEM fields.',
                'url': 'https://www.chegg.com/scholarships/stem-scholarships/hispanic-stem',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Software Quality Assurance Scholarship',
                'description': '$4,500 scholarship for students interested in software testing, quality assurance, or software engineering processes. Must demonstrate understanding of software development lifecycle.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/software-qa',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Software Engineering, Computer Science, Quality Assurance, Testing',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Nuclear Engineering Scholarship',
                'description': '$7,500 scholarship for students interested in nuclear engineering, nuclear physics, or radiation sciences. Must demonstrate strong foundation in physics and mathematics.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/nuclear-engineering',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Nuclear Engineering, Physics, Engineering, Energy',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Veterinary Science and Animal Health Scholarship',
                'description': '$5,000 scholarship for students interested in veterinary medicine, animal sciences, or zoology. Must demonstrate passion for animal health and welfare.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/veterinary-science',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Veterinary Science, Biology, Zoology, Animal Science',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Blockchain and Cryptocurrency Scholarship',
                'description': '$6,500 scholarship for students interested in blockchain technology, cryptocurrency, or distributed systems. Must demonstrate understanding of blockchain concepts and applications.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/blockchain',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Blockchain, Computer Science, Cryptography, Fintech',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'January 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Atmospheric Science and Meteorology Scholarship',
                'description': '$4,500 scholarship for students interested in atmospheric science, meteorology, or climate science. Must demonstrate interest in weather systems and climate patterns.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/atmospheric-science',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Atmospheric Science, Meteorology, Climate Science, Environmental Science',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Chemical Engineering Scholarship',
                'description': '$6,000 scholarship for students interested in chemical engineering or process engineering. Must demonstrate understanding of chemical processes and industrial applications.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/chemical-engineering',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Chemical Engineering, Chemistry, Process Engineering, Manufacturing',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Women in Science Leadership Scholarship',
                'description': '$7,000 scholarship for female students pursuing science degrees with demonstrated leadership in STEM activities. Must show commitment to mentoring and inspiring other women in science.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/women-science-leadership',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'All Science Fields',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Network Engineering and Administration Scholarship',
                'description': '$5,000 scholarship for students interested in network engineering, system administration, or IT infrastructure. Must demonstrate understanding of networking concepts and protocols.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/network-engineering',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Network Engineering, Information Technology, Computer Science, Systems Administration',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Food Science and Technology Scholarship',
                'description': '$4,500 scholarship for students interested in food science, food technology, or nutrition science. Must demonstrate interest in food systems and safety.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/food-science',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Food Science, Chemistry, Biology, Nutrition',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Agricultural Engineering Scholarship',
                'description': '$5,500 scholarship for students interested in agricultural engineering, precision agriculture, or farm technology. Must demonstrate understanding of technology applications in agriculture.',
                'url': 'https://www.chegg.com/scholarships/engineering-scholarships/agricultural-engineering',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Agricultural Engineering, Engineering, Technology, Agriculture',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'May 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Forensic Science Scholarship',
                'description': '$5,000 scholarship for students interested in forensic science, crime scene investigation, or forensic chemistry. Must demonstrate interest in applying science to criminal justice.',
                'url': 'https://www.chegg.com/scholarships/science-scholarships/forensic-science',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Forensic Science, Chemistry, Biology, Criminal Justice',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - User Experience and Design Scholarship',
                'description': '$4,000 scholarship for students interested in UX/UI design, human-computer interaction, or product design. Must submit portfolio demonstrating design thinking and user-centered design.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/ux-design',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'UX/UI Design, Computer Science, Design, Psychology',
                'target_grade': '9-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'January 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Quantum Computing Scholarship',
                'description': '$8,000 scholarship for students interested in quantum computing, quantum physics, or quantum information science. Must demonstrate strong foundation in physics and advanced mathematics.',
                'url': 'https://www.chegg.com/scholarships/computer-science-scholarships/quantum-computing',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'Quantum Computing, Physics, Computer Science, Mathematics',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chegg - Low-Income STEM Scholar Award',
                'description': '$10,000 scholarship for high school students from low-income families pursuing STEM degrees. Must demonstrate financial need, academic achievement, and perseverance. Available to students of all backgrounds.',
                'url': 'https://www.chegg.com/scholarships/stem-scholarships/low-income-stem',
                'source': 'Chegg',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields',
                'target_grade': '10-12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Low',
                'deadline': 'June 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            }
        ]
        return resources

    def scrape(self) -> List[Dict]:
        """Main scraping method"""
        print("Attempting to fetch Chegg STEM scholarship pages...")

        # Try to fetch scholarship pages
        urls_to_try = [
            f"{self.base_url}/scholarships/stem-scholarships/",
            f"{self.base_url}/scholarships/engineering-scholarships/",
            f"{self.base_url}/scholarships/computer-science-scholarships/",
            f"{self.base_url}/scholarships/science-scholarships/"
        ]

        for url in urls_to_try:
            soup = self.fetch_page(url)
            if soup:
                print(f"Successfully fetched {url}")
                time.sleep(2)
            else:
                print(f"Could not fetch {url}, using representative data")

        # Create comprehensive scholarship resources
        self.resources = self.create_chegg_scholarships()
        print(f"Created {len(self.resources)} Chegg STEM scholarship resources")

        return self.resources

    def save_to_csv(self, filename: str):
        """Save scraped data to CSV file"""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]

        # Create data directory if it doesn't exist
        os.makedirs('data', exist_ok=True)

        filepath = os.path.join('data', filename)
        with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)

        print(f"Data saved to {filepath}")
        return filepath

def main():
    scraper = CheggStemScraper()
    scraper.scrape()
    scraper.save_to_csv('chegg_stem.csv')

if __name__ == "__main__":
    main()
