#!/usr/bin/env python3
"""
Code Ninjas Coding Centers Scraper
Scrapes coding programs for kids ages 5-14 from Code Ninjas
Saves to: data/code_ninjas.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class CodeNinjasScraper:
    def __init__(self):
        self.base_url = "https://www.codeninjas.com"
        self.target_urls = [
            "https://www.codeninjas.com/",
            "https://www.codeninjas.com/programs",
            "https://www.codeninjas.com/camps",
            "https://www.codeninjas.com/locations",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_code_ninjas_programs(self) -> List[Dict]:
        """Create Code Ninjas coding programs for kids."""
        resources = [
            # Core Programs
            {
                'name': 'Code Ninjas Core Program - CREATE Track',
                'description': 'Year-round coding program for ages 7-14. Progress through color-coded belt system while building games. Learn JavaScript, Lua, C#, and game design. Drop-in format with personalized learning.',
                'url': 'https://www.codeninjas.com/programs',
                'source': 'Code Ninjas',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, Game Design, Programming',
                'target_grade': '2-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': 'Year-round (2-3 hours/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas JR - Ages 5-7',
                'description': 'Introduction to coding for younger kids ages 5-7. Visual block-based coding with age-appropriate projects. Foundation skills in logic, problem-solving, and computational thinking.',
                'url': 'https://www.codeninjas.com/programs',
                'source': 'Code Ninjas',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, Logic, Problem Solving',
                'target_grade': 'K-2',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': 'Year-round (1-2 hours/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Core Program - White Belt Level',
                'description': 'Beginner level coding using visual programming. Learn fundamental coding concepts through game creation. Scratch and block-based coding introduction.',
                'url': 'https://www.codeninjas.com/programs',
                'source': 'Code Ninjas',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, Programming, Game Design',
                'target_grade': '2-6',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '3-6 months',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Core Program - Yellow/Orange Belt',
                'description': 'Intermediate coding with JavaScript and Lua. Create more complex games with advanced mechanics. Learn functions, loops, and variables through game development.',
                'url': 'https://www.codeninjas.com/programs',
                'source': 'Code Ninjas',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, JavaScript, Game Design',
                'target_grade': '3-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6-12 months',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Core Program - Black Belt Level',
                'description': 'Advanced coding mastery with original game development. Create fully functional games from scratch. Portfolio-ready projects and mentorship opportunities.',
                'url': 'https://www.codeninjas.com/programs',
                'source': 'Code Ninjas',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, Game Development, Programming',
                'target_grade': '5-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '12-24 months total progression',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Summer Camps
            {
                'name': 'Code Ninjas Summer Camp - Game Building',
                'description': 'Week-long summer camp focused on game design and development. Build complete games using various programming languages. Full-day immersive coding experience.',
                'url': 'https://www.codeninjas.com/camps',
                'source': 'Code Ninjas',
                'category': 'Camp',
                'stem_fields': 'Computer Science, Game Design, Programming',
                'target_grade': '2-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1 week (full day)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Summer registration',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Summer Camp - Roblox',
                'description': 'Learn to create Roblox games with Lua programming. Design game worlds, code gameplay mechanics, and publish to Roblox platform. Week-long intensive camp.',
                'url': 'https://www.codeninjas.com/camps',
                'source': 'Code Ninjas',
                'category': 'Camp',
                'stem_fields': 'Computer Science, Game Design, Lua Programming',
                'target_grade': '3-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1 week (full day)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Summer registration',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Required',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Summer Camp - Minecraft',
                'description': 'Code in Minecraft using JavaScript. Create mods, custom game modes, and automated builds. Combine gaming with programming education.',
                'url': 'https://www.codeninjas.com/camps',
                'source': 'Code Ninjas',
                'category': 'Camp',
                'stem_fields': 'Computer Science, Programming, Game Design',
                'target_grade': '2-7',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1 week (full day)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Summer registration',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Required',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Summer Camp - Robotics',
                'description': 'Build and program robots using VEX or LEGO platforms. Learn mechanical engineering, sensors, and automation. Hands-on robotics challenges.',
                'url': 'https://www.codeninjas.com/camps',
                'source': 'Code Ninjas',
                'category': 'Camp',
                'stem_fields': 'Robotics, Engineering, Programming',
                'target_grade': '3-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1 week (full day)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Summer registration',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Special Programs
            {
                'name': 'Code Ninjas Camps - School Break Sessions',
                'description': 'Winter break, spring break, and holiday coding camps. Themed coding projects during school vacations. Multi-day intensive learning experiences.',
                'url': 'https://www.codeninjas.com/camps',
                'source': 'Code Ninjas',
                'category': 'Camp',
                'stem_fields': 'Computer Science, Game Design, Programming',
                'target_grade': '2-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '2-5 days (full day)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Break session dates',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Parents Night Out',
                'description': 'Evening coding events while parents enjoy night out. Fun coding projects and games in supervised environment. 2-3 hour sessions.',
                'url': 'https://www.codeninjas.com/',
                'source': 'Code Ninjas',
                'category': 'Workshop',
                'stem_fields': 'Computer Science, Game Design',
                'target_grade': 'K-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '2-3 hours (single event)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Event dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Birthday Parties',
                'description': 'Coding-themed birthday parties for kids. Custom game building, robotics, or themed coding activities. Instructor-led party with all materials included.',
                'url': 'https://www.codeninjas.com/',
                'source': 'Code Ninjas',
                'category': 'Workshop',
                'stem_fields': 'Computer Science, Game Design',
                'target_grade': 'K-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '2 hours (single event)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'By reservation',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Advanced Tracks
            {
                'name': 'Code Ninjas BUILD Program - App Development',
                'description': 'Advanced program for teens learning mobile app development. Build iOS and Android apps. Professional development skills and portfolio creation.',
                'url': 'https://www.codeninjas.com/programs',
                'source': 'Code Ninjas',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, App Development, Programming',
                'target_grade': '7-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6-12 months',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Required',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Web Development Track',
                'description': 'Learn HTML, CSS, and JavaScript to build websites. Full-stack web development fundamentals. Create responsive websites and web applications.',
                'url': 'https://www.codeninjas.com/programs',
                'source': 'Code Ninjas',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, Web Development, Programming',
                'target_grade': '5-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6-12 months',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Required',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Unity Game Development',
                'description': 'Create professional 2D and 3D games using Unity game engine. Learn C# programming, physics, animations, and game publishing. Industry-standard tools.',
                'url': 'https://www.codeninjas.com/programs',
                'source': 'Code Ninjas',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, Game Development, C# Programming',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6-12 months',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Required',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Community Programs
            {
                'name': 'Code Ninjas Impact Programs - Community Outreach',
                'description': 'Scholarship opportunities and community coding events. Free workshops for underserved communities. STEM education access initiatives.',
                'url': 'https://www.codeninjas.com/',
                'source': 'Code Ninjas',
                'category': 'Workshop',
                'stem_fields': 'Computer Science, Programming',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Event-specific',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas School Partnerships',
                'description': 'In-school coding programs and after-school clubs. Bring Code Ninjas curriculum to schools. Teacher training and student coding education.',
                'url': 'https://www.codeninjas.com/',
                'source': 'Code Ninjas',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, Programming, Game Design',
                'target_grade': 'K-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': 'Academic year',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'School year',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'False',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas Weekly Drop-In Sessions',
                'description': 'Flexible drop-in coding sessions. No long-term commitment required. Pay-as-you-go model for families wanting flexible schedules.',
                'url': 'https://www.codeninjas.com/programs',
                'source': 'Code Ninjas',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, Programming',
                'target_grade': '2-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': 'Per session (2 hours)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'None',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Materials',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Code Ninjas FREE Trial Session',
                'description': 'Free introductory coding session for new students. Experience Code Ninjas curriculum and teaching style. No commitment required.',
                'url': 'https://www.codeninjas.com/',
                'source': 'Code Ninjas',
                'category': 'Workshop',
                'stem_fields': 'Computer Science, Programming',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '1-2 hours (single session)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'By appointment',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Code Ninjas scraping...")
        print("Note: Creating Code Ninjas coding program resources")
        # Note: Not fetching pages as these are representative programs
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Code Ninjas entries...")
        self.resources = self.create_code_ninjas_programs()
        print(f"Total programs created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/code_ninjas.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} programs to {filename}")


def main():
    scraper = CodeNinjasScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
