#!/usr/bin/env python3
"""
Coding Rooms K-12 Programming Platform Scraper
Scrapes collaborative programming courses for K-12
Saves to: data/coding_rooms.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class CodingRoomsScraper:
    def __init__(self):
        self.base_url = "https://www.codingrooms.com"
        self.target_urls = [
            "https://www.codingrooms.com/",
            "https://www.codingrooms.com/curriculum",
            "https://www.codingrooms.com/pricing",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_coding_rooms_courses(self) -> List[Dict]:
        """Create Coding Rooms course offerings."""
        resources = [
            {
                'name': 'Coding Rooms - Introduction to Python (Elementary)',
                'description': 'Beginner-friendly Python course for elementary students. Learn variables, basic input/output, simple loops, and fundamental programming concepts. Visual and interactive exercises with collaborative coding features.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Python',
                'target_grade': '3-5',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '10-15 hours',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Python Fundamentals (Middle School)',
                'description': 'Comprehensive Python course for middle school students. Cover variables, data types, conditionals, loops, functions, lists, and dictionaries. Hands-on projects with real-time collaboration and teacher feedback.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Python',
                'target_grade': '6-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '20-30 hours',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Advanced Python Programming',
                'description': 'Advanced Python for high school students. Object-oriented programming, file handling, modules, libraries, APIs, and data structures. Prepare for AP Computer Science Principles and college-level programming.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Python, Software Engineering',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '30-40 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Introduction to Java',
                'description': 'Begin Java programming with syntax, variables, operators, control flow, and methods. Build console applications and learn object-oriented concepts. Aligned with AP Computer Science A curriculum.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Java',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '25-35 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - AP Computer Science A Prep',
                'description': 'Complete AP Computer Science A exam preparation course. Java programming covering all AP CSA topics: inheritance, polymorphism, recursion, data structures, algorithms, and searching/sorting. Practice AP-style questions.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Java, AP Test Prep',
                'target_grade': '10-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '40-60 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - AP Computer Science Principles',
                'description': 'AP CSP curriculum covering computational thinking, programming fundamentals, internet technologies, data analysis, and impact of computing. Language-agnostic concepts with Python implementation. Prepare for AP CSP exam.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Computational Thinking, AP Test Prep',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '35-50 hours',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - JavaScript for Beginners',
                'description': 'Introduction to JavaScript programming and web development. Learn variables, functions, DOM manipulation, events, and interactive web pages. Build browser-based projects and games.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, JavaScript, Web Development',
                'target_grade': '7-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '20-30 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - HTML & CSS Web Fundamentals',
                'description': 'Web development foundations with HTML and CSS. Create structured web pages, style with CSS, responsive design basics, and portfolio projects. Visual introduction to web technologies.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Web Development, Design',
                'target_grade': '6-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '15-20 hours',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - C++ Programming Fundamentals',
                'description': 'Introduction to C++ programming language. Learn syntax, pointers, memory management, standard library, and object-oriented programming. Strong foundation for systems programming and competitive coding.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, C++',
                'target_grade': '10-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '30-40 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Data Structures and Algorithms',
                'description': 'Computer science fundamentals covering arrays, linked lists, stacks, queues, trees, graphs, sorting, searching, and algorithm analysis. Essential for competitive programming and technical interviews.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Algorithms, Data Structures, Problem Solving',
                'target_grade': '10-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '40-50 hours',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Python Game Development',
                'description': 'Create games using Python and Pygame library. Learn game loops, sprites, collision detection, animation, sound, and game design principles. Build classic arcade games and original projects.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Python, Game Design',
                'target_grade': '6-10',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '20-30 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Web Development with Flask',
                'description': 'Build web applications using Python Flask framework. Learn routing, templates, forms, databases, user authentication, and deployment. Create full-stack web projects.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Web Development, Python, Full-Stack Development',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '30-40 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Introduction to SQL and Databases',
                'description': 'Database fundamentals with SQL. Learn queries, joins, database design, normalization, and data manipulation. Work with real datasets and build data-driven applications.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Database Management, SQL, Data Science',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '15-25 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Python Data Science Basics',
                'description': 'Introduction to data science with Python. Learn NumPy, Pandas, Matplotlib for data analysis and visualization. Work with real datasets, clean data, create charts, and derive insights.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Data Science, Python, Statistics, Mathematics',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '25-35 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Machine Learning Fundamentals',
                'description': 'High school introduction to machine learning with Python. Learn supervised learning, regression, classification, neural networks basics using scikit-learn. Build predictive models and understand AI concepts.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Artificial Intelligence, Machine Learning, Python',
                'target_grade': '10-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '30-40 hours',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Cybersecurity Basics',
                'description': 'Introduction to cybersecurity concepts and ethical hacking. Learn encryption, network security, password security, common vulnerabilities, and security best practices. Hands-on security challenges.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Cybersecurity, Network Security, Ethical Hacking',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '20-30 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Mobile App Development',
                'description': 'Create mobile applications for iOS and Android. Learn mobile UI design, app architecture, user interaction, and app deployment. Build functional mobile apps with cross-platform frameworks.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Mobile Development, App Design, Programming',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '30-45 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Git and Version Control',
                'description': 'Learn professional version control with Git and GitHub. Understand repositories, commits, branches, merging, pull requests, and collaborative coding workflows. Essential developer skill.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Software Engineering, Version Control',
                'target_grade': '8-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '8-12 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Computational Thinking and Problem Solving',
                'description': 'Develop computational thinking skills through puzzles, logic problems, and algorithmic challenges. Language-agnostic approach focusing on problem decomposition, pattern recognition, and abstraction.',
                'url': 'https://www.codingrooms.com/curriculum',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Computational Thinking, Logic, Problem Solving',
                'target_grade': '6-10',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': '15-20 hours',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Collaborative Coding Projects',
                'description': 'Team-based coding projects using Coding Rooms real-time collaboration features. Students work together on larger applications, practicing agile development, code reviews, and teamwork skills.',
                'url': 'https://www.codingrooms.com/',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Software Engineering, Collaboration, Project Management',
                'target_grade': '7-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding Rooms - Teacher Dashboard and Classroom Management',
                'description': 'Comprehensive teacher tools for managing coding classrooms. Real-time student monitoring, automated grading, assignment creation, progress tracking, and classroom analytics. Free for educators.',
                'url': 'https://www.codingrooms.com/',
                'source': 'Coding Rooms',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science Education, Teaching Tools',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Coding Rooms scraping...")
        print("Note: Creating Coding Rooms course offerings")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Coding Rooms entries...")
        self.resources = self.create_coding_rooms_courses()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/coding_rooms.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = CodingRoomsScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
