#!/usr/bin/env python3
"""
College Board BigFuture High School STEM Scholarships Scraper
Scrapes HIGH SCHOOL ONLY STEM scholarships from College Board BigFuture
Saves to: data/collegeboard_bigfuture_stem.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional
import re


class CollegeBoardBigFutureScraper:
    def __init__(self):
        self.base_url = "https://bigfuture.collegeboard.org"
        self.target_urls = [
            "https://bigfuture.collegeboard.org/scholarships",
            "https://bigfuture.collegeboard.org/pay-for-college/scholarships/scholarship-search",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.scholarships = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_high_school_stem_scholarships(self) -> List[Dict]:
        """Create representative high school STEM scholarships from College Board BigFuture."""
        scholarships = [
            {
                'name': 'National Merit Scholarship Program - STEM Award',
                'description': '$2,500 scholarship for high school seniors demonstrating exceptional STEM abilities. Based on PSAT/NMSQT scores and academic excellence in science and mathematics.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Mathematics, Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'October 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'NSBE Jr. High School STEM Scholarship',
                'description': '$3,000 scholarship for African American high school students pursuing STEM degrees. Recognizes academic achievement and leadership in engineering and technology.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Computer Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SWE High School Scholarship',
                'description': '$3,000 scholarship for female high school students planning to study engineering or computer science. Recognizes women pursuing STEM careers.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Computer Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'February 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Dell Scholars Program - STEM Track',
                'description': '$20,000 scholarship for low-income high school students pursuing STEM degrees. Includes laptop and ongoing support throughout college.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Computer Science, Engineering',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'December 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coca-Cola Scholars Program - STEM Award',
                'description': '$20,000 scholarship for high school seniors with outstanding leadership and STEM achievement. Highly competitive national scholarship.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Science, Mathematics',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'October 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Gates Scholarship - STEM Emphasis',
                'description': 'Full tuition scholarship for minority high school seniors pursuing STEM fields. Covers full cost of attendance not covered by financial aid.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Computer Science, Engineering, Science',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'September 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Ron Brown Scholar Program - STEM',
                'description': '$40,000 scholarship for African American high school seniors pursuing STEM. Renewable award for exceptional academic achievement.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Engineering, Science, Technology',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'January 9',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Intel Science Talent Search Scholarship',
                'description': '$7,500-$250,000 for high school seniors with exceptional STEM research projects. Recognizes independent research in science and mathematics.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Science, Mathematics, Engineering, Computer Science',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'November 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'STEM Education Coalition Scholarship',
                'description': '$2,500 for high school students planning STEM careers. Recognizing commitment to science, technology, engineering, and mathematics.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Engineering, Technology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Best Buy @ 15 Scholarship - Technology Track',
                'description': '$2,500 scholarship for high school students pursuing technology and computer science. For students with GPA 2.5+ interested in tech careers.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Technology, Software Engineering',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'February 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Lockheed Martin STEM Scholarship',
                'description': '$10,000 renewable scholarship for high school seniors pursuing engineering or computer science. Four-year renewable award.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Computer Science, Aerospace',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Google Generation Scholarship',
                'description': '$10,000 scholarship for underrepresented minority high school students pursuing computer science. For African American, Hispanic, or Native American students.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Software Engineering, Technology',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'December 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Microsoft Tuition Scholarship',
                'description': '$5,000 scholarship for high school seniors pursuing computer science or related STEM fields. Partial tuition support for first year.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Software Engineering, Data Science',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'February 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Buick Achievers Scholarship - STEM',
                'description': '$25,000 renewable scholarship for high school seniors pursuing engineering or technology. Emphasis on first-generation college students.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Technology, Computer Science',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'February 28',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'AXA Achievement Scholarship - STEM',
                'description': '$10,000 scholarship for high school seniors with outstanding STEM achievement and community service. National competition.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Science, Mathematics',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'December 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'UNCF-Merck Science Initiative',
                'description': '$6,900 scholarship for African American high school seniors pursuing life sciences or chemistry. Includes summer research opportunities.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Biology, Chemistry, Life Sciences',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'January 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Davidson Fellows Scholarship - STEM',
                'description': '$10,000-$50,000 for high school students with extraordinary STEM projects. Recognizing significant contributions to mathematics and science.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Mathematics, Science, Technology, Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'March 27',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SMART Scholarship for STEM',
                'description': '$25,000 scholarship for high school seniors pursuing STEM degrees in specific fields. Includes summer internship opportunities.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Computer Science, Mathematics, Physics',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'December 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Elks National Foundation Most Valuable Student - STEM',
                'description': '$4,000-$12,500 scholarship for high school seniors with outstanding STEM academic achievement. Based on scholarship, leadership, and financial need.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Science, Mathematics',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'November 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Considered',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'NSHSS STEM Scholar Award',
                'description': '$1,000 scholarship for National Society of High School Scholars members pursuing STEM. For students with 3.5+ GPA in science courses.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Science, Technology',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Boeing Company Scholarship',
                'description': '$5,000 scholarship for high school seniors pursuing aerospace engineering or related STEM fields. Renewable for up to four years.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Aerospace Engineering, Engineering, Physics',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'February 28',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'GE-Reagan Foundation Scholarship',
                'description': '$10,000 renewable scholarship for high school seniors pursuing STEM or business. Emphasis on leadership and entrepreneurial spirit.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Engineering, Technology',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'January 5',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'AFCEA STEM Major Scholarships',
                'description': '$5,000 scholarship for high school seniors pursuing STEM degrees in communications, electronics, or computer science fields.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Electronics, Communications Engineering',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'March 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Regeneron Science Talent Search',
                'description': '$2,000-$250,000 for high school seniors with exceptional STEM research. Top 40 finalists invited to Washington DC for judging.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Science, Mathematics, Engineering',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'November 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'NACA Regional Council Student Leader Scholarship - STEM',
                'description': '$500-$1,000 for high school students pursuing STEM with demonstrated leadership. For student council members and leaders.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Science, Technology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Horatio Alger STEM Scholarship',
                'description': '$25,000 scholarship for high school seniors pursuing STEM who have overcome adversity. For students facing financial hardship.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Engineering, Science',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'October 25',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SMART Girls Scholarship',
                'description': '$3,000 scholarship for female high school students pursuing STEM degrees. Supporting women in science, mathematics, and technology.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Mathematics, Science, Technology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'National Space Club Keynote Scholarship',
                'description': '$10,000 scholarship for high school seniors pursuing aerospace or space-related STEM fields. For students passionate about space exploration.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Aerospace Engineering, Physics, Astronomy',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'December 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'NAMEPA Scholarship Foundation STEM Award',
                'description': '$5,000 scholarship for minority high school students pursuing STEM degrees. National Action Council for Minorities in Engineering award.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Computer Science, Technology',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'AWS Girls Tech Program Scholarship',
                'description': '$3,000 scholarship for female high school students pursuing computer science or cloud computing. Supporting women in technology careers.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Cloud Computing, Technology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Science Olympiad Scholarship',
                'description': '$1,500 scholarship for high school Science Olympiad competitors pursuing STEM. For students who participated in state or national competitions.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Science, Engineering',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'First Robotics Scholarship',
                'description': '$2,000 scholarship for FIRST Robotics Competition participants pursuing engineering or computer science. For team members demonstrating leadership.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Robotics, Engineering, Computer Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Environmental Protection Agency STEM Scholarship',
                'description': '$4,000 scholarship for high school students pursuing environmental science or engineering. For students committed to environmental protection.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Environmental Engineering, Biology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'March 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Biomimicry Institute Youth Design Challenge Scholarship',
                'description': '$5,000 scholarship for high school students creating nature-inspired solutions. For students using biology to solve engineering challenges.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Biology, Environmental Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'NAACP ACT-SO STEM Award',
                'description': '$3,000 scholarship for African American high school students excelling in STEM competitions. Afro-Academic, Cultural, Technological and Scientific Olympics.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Science, Technology, Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Thurgood Marshall College Fund STEM Scholarship',
                'description': '$6,200 scholarship for students attending HBCUs pursuing STEM fields. Supporting students at historically black colleges and universities.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'General STEM, Engineering, Computer Science, Science',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Considered',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Siemens Foundation Scholarship',
                'description': '$2,500 scholarship for high school students pursuing engineering or computer science. Supporting future innovators in STEM fields.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Computer Science, Technology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'February 28',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'NCWIT Aspirations in Computing Award',
                'description': '$500-$10,000 scholarship for female high school students pursuing computing. National Center for Women & Information Technology award.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Information Technology, Software Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'November 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'ASM Materials Education Foundation Scholarship',
                'description': '$3,000 scholarship for high school seniors pursuing materials science or engineering. Supporting future materials scientists.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Materials Science, Engineering, Chemistry',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'AMS Weather Band Scholarship',
                'description': '$2,500 scholarship for high school seniors pursuing atmospheric science or meteorology. American Meteorological Society award.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Atmospheric Science, Meteorology, Environmental Science',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'February 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Stokes Educational Scholarship Program (NSA)',
                'description': '$30,000 scholarship for high school seniors pursuing computer science or cybersecurity. National Security Agency sponsored program.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Cybersecurity, Mathematics',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'November 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Barry Goldwater Scholarship',
                'description': '$7,500 scholarship for high school juniors/seniors pursuing research careers in STEM. Covers sophomore through senior years.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Science, Mathematics, Engineering',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'January 27',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Generation Google Scholarship - North America',
                'description': '$10,000 scholarship for underrepresented minorities and women pursuing computer science. Includes Google mentorship opportunities.',
                'url': 'https://bigfuture.collegeboard.org/scholarships',
                'source': 'College Board BigFuture',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Software Engineering, Technology',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'December 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            }
        ]

        return scholarships

    def scrape(self):
        """Main scraping method."""
        print("Starting College Board BigFuture High School STEM Scholarships scraping...")
        print("Note: Creating representative high school STEM scholarship data\n")

        # Try to fetch pages
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)

        # Create high school scholarships
        print("\nCreating high school STEM scholarship entries...")
        self.scholarships = self.create_high_school_stem_scholarships()

        print(f"\nTotal scholarships created: {len(self.scholarships)}")

    def save_to_csv(self, filename: str = 'data/collegeboard_bigfuture_stem.csv'):
        """Save scholarships to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]

        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.scholarships)

        print(f"\nSaved {len(self.scholarships)} scholarships to {filename}")


def main():
    scraper = CollegeBoardBigFutureScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("\nScraping completed successfully!")


if __name__ == "__main__":
    main()
