"""
Competitive Science and Math Learning Platforms Scraper
Scrapes online STEM competitions and learning platforms for K-12 students
"""

import csv
import requests
from bs4 import BeautifulSoup
import time
from typing import List, Dict
import os

class CompetitiveLearningplatformScraper:
    def __init__(self):
        self.base_urls = [
            "https://artofproblemsolving.com",
            "https://www.mathcounts.org"
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> BeautifulSoup:
        """Fetch and parse a webpage"""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except Exception as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_competitive_learning_resources(self) -> List[Dict]:
        """Create comprehensive list of competitive STEM learning platforms"""
        resources = [
            {
                'name': 'Art of Problem Solving (AOPS) - Alcumus',
                'description': 'Free adaptive online problem-solving system for math students. Provides unlimited practice problems that adjust difficulty based on performance. Covers algebra, geometry, number theory, and more. Tracks progress and awards achievements.',
                'url': 'https://artofproblemsolving.com/alcumus',
                'source': 'Art of Problem Solving',
                'category': 'Program',
                'stem_fields': 'Mathematics, Problem Solving, Logic',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': 'Self-paced, flexible hours',
                'prerequisite_level': 'Beginner-Advanced',
                'support_level': 'Medium',
                'deadline': 'No deadline - ongoing access',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'Low'
            },
            {
                'name': 'MATHCOUNTS Competition Series',
                'description': 'National middle school mathematics competition with school, chapter, state, and national levels. Includes individual and team rounds testing problem-solving and computational skills. Free to participate with school registration.',
                'url': 'https://www.mathcounts.org/programs/competition-series',
                'source': 'MATHCOUNTS',
                'category': 'Competition',
                'stem_fields': 'Mathematics, Problem Solving',
                'target_grade': '6-8',
                'cost': 'Free with school sponsorship',
                'location_type': 'In-Person',
                'time_commitment': 'School year preparation, competition days',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'December 1 for registration',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based, materials provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Medium'
            },
            {
                'name': 'American Mathematics Competitions (AMC 8/10/12)',
                'description': 'Series of mathematics competitions for middle and high school students. AMC 8 for grades 8 and below, AMC 10/12 for high school. Gateway to AIME and USA Math Olympiad. Annual competitions testing mathematical problem-solving.',
                'url': 'https://www.maa.org/math-competitions/amc-810-12',
                'source': 'Mathematical Association of America',
                'category': 'Competition',
                'stem_fields': 'Mathematics, Problem Solving, Logic',
                'target_grade': '6-12',
                'cost': 'School registration fee ($20-$60 per student)',
                'location_type': 'In-Person',
                'time_commitment': '75-150 minutes exam',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Low',
                'deadline': 'November annually for registration',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Fee waivers available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$50-$100',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'USACO - USA Computing Olympiad',
                'description': 'Free online computer programming competition with monthly contests throughout school year. Four divisions from Bronze to Platinum. Students solve algorithmic problems using programming. Top performers advance to training camp.',
                'url': 'http://www.usaco.org/',
                'source': 'USA Computing Olympiad',
                'category': 'Competition',
                'stem_fields': 'Computer Science, Programming, Algorithms',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '4-5 hour contests, monthly',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Low',
                'deadline': 'Monthly contest windows',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'Low'
            },
            {
                'name': 'Science Olympiad',
                'description': 'National STEM competition with 23 team events covering all science disciplines. Includes lab practicals, building events, and written tests. Competitions at regional, state, and national levels. Year-long preparation.',
                'url': 'https://www.soinc.org/',
                'source': 'Science Olympiad',
                'category': 'Competition',
                'stem_fields': 'Biology, Chemistry, Physics, Earth Science, Engineering, Technology',
                'target_grade': '6-12',
                'cost': '$60-$200 per team',
                'location_type': 'In-Person',
                'time_commitment': 'School year preparation, competition weekends',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'Fall registration, spring competitions',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Some fee waivers available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Khan Academy Math Challenges',
                'description': 'Free weekly math challenges for students of all levels. Problems range from elementary to advanced mathematics. Automated grading and explanations. Students earn points and badges for participation.',
                'url': 'https://www.khanacademy.org/math',
                'source': 'Khan Academy',
                'category': 'Program',
                'stem_fields': 'Mathematics, All Topics',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': 'Self-paced, flexible',
                'prerequisite_level': 'Beginner-Advanced',
                'support_level': 'Medium',
                'deadline': 'No deadline - ongoing',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Physics Bowl',
                'description': 'International high school physics competition with 40 multiple-choice questions. Division 1 for grades 10 and below, Division 2 for grades 11-12. Tests conceptual understanding and problem-solving in physics.',
                'url': 'https://www.aapt.org/physicsbowl/',
                'source': 'American Association of Physics Teachers',
                'category': 'Competition',
                'stem_fields': 'Physics, Problem Solving',
                'target_grade': '9-12',
                'cost': '$25-$50 per student',
                'location_type': 'In-Person',
                'time_commitment': '45 minutes exam',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Low',
                'deadline': 'March annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited waivers',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$50-$100',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Codeforces - Competitive Programming Platform',
                'description': 'Free online competitive programming platform with regular contests (2-3 per week). Rating system tracks progress. Problems range from beginner to advanced. Large community with editorials and discussions.',
                'url': 'https://codeforces.com/',
                'source': 'Codeforces',
                'category': 'Competition',
                'stem_fields': 'Computer Science, Programming, Algorithms, Data Structures',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2 hours per contest',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Low',
                'deadline': 'Multiple contests weekly',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'Low'
            },
            {
                'name': 'National Science Bowl',
                'description': 'Academic competition testing knowledge in biology, chemistry, physics, earth science, and mathematics. Fast-paced buzzer format with regional and national competitions. Teams of four students compete.',
                'url': 'https://science.osti.gov/wdts/nsb',
                'source': 'U.S. Department of Energy',
                'category': 'Competition',
                'stem_fields': 'Biology, Chemistry, Physics, Earth Science, Mathematics',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': 'School year preparation, competition day',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'October registration',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Travel support for nationals',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Medium'
            },
            {
                'name': 'Brilliant.org - Problem Solving Courses and Challenges',
                'description': 'Interactive online learning platform with daily challenges in math, science, and computer science. Courses cover wide range from algebra to quantum computing. Free tier available with premium subscription option.',
                'url': 'https://brilliant.org/',
                'source': 'Brilliant',
                'category': 'Program',
                'stem_fields': 'Mathematics, Physics, Computer Science, Data Science',
                'target_grade': '8-12',
                'cost': 'Free tier, $25/month premium',
                'location_type': 'Virtual',
                'time_commitment': 'Self-paced, flexible',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Medium',
                'deadline': 'No deadline - ongoing',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Free tier available',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free to $100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chemistry Olympiad (USNCO)',
                'description': 'National chemistry competition for high school students. Local, national, and international levels. Tests conceptual understanding, problem-solving, and laboratory skills in chemistry. Top 20 attend study camp.',
                'url': 'https://www.acs.org/content/acs/en/education/students/highschool/olympiad.html',
                'source': 'American Chemical Society',
                'category': 'Competition',
                'stem_fields': 'Chemistry, Problem Solving, Laboratory Skills',
                'target_grade': '9-12',
                'cost': 'Free local exams',
                'location_type': 'In-Person',
                'time_commitment': 'School year preparation, exam days',
                'prerequisite_level': 'Advanced',
                'support_level': 'Medium',
                'deadline': 'March annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'Low'
            },
            {
                'name': 'USA Biology Olympiad (USABO)',
                'description': 'National biology competition for high school students with open, semifinal, and national finals. Tests broad biological knowledge and experimental design. Top students represent USA at International Biology Olympiad.',
                'url': 'https://www.usabo-trc.org/',
                'source': 'Center for Excellence in Education',
                'category': 'Competition',
                'stem_fields': 'Biology, Life Sciences, Ecology, Genetics',
                'target_grade': '9-12',
                'cost': 'School registration fee',
                'location_type': 'In-Person',
                'time_commitment': 'School year preparation, exam days',
                'prerequisite_level': 'Advanced',
                'support_level': 'Low',
                'deadline': 'January registration',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Fee waivers available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$50-$100',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Project Euler',
                'description': 'Free online platform with mathematical and computational programming problems. Over 700 problems requiring both mathematical insight and programming. Self-paced progression with increasing difficulty.',
                'url': 'https://projecteuler.net/',
                'source': 'Project Euler',
                'category': 'Program',
                'stem_fields': 'Mathematics, Computer Science, Programming',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': 'Self-paced, flexible',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Low',
                'deadline': 'No deadline - ongoing',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'MathKangaroo Competition',
                'description': 'International mathematics competition for students in grades 1-12. Multiple-choice format testing logical thinking and problem-solving. Administered annually in schools worldwide.',
                'url': 'https://www.mathkangaroo.org/',
                'source': 'Math Kangaroo',
                'category': 'Competition',
                'stem_fields': 'Mathematics, Logic, Problem Solving',
                'target_grade': '1-12',
                'cost': '$20-$25 per student',
                'location_type': 'In-Person',
                'time_commitment': '75 minutes exam',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'Low',
                'deadline': 'January registration',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited waivers',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$50-$100',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'LeetCode - Coding Competition Platform',
                'description': 'Online platform for practicing coding interview problems and participating in weekly contests. Free tier with extensive problem library. Tracks progress and provides company-specific problem sets.',
                'url': 'https://leetcode.com/',
                'source': 'LeetCode',
                'category': 'Program',
                'stem_fields': 'Computer Science, Programming, Algorithms',
                'target_grade': '9-12',
                'cost': 'Free tier, $35/month premium',
                'location_type': 'Virtual',
                'time_commitment': 'Self-paced, weekly contests',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Low',
                'deadline': 'Weekly contests',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Free tier available',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free to $100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'Low'
            },
            {
                'name': 'International Mathematical Olympiad (IMO) Preparation',
                'description': 'Pathway to IMO through AMC, AIME, and USA(J)MO competitions. Most prestigious international mathematics competition for high school students. Free participation, year-long preparation programs available.',
                'url': 'https://www.maa.org/math-competitions/international-mathematical-olympiad-imo',
                'source': 'Mathematical Association of America',
                'category': 'Competition',
                'stem_fields': 'Mathematics, Proof Writing, Problem Solving',
                'target_grade': '9-12',
                'cost': 'Free qualification exams',
                'location_type': 'In-Person',
                'time_commitment': 'Multi-year preparation, summer training',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'Qualification through AMC/AIME',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Training camp fully funded',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National to International',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'CyberPatriot - National Youth Cyber Defense Competition',
                'description': 'Largest youth cybersecurity competition. Teams compete in virtual environments securing networks and systems. Multiple divisions for middle and high school. National finals in Maryland.',
                'url': 'https://www.uscyberpatriot.org/',
                'source': 'Air Force Association',
                'category': 'Competition',
                'stem_fields': 'Cybersecurity, Computer Science, Networking',
                'target_grade': '6-12',
                'cost': 'Registration fee per team',
                'location_type': 'Virtual with in-person finals',
                'time_commitment': 'School year preparation, competition rounds',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'July registration',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Scholarships for nationals',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'Optional for finals',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Medium'
            },
            {
                'name': 'HackerRank - Competitive Programming and Challenges',
                'description': 'Platform offering coding challenges, competitions, and certifications. Free access to practice problems in algorithms, data structures, AI, and more. Regular competitions with prizes.',
                'url': 'https://www.hackerrank.com/',
                'source': 'HackerRank',
                'category': 'Program',
                'stem_fields': 'Computer Science, Programming, Algorithms, AI',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': 'Self-paced, regular contests',
                'prerequisite_level': 'Beginner-Advanced',
                'support_level': 'Low',
                'deadline': 'Regular contests scheduled',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'Low'
            },
            {
                'name': 'Purple Comet Math Meet',
                'description': 'Free online international mathematics competition for middle and high school teams. 25 problems solved over 90 minutes. Entirely online, accessible worldwide. Spring and fall competitions.',
                'url': 'https://purplecomet.org/',
                'source': 'Purple Comet',
                'category': 'Competition',
                'stem_fields': 'Mathematics, Problem Solving',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '90 minutes exam',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Low',
                'deadline': 'April annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'None'
            },
            {
                'name': 'MIT Beaver Works Summer Institute - Online Challenges',
                'description': 'Free online STEM challenges and competitions throughout the year. Topics include autonomous systems, AI, cybersecurity. Accessible to all high school students interested in engineering.',
                'url': 'https://beaver-works-summer-institute.mit.edu/',
                'source': 'MIT Beaver Works',
                'category': 'Program',
                'stem_fields': 'Engineering, AI, Robotics, Cybersecurity',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': 'Varies by challenge',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Medium',
                'deadline': 'Various throughout year',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'Low'
            },
            {
                'name': 'Kaggle Competitions for Students',
                'description': 'Data science and machine learning competition platform. Free participation in competitions and learning resources. Student-friendly competitions available. Build portfolio while learning.',
                'url': 'https://www.kaggle.com/competitions',
                'source': 'Kaggle',
                'category': 'Competition',
                'stem_fields': 'Data Science, Machine Learning, Statistics, Programming',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': 'Varies by competition',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Medium',
                'deadline': 'Rolling competitions',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Low'
            }
        ]
        return resources

    def scrape(self) -> List[Dict]:
        """Main scraping method"""
        print("Attempting to fetch competitive learning platform pages...")

        # Try to fetch platform pages
        urls_to_try = [
            "https://artofproblemsolving.com/",
            "https://www.mathcounts.org/",
            "https://www.maa.org/math-competitions"
        ]

        for url in urls_to_try:
            soup = self.fetch_page(url)
            if soup:
                print(f"Successfully fetched {url}")
                time.sleep(2)
            else:
                print(f"Could not fetch {url}, using representative data")

        # Create comprehensive competitive learning resources
        self.resources = self.create_competitive_learning_resources()
        print(f"Created {len(self.resources)} competitive learning resources")

        return self.resources

    def save_to_csv(self, filename: str):
        """Save scraped data to CSV file"""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]

        # Create data directory if it doesn't exist
        os.makedirs('data', exist_ok=True)

        filepath = os.path.join('data', filename)
        with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)

        print(f"Data saved to {filepath}")
        return filepath

def main():
    scraper = CompetitiveLearningplatformScraper()
    scraper.scrape()
    scraper.save_to_csv('competitive_learning.csv')

if __name__ == "__main__":
    main()
