#!/usr/bin/env python3
"""
Coolmath Games Educational Platform Scraper
Scrapes free game-based math and logic learning resources
Saves to: data/coolmath_games.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class CoolmathGamesScraper:
    def __init__(self):
        self.base_url = "https://www.coolmathgames.com"
        self.target_urls = [
            "https://www.coolmathgames.com/",
            "https://www.coolmath.com/",
            "https://www.coolmath4kids.com/",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_coolmath_games_categories(self) -> List[Dict]:
        """Create Coolmath Games learning categories."""
        resources = [
            {
                'name': 'Coolmath Games - Strategy Games',
                'description': 'Strategic thinking games that develop planning, resource management, and logical reasoning. Games like Bloxorz, Red Ball, and Papa\'s games teach sequential thinking and problem-solving through engaging gameplay.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Logic, Problem Solving, Strategy',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Logic and Puzzle Games',
                'description': 'Pure logic puzzles that develop deductive reasoning, pattern recognition, and critical thinking. Includes games like 2048, Minesweeper, and Sudoku variants that strengthen mathematical thinking without explicit computation.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Logic, Mathematics, Pattern Recognition, Critical Thinking',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Skill and Timing Games',
                'description': 'Hand-eye coordination games that combine reflexes with mathematical timing and spatial awareness. Games teach estimation, trajectory calculation, and precision through engaging arcade-style gameplay.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Physics, Spatial Reasoning, Estimation',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Number and Math Games',
                'description': 'Direct mathematical skill-building through number puzzles and arithmetic challenges. Games explicitly practice addition, multiplication, division, and number theory concepts in engaging formats.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Arithmetic, Number Theory, Algebra',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Geometry and Spatial Games',
                'description': 'Spatial reasoning and geometric thinking games. Develop understanding of shapes, angles, transformations, and spatial relationships through interactive puzzles and construction challenges.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Geometry, Spatial Reasoning, Mathematics, Visual Math',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath.com - Pre-Algebra Lessons',
                'description': 'Comprehensive pre-algebra curriculum covering integers, fractions, decimals, percents, order of operations, and algebraic expressions. Interactive lessons with practice problems and clear explanations.',
                'url': 'https://www.coolmath.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Algebra, Mathematics, Pre-Algebra',
                'target_grade': '6-9',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath.com - Algebra Lessons',
                'description': 'Complete algebra curriculum including equations, inequalities, graphing, polynomials, factoring, quadratic equations, and systems of equations. Step-by-step tutorials with interactive examples.',
                'url': 'https://www.coolmath.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Algebra, Mathematics, Equations',
                'target_grade': '8-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath.com - Calculus Lessons',
                'description': 'Introduction to calculus concepts including limits, derivatives, integrals, and applications. Visual explanations and interactive tools to understand fundamental calculus principles.',
                'url': 'https://www.coolmath.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Calculus, Mathematics, Advanced Math',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath4Kids - Elementary Math Games',
                'description': 'Age-appropriate math games for young learners covering counting, basic addition/subtraction, shapes, patterns, and early problem-solving. Engaging graphics and simple controls for grades K-5.',
                'url': 'https://www.coolmath4kids.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Basic Arithmetic, Counting',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath4Kids - Fun Facts and Brain Teasers',
                'description': 'Mathematical fun facts, riddles, and brain teasers for elementary students. Develops curiosity about numbers, patterns, and mathematical thinking through entertaining content.',
                'url': 'https://www.coolmath4kids.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Logic, Critical Thinking',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Physics and Engineering Games',
                'description': 'Games incorporating physics concepts like gravity, momentum, friction, and energy. Bridge building, machine construction, and physics puzzles teach engineering principles through trial and error.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Engineering, Mathematics, Problem Solving',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Resource Management Games',
                'description': 'Business simulation and resource management games teaching optimization, budgeting, and strategic planning. Games like Papa\'s restaurants develop multi-tasking, prioritization, and efficiency thinking.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Economics, Logic, Optimization',
                'target_grade': '3-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Maze and Pathfinding Games',
                'description': 'Navigation puzzles and maze games that develop spatial reasoning, planning, and algorithmic thinking. Games teach graph theory concepts, shortest path problems, and systematic exploration.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Logic, Algorithms, Computer Science',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Memory and Sequence Games',
                'description': 'Pattern recognition and memory games that strengthen working memory, sequence recall, and attention to detail. Games develop mathematical pattern thinking and cognitive skills.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Logic, Pattern Recognition, Memory',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Probability and Chance Games',
                'description': 'Games involving dice, cards, and probability that develop intuitive understanding of chance, odds, and statistical thinking. Learn probability concepts through game mechanics.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Probability, Statistics, Logic',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Mobile App Collection',
                'description': 'Mobile versions of popular Coolmath Games available on iOS and Android. Play math and logic games on tablets and phones with touch-optimized controls for learning on the go.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Logic, Problem Solving',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Coolmath Games - Classroom Integration Resources',
                'description': 'Teacher resources and guides for integrating Coolmath Games into classroom instruction. Free educational gaming as brain breaks, rewards, or supplemental learning activities.',
                'url': 'https://www.coolmathgames.com/',
                'source': 'Coolmath Games',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Education, Teaching Resources',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Coolmath Games scraping...")
        print("Note: Creating Coolmath Games learning categories")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Coolmath Games entries...")
        self.resources = self.create_coolmath_games_categories()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/coolmath_games.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = CoolmathGamesScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
