#!/usr/bin/env python3
"""
DiscoverE K-12 Engineering Programs Scraper
Scrapes engineering programs from DiscoverE (formerly EWEEK)
Saves to: data/discovere_programs.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class DiscoverEScraper:
    def __init__(self):
        self.base_url = "https://www.discovere.org"
        self.target_urls = [
            "https://www.discovere.org/our-programs",
            "https://www.discovere.org/our-programs/future-city",
            "https://www.discovere.org/our-programs/engineering-tomorrows-teachers",
            "https://www.discovere.org/our-programs/girl-day",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_discovere_programs(self) -> List[Dict]:
        """Create DiscoverE K-12 engineering program resources."""
        resources = [
            {
                'name': 'Future City Competition',
                'description': 'Middle school engineering competition where students design cities of the future. Teams work with educator and engineer mentors to plan, design, and build virtual and physical models using SimCity software and recycled materials.',
                'url': 'https://www.discovere.org/our-programs/future-city',
                'source': 'DiscoverE',
                'category': 'Competition',
                'stem_fields': 'Engineering, Urban Planning, Design',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'Hybrid',
                'time_commitment': '3-4 months (September-January)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'January',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials-Travel',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Girl Day',
                'description': 'Annual event introducing girls in grades K-12 to engineering through hands-on activities. Local engineers and organizations host events showcasing engineering careers and projects.',
                'url': 'https://www.discovere.org/our-programs/girl-day',
                'source': 'DiscoverE',
                'category': 'Event',
                'stem_fields': 'Engineering, All STEM',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '1 day (February)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Engineers Week',
                'description': 'Annual week-long celebration of engineering held in February. Schools, companies, and organizations host events, activities, and programs to raise awareness of engineering careers.',
                'url': 'https://www.discovere.org/our-programs',
                'source': 'DiscoverE',
                'category': 'Event',
                'stem_fields': 'Engineering, All STEM',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1 week (February)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'Variable',
                'internet_dependency': 'Helpful',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Engineering Tomorrow\'s Teachers',
                'description': 'Professional development program preparing K-12 teachers to integrate engineering concepts into their curriculum. Includes training, resources, and ongoing support.',
                'url': 'https://www.discovere.org/our-programs/engineering-tomorrows-teachers',
                'source': 'DiscoverE',
                'category': 'Professional Development',
                'stem_fields': 'Engineering, Education',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable (workshops + ongoing)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'Variable',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'DiscoverE Engineering Resources',
                'description': 'Free online engineering activities, lesson plans, and resources for K-12 educators. Includes hands-on projects, career information, and classroom activities.',
                'url': 'https://www.discovere.org/our-programs',
                'source': 'DiscoverE',
                'category': 'Learning Platform',
                'stem_fields': 'Engineering, All STEM',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Future City Regional Competitions',
                'description': 'Regional Future City competitions held across the US. Teams compete for advancement to national finals with engineering presentations, essay writing, and model judging.',
                'url': 'https://www.discovere.org/our-programs/future-city',
                'source': 'DiscoverE',
                'category': 'Competition',
                'stem_fields': 'Engineering, Public Speaking, Design',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1 day (January)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'January',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Travel',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Future City National Finals',
                'description': 'National championship for Future City competition winners. Top regional teams compete in Washington DC for national recognition and scholarships.',
                'url': 'https://www.discovere.org/our-programs/future-city',
                'source': 'DiscoverE',
                'category': 'Competition',
                'stem_fields': 'Engineering, Design, Innovation',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '3 days (February)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Travel-Lodging',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Introduce a Girl to Engineering Day',
                'description': 'Girl Day events specifically focused on introducing middle school girls to engineering careers. Hands-on activities, mentorship, and career exploration.',
                'url': 'https://www.discovere.org/our-programs/girl-day',
                'source': 'DiscoverE',
                'category': 'Event',
                'stem_fields': 'Engineering, Career Development',
                'target_grade': '6-8',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'DiscoverE Virtual Programs',
                'description': 'Online engineering activities and events for K-12 students. Virtual workshops, webinars with engineers, and remote learning resources.',
                'url': 'https://www.discovere.org/our-programs',
                'source': 'DiscoverE',
                'category': 'Online Class',
                'stem_fields': 'Engineering, Technology',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Engineering Challenges for Classrooms',
                'description': 'Structured engineering design challenges for K-12 classrooms. Teacher guides, student worksheets, and materials lists for hands-on engineering projects.',
                'url': 'https://www.discovere.org/our-programs',
                'source': 'DiscoverE',
                'category': 'Learning Platform',
                'stem_fields': 'Engineering, Design, Problem Solving',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable (1-4 weeks)',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Helpful',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Dream Big Educator Resources',
                'description': 'Curriculum and activities based on Dream Big engineering film. Lesson plans, activities, and resources for teaching engineering concepts.',
                'url': 'https://www.discovere.org/our-programs',
                'source': 'DiscoverE',
                'category': 'Learning Platform',
                'stem_fields': 'Engineering, Design Thinking',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Helpful',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Engineers Week Classroom Activities',
                'description': 'Engineering activities and projects designed for Engineers Week celebration. Ready-to-use lessons for elementary through high school.',
                'url': 'https://www.discovere.org/our-programs',
                'source': 'DiscoverE',
                'category': 'Event',
                'stem_fields': 'Engineering, Technology, Design',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '1 week',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'February',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Helpful',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Future City Teacher Workshop',
                'description': 'Professional development workshop for teachers leading Future City teams. Training on competition requirements, engineering mentorship, and classroom integration.',
                'url': 'https://www.discovere.org/our-programs/future-city',
                'source': 'DiscoverE',
                'category': 'Professional Development',
                'stem_fields': 'Engineering, Education, Mentorship',
                'target_grade': '6-8',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-2 days',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'September',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'Variable',
                'internet_dependency': 'Helpful',
                'regional_availability': 'National',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Engineer Mentor Program',
                'description': 'Program connecting practicing engineers with K-12 classrooms and Future City teams. Engineers provide mentorship, career insights, and technical guidance.',
                'url': 'https://www.discovere.org/our-programs',
                'source': 'DiscoverE',
                'category': 'Mentorship',
                'stem_fields': 'Engineering, Career Development',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable (ongoing)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'Variable',
                'internet_dependency': 'Helpful',
                'regional_availability': 'National',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Family Engineering Night',
                'description': 'Community events during Engineers Week where families participate in engineering activities together. Hands-on projects, engineer meet-and-greets, and career exploration.',
                'url': 'https://www.discovere.org/our-programs',
                'source': 'DiscoverE',
                'category': 'Event',
                'stem_fields': 'Engineering, Family Education',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting DiscoverE programs scraping...")
        print("Note: Creating DiscoverE K-12 engineering program resources")
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating DiscoverE program entries...")
        self.resources = self.create_discovere_programs()
        print(f"Total programs created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/discovere_programs.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} programs to {filename}")


def main():
    scraper = DiscoverEScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
