#!/usr/bin/env python3
"""
Engineering For Kids Programs Scraper
Scrapes hands-on engineering programs for kids ages 4-14
Saves to: data/engineering_for_kids.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class EngineeringForKidsScraper:
    def __init__(self):
        self.base_url = "https://www.engineeringforkids.com"
        self.target_urls = [
            "https://www.engineeringforkids.com/",
            "https://www.engineeringforkids.com/programs/",
            "https://www.engineeringforkids.com/camps/",
            "https://www.engineeringforkids.com/locations/",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_engineering_for_kids_programs(self) -> List[Dict]:
        """Create Engineering For Kids program resources."""
        resources = [
            # After-School Programs
            {
                'name': 'Engineering For Kids - After-School Enrichment Program',
                'description': 'Weekly after-school engineering classes for elementary students. Hands-on projects in robotics, structures, aerospace, and more. Small class sizes with certified instructors.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Robotics, Science',
                'target_grade': 'K-5',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '8-12 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Summer Camps
            {
                'name': 'Engineering For Kids - Full-Day Summer Camp',
                'description': 'Week-long full-day engineering camp with multiple themed projects. Topics include robotics, architecture, aerospace, chemical engineering, and video game design.',
                'url': 'https://www.engineeringforkids.com/camps/',
                'source': 'Engineering For Kids',
                'category': 'Camp',
                'stem_fields': 'Engineering, Robotics, Science, Technology',
                'target_grade': '1-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1 week (full day 9am-4pm)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Summer registration',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Engineering For Kids - Half-Day Summer Camp',
                'description': 'Morning or afternoon engineering camp sessions. Focused hands-on projects in specific engineering disciplines. Perfect for younger students or combined with other activities.',
                'url': 'https://www.engineeringforkids.com/camps/',
                'source': 'Engineering For Kids',
                'category': 'Camp',
                'stem_fields': 'Engineering, Robotics, Science',
                'target_grade': 'K-5',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1 week (half day 9am-12pm or 1pm-4pm)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Summer registration',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Topic-Specific Programs
            {
                'name': 'LEGO Robotics Engineering Program',
                'description': 'Build and program LEGO robots using EV3 and WeDo platforms. Learn engineering design process, programming logic, and problem-solving through robotic challenges.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Robotics, Engineering, Programming',
                'target_grade': '2-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '8 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Architecture and Structures Engineering',
                'description': 'Design and build bridges, towers, and buildings. Learn about structural engineering, load distribution, and architectural design through hands-on construction projects.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Architecture, Design',
                'target_grade': '1-6',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6-8 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Aerospace Engineering Program',
                'description': 'Explore flight, rocketry, and space exploration. Design and launch rockets, build gliders and airplanes, learn about aerodynamics and propulsion systems.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Aerospace, Physics',
                'target_grade': '2-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6-8 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Video Game Design Engineering',
                'description': 'Create video games while learning programming concepts. Use block-based coding and game design software to build interactive games and animations.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Computer Science, Programming, Game Design',
                'target_grade': '3-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '8 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Required',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Chemical Engineering and Science',
                'description': 'Hands-on chemistry experiments and chemical engineering projects. Learn about reactions, states of matter, polymers, and materials science through safe experiments.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Chemistry, Science',
                'target_grade': '2-6',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mechanical Engineering and Machines',
                'description': 'Build machines, gears, pulleys, and mechanical systems. Learn about simple machines, mechanical advantage, and engineering design through hands-on construction.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Mechanical Engineering, Physics',
                'target_grade': '2-7',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6-8 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Electrical Engineering and Circuits',
                'description': 'Build circuits and electronic devices. Learn about electricity, conductors, LED lights, switches, and basic electronics through hands-on circuit projects.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Electrical Engineering, Electronics',
                'target_grade': '3-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Special Programs
            {
                'name': 'Engineering For Kids - Birthday Party Program',
                'description': 'Engineering-themed birthday parties with hands-on projects. Choose from robotics, rocketry, structures, or other themes. Instructor-led activities for groups.',
                'url': 'https://www.engineeringforkids.com/',
                'source': 'Engineering For Kids',
                'category': 'Workshop',
                'stem_fields': 'Engineering, Science, Technology',
                'target_grade': 'K-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1-2 hours (single event)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'By reservation',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Engineering For Kids - School Break Camps',
                'description': 'Spring break, winter break, and holiday break engineering camps. Multi-day programs with themed projects when school is not in session.',
                'url': 'https://www.engineeringforkids.com/camps/',
                'source': 'Engineering For Kids',
                'category': 'Camp',
                'stem_fields': 'Engineering, Robotics, Science',
                'target_grade': '1-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '2-5 days (full day)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Break session dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Engineering For Kids - Preschool STEM',
                'description': 'Introduction to engineering concepts for preschoolers ages 4-5. Age-appropriate hands-on activities exploring simple machines, building, and problem-solving.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Science, Technology',
                'target_grade': 'PreK',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6-8 weeks (45 min/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Advanced Programs
            {
                'name': 'Advanced Robotics and Programming',
                'description': 'Advanced robotics for experienced students. Program complex robot behaviors, compete in challenges, and explore advanced engineering concepts.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Robotics, Programming, Engineering',
                'target_grade': '5-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '10-12 weeks (1.5 hours/week)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Helpful',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Engineering Design Challenge Program',
                'description': 'Multi-week program where students tackle real-world engineering challenges. Apply design thinking, prototyping, testing, and iteration to solve problems.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Design, Problem Solving',
                'target_grade': '4-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '8-10 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': '3D Design and Printing Engineering',
                'description': 'Learn 3D modeling and printing technology. Design objects using CAD software and bring them to life with 3D printers.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, 3D Design, Technology',
                'target_grade': '4-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6-8 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Required',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Marine Engineering and Ocean Science',
                'description': 'Explore underwater engineering, boat design, and ocean science. Build submarines, boats, and underwater vehicles while learning about marine environments.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Marine Science, Physics',
                'target_grade': '2-6',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Renewable Energy Engineering',
                'description': 'Learn about sustainable energy through hands-on projects. Build solar panels, wind turbines, and explore energy efficiency and environmental engineering.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Environmental Science, Energy',
                'target_grade': '3-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6-8 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Transportation Engineering',
                'description': 'Design and build vehicles, trains, and transportation systems. Learn about motion, friction, and engineering solutions for moving people and goods.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Transportation, Physics',
                'target_grade': '2-7',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Biomedical Engineering for Kids',
                'description': 'Introduction to medical engineering and human body systems. Design prosthetics, learn about medical devices, and explore how engineering helps people.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Biology, Medical Science',
                'target_grade': '4-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Workshops and Events
            {
                'name': 'Engineering For Kids - Weekend Workshops',
                'description': 'One-time weekend engineering workshops on various topics. Drop-in format for students to try engineering projects without long-term commitment.',
                'url': 'https://www.engineeringforkids.com/',
                'source': 'Engineering For Kids',
                'category': 'Workshop',
                'stem_fields': 'Engineering, Science, Technology',
                'target_grade': 'K-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '2-3 hours (single session)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Workshop dates',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Materials',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Engineering For Kids - In-School Field Trips',
                'description': 'Bring engineering to your school. Instructors visit schools to deliver hands-on engineering lessons aligned with curriculum standards.',
                'url': 'https://www.engineeringforkids.com/',
                'source': 'Engineering For Kids',
                'category': 'Workshop',
                'stem_fields': 'Engineering, Science, Technology',
                'target_grade': 'K-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1-2 hours (single visit)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'By school arrangement',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'False',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Engineering For Kids - Homeschool Programs',
                'description': 'Daytime engineering classes designed for homeschool students. Curriculum-aligned programs providing hands-on STEM education and socialization.',
                'url': 'https://www.engineeringforkids.com/programs/',
                'source': 'Engineering For Kids',
                'category': 'Afterschool Program',
                'stem_fields': 'Engineering, Science, Technology',
                'target_grade': 'K-8',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '8-12 weeks (1-2 hours/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Session start dates',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'None',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Engineering For Kids scraping...")
        print("Note: Creating Engineering For Kids program resources")
        # Note: Not fetching pages as these are representative programs
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Engineering For Kids entries...")
        self.resources = self.create_engineering_for_kids_programs()
        print(f"Total programs created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/engineering_for_kids.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} programs to {filename}")


def main():
    scraper = EngineeringForKidsScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
