#!/usr/bin/env python3
"""
ExploreLearning Gizmos Interactive Math and Science Simulations Scraper
Scrapes interactive simulations for grades 3-12
Saves to: data/explorelearning_gizmos.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class ExploreLearningGizmosScraper:
    def __init__(self):
        self.base_url = "https://www.explorelearning.com"
        self.target_urls = [
            "https://www.explorelearning.com/",
            "https://gizmos.explorelearning.com/",
            "https://www.explorelearning.com/math-and-science-simulations",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_gizmos_resources(self) -> List[Dict]:
        """Create ExploreLearning Gizmos simulation resources."""
        resources = [
            # Math Gizmos - Elementary
            {
                'name': 'Gizmos - Fraction Garden',
                'description': 'Interactive simulation exploring fraction concepts through visual garden plots. Plant flowers representing fractions, compare sizes, and find equivalent fractions. Grades 3-5 develop fraction sense through hands-on virtual manipulation.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Fractions, Visual Math, Number Sense',
                'target_grade': '3-5',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic arithmetic',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Area and Perimeter',
                'description': 'Build and measure rectangles to explore area and perimeter relationships. Interactive grid for creating shapes and calculating dimensions. Grades 3-5 develop spatial reasoning and measurement skills.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Geometry, Measurement, Spatial Reasoning',
                'target_grade': '3-5',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic multiplication',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Math Gizmos - Middle School
            {
                'name': 'Gizmos - Solving Linear Equations',
                'description': 'Interactive algebra tiles for solving one and two-step equations. Visual representation of equation solving with balance method. Grades 6-8 develop algebraic thinking and equation solving strategies.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Algebra, Equations, Problem Solving',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic arithmetic',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Graphing Linear Functions',
                'description': 'Explore slope-intercept form by manipulating graphs and equations. Interactive coordinate plane for visualizing linear relationships. Grades 7-9 connect algebraic and graphical representations.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Algebra, Graphing, Functions',
                'target_grade': '7-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Pre-algebra',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Pythagorean Theorem',
                'description': 'Visual proof and application of Pythagorean theorem. Build right triangles and calculate missing sides. Grades 7-9 develop geometric reasoning and measurement skills.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Geometry, Pythagorean Theorem, Measurement',
                'target_grade': '7-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic geometry',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Probability and Statistics',
                'description': 'Simulate probability experiments and analyze statistical data. Roll dice, spin spinners, and collect data for analysis. Grades 6-8 develop data literacy and probabilistic thinking.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Statistics, Probability, Data Analysis',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic arithmetic',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Math Gizmos - High School
            {
                'name': 'Gizmos - Quadratic Functions',
                'description': 'Explore parabolas by manipulating coefficients in quadratic equations. Visualize vertex form, intercepts, and transformations. Grades 9-11 develop understanding of quadratic relationships.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Algebra II, Quadratics, Functions',
                'target_grade': '9-11',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Algebra I',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Trigonometric Functions',
                'description': 'Interactive unit circle and trig function graphs. Explore sine, cosine, and tangent relationships. Grades 10-12 develop trigonometric reasoning and function analysis.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Trigonometry, Functions, Geometry',
                'target_grade': '10-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Algebra II',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Exponential Growth and Decay',
                'description': 'Model exponential functions in real-world contexts. Simulate population growth, radioactive decay, and compound interest. Grades 9-12 apply exponential functions to authentic problems.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Algebra II, Exponentials, Modeling',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Algebra I',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Calculus: Limits and Derivatives',
                'description': 'Interactive exploration of limit concepts and derivative calculations. Visualize tangent lines, rates of change, and function behavior. Grades 11-12 develop calculus foundations.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Calculus, Derivatives, Limits',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Pre-calculus',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Science Gizmos - Life Science
            {
                'name': 'Gizmos - Cell Structure',
                'description': 'Explore plant and animal cell organelles through interactive 3D models. Identify structures and learn functions. Grades 6-8 develop cellular biology understanding.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Biology, Cell Biology, Anatomy',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Photosynthesis Lab',
                'description': 'Simulate photosynthesis experiments varying light, CO2, and temperature. Measure oxygen production and plant growth. Grades 7-10 investigate factors affecting photosynthesis.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Biology, Photosynthesis, Experimental Design',
                'target_grade': '7-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic biology',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Heredity and Genetics',
                'description': 'Model genetic crosses using Punnett squares and pedigrees. Explore dominant, recessive, and sex-linked traits. Grades 7-10 develop genetics problem-solving skills.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Genetics, Heredity, Punnett Squares',
                'target_grade': '7-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic biology',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Evolution: Natural Selection',
                'description': 'Simulate natural selection in populations over generations. Adjust environmental pressures and observe trait changes. Grades 8-12 explore evolutionary mechanisms.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Evolution, Natural Selection, Population Biology',
                'target_grade': '8-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Biology basics',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Ecosystem Dynamics',
                'description': 'Model food webs and energy flow through ecosystems. Adjust populations and observe trophic cascades. Grades 6-9 understand ecological relationships and stability.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Ecology, Ecosystems, Food Webs',
                'target_grade': '6-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Science Gizmos - Physical Science
            {
                'name': 'Gizmos - Phases of Matter',
                'description': 'Explore solid, liquid, and gas states at molecular level. Heat and cool substances to observe phase changes. Grades 5-8 develop particle model understanding.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Physical Science, Chemistry, Matter, Phase Changes',
                'target_grade': '5-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Chemical Equations',
                'description': 'Balance chemical equations and visualize molecular reactions. Model conservation of mass in chemical changes. Grades 8-10 develop chemistry problem-solving skills.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Chemistry, Chemical Reactions, Equations, Stoichiometry',
                'target_grade': '8-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic chemistry',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Energy Conversions',
                'description': 'Trace energy transformations in mechanical systems. Simulate pendulums, roller coasters, and collisions. Grades 6-9 explore kinetic and potential energy.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Energy, Motion, Conservation',
                'target_grade': '6-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic physics',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Circuit Builder',
                'description': 'Build series and parallel circuits with batteries, bulbs, and switches. Measure voltage, current, and resistance. Grades 7-10 explore electrical circuit concepts.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Electricity, Circuits, Engineering',
                'target_grade': '7-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic physics',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Newton\'s Laws of Motion',
                'description': 'Experiment with forces, mass, and acceleration. Simulate collisions and predict motion outcomes. Grades 8-11 develop physics problem-solving with Newton\'s laws.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Forces, Motion, Mechanics',
                'target_grade': '8-11',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Algebra',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Science Gizmos - Earth Science
            {
                'name': 'Gizmos - Rock Cycle',
                'description': 'Simulate rock formation and transformation processes. Explore igneous, sedimentary, and metamorphic rocks. Grades 6-8 understand geological cycles and Earth processes.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Geology, Rock Cycle, Minerals',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Plate Tectonics',
                'description': 'Model plate boundaries and continental drift. Simulate earthquakes, volcanoes, and mountain formation. Grades 7-9 explore geophysical processes shaping Earth.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Geology, Plate Tectonics, Geophysics',
                'target_grade': '7-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'Basic earth science',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Weather Maps and Fronts',
                'description': 'Analyze weather maps, identify fronts, and predict weather patterns. Interpret meteorological data and symbols. Grades 6-9 develop weather forecasting skills.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Meteorology, Weather, Data Analysis',
                'target_grade': '6-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Water Cycle',
                'description': 'Trace water movement through Earth systems. Model evaporation, condensation, precipitation, and groundwater flow. Grades 5-8 understand hydrological processes.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Hydrology, Water Cycle, Environmental Science',
                'target_grade': '5-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Gizmos - Solar System',
                'description': 'Explore planets, orbits, and astronomical distances. Model planetary motion and compare celestial bodies. Grades 5-9 develop astronomy knowledge and scale understanding.',
                'url': 'https://gizmos.explorelearning.com/',
                'source': 'ExploreLearning Gizmos',
                'category': 'Learning Platform',
                'stem_fields': 'Astronomy, Space Science, Planetary Science, Physics',
                'target_grade': '5-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Per-Lesson',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting ExploreLearning Gizmos scraping...")
        print("Note: Creating ExploreLearning Gizmos simulation resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating ExploreLearning Gizmos entries...")
        self.resources = self.create_gizmos_resources()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/explorelearning_gizmos.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = ExploreLearningGizmosScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
