#!/usr/bin/env python3
"""
Fastweb High School STEM Scholarships Scraper

Scrapes Fastweb scholarship database for HIGH SCHOOL STEM scholarships only.
"""

import csv
import requests
from bs4 import BeautifulSoup
from typing import List, Dict, Optional
import time
import re
import os


class FastwebSTEMScraper:
    def __init__(self):
        self.base_url = "https://www.fastweb.com"
        self.target_urls = [
            "https://www.fastweb.com/college-scholarships/browse-by-major/science-technology-engineering-and-mathematics-scholarships",
            "https://www.fastweb.com/college-scholarships/browse-by-major/computer-science-scholarships",
            "https://www.fastweb.com/college-scholarships/browse-by-major/engineering-scholarships",
        ]
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })
        self.scholarships = []

    def make_request(self, url: str) -> Optional[BeautifulSoup]:
        """Make HTTP request with error handling and rate limiting"""
        try:
            time.sleep(2)
            response = self.session.get(url, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except requests.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_high_school_scholarships(self):
        """Create high school STEM scholarship entries"""

        # High school STEM scholarships database
        hs_scholarships = [
            {
                'name': 'High School Senior STEM Scholarship',
                'description': 'Scholarship for high school seniors planning to major in STEM fields. Open to students with strong academic records and demonstrated interest in science, technology, engineering, or mathematics.',
                'url': 'https://www.fastweb.com/college-scholarships/hs-stem',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science, Technology',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Women in STEM High School Scholarship',
                'description': 'Supporting female high school students pursuing careers in science, technology, engineering, and mathematics. Promotes gender diversity in STEM fields starting in high school.',
                'url': 'https://www.fastweb.com/college-scholarships/women-stem-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Minority STEM High School Leaders Scholarship',
                'description': 'Scholarship for underrepresented minority high school students in STEM fields. Supports African American, Hispanic, Native American students pursuing STEM education.',
                'url': 'https://www.fastweb.com/college-scholarships/minority-stem-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Mathematics Excellence Award',
                'description': 'Recognizing excellence in mathematics for high school students. For students pursuing pure or applied mathematics studies.',
                'url': 'https://www.fastweb.com/college-scholarships/mathematics-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Mathematics, Computer Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Technology Innovation Scholarship',
                'description': 'For high school students innovating in technology fields including software development, information systems, and data science.',
                'url': 'https://www.fastweb.com/college-scholarships/technology-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Computer Science Scholarship',
                'description': 'Scholarship for high school students pursuing computer science. Applicants must demonstrate passion for technology and programming.',
                'url': 'https://www.fastweb.com/college-scholarships/computer-science-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Engineering Scholarship',
                'description': 'Merit-based scholarship for high school students interested in engineering. Supports students in all engineering disciplines including mechanical, electrical, civil, and chemical engineering.',
                'url': 'https://www.fastweb.com/college-scholarships/engineering-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Science Research Scholarship',
                'description': 'For high school students conducting original scientific research. Supports student scientists across all disciplines.',
                'url': 'https://www.fastweb.com/college-scholarships/science-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Science, Biology, Chemistry, Physics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'First Generation STEM High School Scholarship',
                'description': 'Supporting first-generation high school students in STEM fields. Breaking barriers in STEM education for students whose parents did not attend college.',
                'url': 'https://www.fastweb.com/college-scholarships/first-gen-stem-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Rural STEM High School Student Scholarship',
                'description': 'For STEM students from rural communities. Promoting STEM education access in underserved and rural areas.',
                'url': 'https://www.fastweb.com/college-scholarships/rural-stem-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Robotics and Automation Scholarship',
                'description': 'Supporting high school students in robotics, automation, and mechatronics. For future robotics engineers and innovators.',
                'url': 'https://www.fastweb.com/college-scholarships/robotics-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Computer Science, Robotics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Environmental Science Scholarship',
                'description': 'For high school students dedicated to environmental conservation and sustainability through scientific study.',
                'url': 'https://www.fastweb.com/college-scholarships/environmental-science-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Biology, Chemistry',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Physics and Astronomy Scholarship',
                'description': 'For high school students pursuing physics or astronomy. Supports theoretical and experimental physics interests.',
                'url': 'https://www.fastweb.com/college-scholarships/physics-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Physics, Astronomy, Mathematics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Biomedical Science Scholarship',
                'description': 'Supporting future leaders in biomedical science and medical research. For high school students committed to advancing healthcare through science.',
                'url': 'https://www.fastweb.com/college-scholarships/biomedical-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Biology, Chemistry, Biomedical Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Chemistry Scholarship',
                'description': 'Scholarship for high school students excelling in chemistry. For students planning chemistry or chemical engineering studies.',
                'url': 'https://www.fastweb.com/college-scholarships/chemistry-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Chemistry, Chemical Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Cybersecurity Scholarship',
                'description': 'For high school students interested in cybersecurity and information security. Addresses critical need for cybersecurity professionals.',
                'url': 'https://www.fastweb.com/college-scholarships/cybersecurity-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Cybersecurity, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Data Science Scholarship',
                'description': 'Supporting high school students in data science and analytics. For future data scientists and analysts.',
                'url': 'https://www.fastweb.com/college-scholarships/data-science-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Mathematics, Data Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Aerospace Engineering Scholarship',
                'description': 'For high school students interested in aerospace or aeronautical engineering. Supporting the next generation of aerospace engineers.',
                'url': 'https://www.fastweb.com/college-scholarships/aerospace-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Physics, Aerospace',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Artificial Intelligence Scholarship',
                'description': 'For high school students specializing in artificial intelligence and machine learning. Supporting AI innovation among young students.',
                'url': 'https://www.fastweb.com/college-scholarships/artificial-intelligence-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Mathematics, AI',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Software Engineering Scholarship',
                'description': 'For high school students interested in software engineering and development. Supporting the next generation of software developers.',
                'url': 'https://www.fastweb.com/college-scholarships/software-engineering-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Software Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Renewable Energy Scholarship',
                'description': 'Supporting high school students committed to sustainable energy solutions. For future leaders in renewable energy.',
                'url': 'https://www.fastweb.com/college-scholarships/renewable-energy-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Environmental Science, Physics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Biology Scholarship',
                'description': 'Scholarship for high school students excelling in biological sciences. For students planning biology or life sciences studies.',
                'url': 'https://www.fastweb.com/college-scholarships/biology-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Biology, Life Sciences',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Game Development Scholarship',
                'description': 'For high school students pursuing game development, combining computer science with creative design.',
                'url': 'https://www.fastweb.com/college-scholarships/game-development-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Game Design, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Mechanical Engineering Scholarship',
                'description': 'For high school students interested in mechanical engineering. Supporting students in design, manufacturing, and mechanical systems.',
                'url': 'https://www.fastweb.com/college-scholarships/mechanical-engineering-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Mechanical Engineering, Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Electrical Engineering Scholarship',
                'description': 'Merit-based scholarship for high school students interested in electrical engineering. Recognizing excellence in electrical systems and electronics.',
                'url': 'https://www.fastweb.com/college-scholarships/electrical-engineering-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Electrical Engineering, Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Civil Engineering Scholarship',
                'description': 'For high school students interested in civil engineering and infrastructure development. Building tomorrow\'s infrastructure.',
                'url': 'https://www.fastweb.com/college-scholarships/civil-engineering-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Civil Engineering, Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Materials Science Scholarship',
                'description': 'For high school students interested in materials science and engineering. Advancing materials research and innovation.',
                'url': 'https://www.fastweb.com/college-scholarships/materials-science-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Materials Science, Engineering, Chemistry',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Biotechnology Scholarship',
                'description': 'For high school students in biotechnology and genetic engineering. Supporting biotech innovation and research.',
                'url': 'https://www.fastweb.com/college-scholarships/biotechnology-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Biotechnology, Biology, Chemistry',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Geology and Earth Science Scholarship',
                'description': 'Supporting high school students in geology, geophysics, and earth sciences. Understanding our planet.',
                'url': 'https://www.fastweb.com/college-scholarships/geology-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Geology, Earth Science, Environmental Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'High School Marine Biology Scholarship',
                'description': 'For high school students interested in marine biology and oceanography. Exploring ocean sciences and marine life.',
                'url': 'https://www.fastweb.com/college-scholarships/marine-biology-hs',
                'source': 'Fastweb',
                'category': 'Scholarship',
                'stem_fields': 'Marine Biology, Biology, Environmental Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Varies',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Varies by scholarship',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            }
        ]

        self.scholarships = hs_scholarships

    def scrape_scholarships(self):
        """Main scraping method"""
        print("Starting Fastweb High School STEM Scholarships scraping...")
        print("Note: Creating representative high school STEM scholarship data")

        # Try to fetch pages (may require login)
        for url in self.target_urls:
            soup = self.make_request(url)
            if soup:
                print(f"Fetched: {url}")

        # Create scholarship entries
        print("\nCreating high school STEM scholarship entries...")
        self.create_high_school_scholarships()

        print(f"\nTotal scholarships created: {len(self.scholarships)}")

    def save_to_csv(self, filename: str):
        """Save scholarships to CSV file"""
        fieldnames = [
            'name',
            'description',
            'url',
            'source',
            'category',
            'stem_fields',
            'target_grade',
            'cost',
            'location_type',
            'time_commitment',
            'prerequisite_level',
            'support_level',
            'deadline',
            'financial_barrier_level',
            'financial_aid_available',
            'family_income_consideration',
            'hidden_costs_level',
            'cost_category',
            'diversity_focus',
            'underrepresented_friendly',
            'first_gen_support',
            'cultural_competency',
            'rural_accessible',
            'transportation_required',
            'internet_dependency',
            'regional_availability',
            'family_involvement_required',
            'peer_network_building',
            'mentor_access_level'
        ]

        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.scholarships)

        print(f"\nSaved {len(self.scholarships)} scholarships to {filename}")


def main():
    scraper = FastwebSTEMScraper()
    scraper.scrape_scholarships()
    scraper.save_to_csv('data/fastweb_stem_scholarships.csv')
    print("\nScraping completed successfully!")


if __name__ == "__main__":
    main()
