#!/usr/bin/env python3
"""
Hopscotch Visual Coding App Scraper
Scrapes block-based programming platform for ages 9-14
Saves to: data/hopscotch_coding.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class HopscotchCodingScraper:
    def __init__(self):
        self.base_url = "https://www.gethopscotch.com"
        self.target_urls = [
            "https://www.gethopscotch.com/",
            "https://www.gethopscotch.com/explore",
            "https://www.gethopscotch.com/educators",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_hopscotch_resources(self) -> List[Dict]:
        """Create Hopscotch coding tutorial and project resources."""
        resources = [
            {
                'name': 'Hopscotch - Getting Started Tutorial',
                'description': 'Introduction to block-based coding on iPad. Learn drag-and-drop programming interface, basic commands, and creating first interactive project. Ages 9-14 develop foundational coding skills through guided tutorial.',
                'url': 'https://www.gethopscotch.com/',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Computational Thinking, Logic',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Game Creation Projects',
                'description': 'Build interactive games using visual programming blocks. Create platformers, racing games, and puzzles. Learn game mechanics, collision detection, scoring systems, and player controls. Ages 9-14 develop game design skills.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Game Design, Programming, Creativity',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Animation Studio',
                'description': 'Create animated stories and interactive art. Program character movements, scene transitions, and visual effects using code blocks. Ages 9-14 combine storytelling with programming to create animated narratives.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Animation, Art, Storytelling',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Interactive Art Projects',
                'description': 'Code generative art and interactive designs. Use loops, variables, and drawing commands to create mathematical art, patterns, and responsive visuals. Ages 9-14 explore intersection of art and computer science.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Generative Art, Mathematics, Design',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Music and Sound Programming',
                'description': 'Create musical compositions and sound effects using code. Program beats, melodies, and interactive instruments. Ages 9-14 learn sequencing, timing, and audio programming through musical projects.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Music, Audio Programming, Sequencing',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Variables and Math Projects',
                'description': 'Learn programming variables through math games and calculators. Build counting apps, math quizzes, and interactive calculators. Ages 9-14 connect mathematical concepts with coding logic.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Mathematics, Variables, Logic',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Loops and Patterns',
                'description': 'Master loop programming through pattern creation and repetitive tasks. Build spirals, tessellations, and automated behaviors. Ages 9-14 develop computational efficiency and algorithmic thinking.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Algorithms, Loops, Patterns',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Conditionals and Logic',
                'description': 'Learn if-then logic and conditional statements. Create decision-making programs, quizzes, and interactive stories with branching paths. Ages 9-14 develop logical reasoning and conditional thinking.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Logic, Conditionals, Decision Making',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Basic coding',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Physics Simulations',
                'description': 'Code physics-based games and simulations. Implement gravity, velocity, acceleration, and collision physics. Ages 9-14 apply physics concepts through game programming.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Physics, Game Physics, Simulation',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Basic coding',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Character Design and Sprites',
                'description': 'Create custom characters and sprites using built-in drawing tools. Program character behaviors, animations, and interactions. Ages 9-14 combine art and coding to build unique game assets.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Digital Art, Character Design, Animation',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Community Explore Page',
                'description': 'Browse, play, and remix projects from global community. Discover trending games, featured projects, and learning from peer code. Ages 9-14 engage with collaborative learning and code remixing.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Peer Learning, Code Reading, Collaboration',
                'target_grade': '4-8',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Publishing and Sharing',
                'description': 'Publish projects to community for others to play and remix. Receive feedback, track plays, and build portfolio. Ages 9-14 develop confidence sharing work and receiving constructive feedback.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Digital Citizenship, Portfolio Building, Communication',
                'target_grade': '4-8',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Basic coding',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Code Remixing',
                'description': 'Learn by remixing existing projects. View code from community projects, modify logic, and create variations. Ages 9-14 develop code reading skills and learn from examples.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Code Reading, Reverse Engineering, Adaptation',
                'target_grade': '4-8',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Educator Dashboard',
                'description': 'Free classroom management tools for teachers. Create class codes, monitor student progress, view projects, and access curriculum-aligned lesson plans. Support K-8 computer science education.',
                'url': 'https://www.gethopscotch.com/educators',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science Education, Classroom Management, Curriculum',
                'target_grade': '4-8',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Hopscotch - Classroom Lesson Plans',
                'description': 'Free downloadable lesson plans aligned to CSTA standards. Step-by-step coding activities, project rubrics, and assessment tools. Support educators teaching grades 4-8 computer science.',
                'url': 'https://www.gethopscotch.com/educators',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science Education, Curriculum, Standards-Aligned',
                'target_grade': '4-8',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Hopscotch - Video Tutorials',
                'description': 'Library of step-by-step video tutorials covering coding concepts. Learn loops, variables, conditionals, and game design through guided videos. Ages 9-14 follow along to build projects.',
                'url': 'https://www.gethopscotch.com/',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Video Learning, Tutorials',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Hopscotch - Premium Subscription',
                'description': 'Optional subscription unlocking advanced features including expanded character library, special effects, cloud saves, and ad-free experience. Ages 9-14 access enhanced creative tools.',
                'url': 'https://www.gethopscotch.com/',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Premium Features',
                'target_grade': '4-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$50-$100',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - iPad App Interface',
                'description': 'Touch-optimized coding on iPad. Drag-and-drop blocks, real-time preview, and intuitive interface designed for mobile. Ages 9-14 code anywhere with tablet-friendly design.',
                'url': 'https://www.gethopscotch.com/',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Mobile Learning, User Interface Design',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Mobile App',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Weekly Challenges',
                'description': 'Community coding challenges with themes and prompts. Participate in weekly projects, showcase creativity, and get featured. Ages 9-14 stay engaged with fresh content and friendly competition.',
                'url': 'https://www.gethopscotch.com/explore',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Creative Problem Solving, Community Engagement',
                'target_grade': '4-8',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Weekly',
                'prerequisite_level': 'Basic coding',
                'support_level': 'Low',
                'deadline': 'Weekly',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            {
                'name': 'Hopscotch - Safe Community Moderation',
                'description': 'Kid-safe moderated community with no personal messaging. COPPA-compliant safety features, content filtering, and reporting tools. Ages 9-14 code in protected environment.',
                'url': 'https://www.gethopscotch.com/',
                'source': 'Hopscotch',
                'category': 'Learning Platform',
                'stem_fields': 'Digital Citizenship, Online Safety, Community Guidelines',
                'target_grade': '4-8',
                'cost': 'Free',
                'location_type': 'Feature',
                'time_commitment': 'Not applicable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Hopscotch coding scraping...")
        print("Note: Creating Hopscotch tutorial and project resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Hopscotch entries...")
        self.resources = self.create_hopscotch_resources()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/hopscotch_coding.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = HopscotchCodingScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
