#!/usr/bin/env python3
"""
IXL Learning K-12 Platform Scraper
Scrapes adaptive learning curriculum across all K-12 subjects
Saves to: data/ixl_learning.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class IXLLearningScraper:
    def __init__(self):
        self.base_url = "https://www.ixl.com"
        self.target_urls = [
            "https://www.ixl.com/",
            "https://www.ixl.com/math/",
            "https://www.ixl.com/science/",
            "https://www.ixl.com/membership",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_ixl_learning_subjects(self) -> List[Dict]:
        """Create IXL Learning subject/grade combinations."""
        resources = [
            # Math by grade level
            {
                'name': 'IXL Math - Kindergarten',
                'description': 'Comprehensive kindergarten math curriculum with 200+ skills. Counting to 20, number recognition, basic addition and subtraction, shapes, patterns, measurement, and comparison. Adaptive practice with instant feedback.',
                'url': 'https://www.ixl.com/math/kindergarten',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Early Math',
                'target_grade': 'K',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - 1st Grade',
                'description': 'First grade math with 300+ skills. Addition and subtraction within 20, place value, time, money, measurement, data and graphs, and geometry. Standards-aligned adaptive learning.',
                'url': 'https://www.ixl.com/math/grade-1',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Arithmetic',
                'target_grade': '1',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - 2nd Grade',
                'description': 'Second grade math covering 400+ skills. Addition and subtraction within 100, place value to 1000, multiplication foundations, fractions, measurement, time, money, and data analysis.',
                'url': 'https://www.ixl.com/math/grade-2',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Arithmetic',
                'target_grade': '2',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - 3rd Grade',
                'description': 'Third grade math with 500+ skills. Multiplication and division, fractions, area and perimeter, time, measurement, data, and problem-solving. Interactive practice with real-world applications.',
                'url': 'https://www.ixl.com/math/grade-3',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Multiplication, Fractions',
                'target_grade': '3',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - 4th Grade',
                'description': 'Fourth grade math covering 600+ skills. Multi-digit multiplication and division, fractions and decimals, measurement conversions, geometry, and data interpretation. Comprehensive skill building.',
                'url': 'https://www.ixl.com/math/grade-4',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Fractions, Decimals, Geometry',
                'target_grade': '4',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - 5th Grade',
                'description': 'Fifth grade math with 700+ skills. Decimal operations, fraction operations, volume, coordinate planes, and algebraic thinking. Prepare for middle school mathematics.',
                'url': 'https://www.ixl.com/math/grade-5',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Decimals, Algebra Basics',
                'target_grade': '5',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - 6th Grade',
                'description': 'Sixth grade math covering 800+ skills. Ratios, rates, percentages, negative numbers, algebraic expressions, equations, area, surface area, and statistics. Middle school mathematics foundation.',
                'url': 'https://www.ixl.com/math/grade-6',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Algebra, Ratios, Statistics',
                'target_grade': '6',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - 7th Grade',
                'description': 'Seventh grade math with 900+ skills. Proportional relationships, rational numbers, linear equations, geometric constructions, probability, and statistics. Advanced middle school topics.',
                'url': 'https://www.ixl.com/math/grade-7',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Algebra, Geometry, Probability',
                'target_grade': '7',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - 8th Grade',
                'description': 'Eighth grade math covering 1000+ skills. Linear functions, systems of equations, transformations, Pythagorean theorem, exponents, and scientific notation. Algebra 1 preparation.',
                'url': 'https://www.ixl.com/math/grade-8',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Algebra, Functions, Geometry',
                'target_grade': '8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - Algebra 1',
                'description': 'Complete Algebra 1 curriculum with 1000+ skills. Linear equations, inequalities, systems, quadratic functions, polynomials, factoring, and exponential functions. High school mathematics foundation.',
                'url': 'https://www.ixl.com/math/algebra-1',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Algebra, Equations, Functions',
                'target_grade': '8-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - Geometry',
                'description': 'Comprehensive geometry curriculum with 900+ skills. Proofs, transformations, congruence, similarity, trigonometry, circles, and coordinate geometry. Visual and interactive practice.',
                'url': 'https://www.ixl.com/math/geometry',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Geometry, Trigonometry, Proofs',
                'target_grade': '9-11',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - Algebra 2',
                'description': 'Advanced algebra with 1100+ skills. Polynomials, rational expressions, logarithms, sequences, series, conic sections, and complex numbers. College preparatory mathematics.',
                'url': 'https://www.ixl.com/math/algebra-2',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Algebra, Advanced Math',
                'target_grade': '10-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - Precalculus',
                'description': 'Precalculus curriculum with 800+ skills. Advanced functions, trigonometry, vectors, matrices, parametric equations, and polar coordinates. Preparation for calculus.',
                'url': 'https://www.ixl.com/math/precalculus',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Precalculus, Trigonometry, Advanced Math',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Math - Calculus',
                'description': 'Calculus curriculum covering limits, derivatives, integrals, and applications. AP Calculus AB/BC aligned content with comprehensive practice problems.',
                'url': 'https://www.ixl.com/math/calculus',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Calculus, Advanced Math',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'High',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Science by grade level
            {
                'name': 'IXL Science - 2nd Grade',
                'description': 'Elementary science curriculum with 150+ skills. Plants and animals, habitats, matter, forces, energy, weather, and scientific inquiry. Interactive diagrams and real-world scenarios.',
                'url': 'https://www.ixl.com/science/grade-2',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Biology, Physics, Earth Science',
                'target_grade': '2',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Science - 3rd Grade',
                'description': 'Third grade science with 200+ skills. Life cycles, ecosystems, properties of matter, forces and motion, weather patterns, and engineering design. NGSS-aligned curriculum.',
                'url': 'https://www.ixl.com/science/grade-3',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Biology, Physics, Engineering',
                'target_grade': '3',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Science - 4th Grade',
                'description': 'Fourth grade science covering 250+ skills. Energy transfer, waves, structures of life, Earth systems, natural resources, and technology. Interactive science simulations.',
                'url': 'https://www.ixl.com/science/grade-4',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Physics, Biology, Earth Science, Technology',
                'target_grade': '4',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Science - 5th Grade',
                'description': 'Fifth grade science with 300+ skills. Matter and energy, ecosystems, Earth systems, space systems, and engineering solutions. Comprehensive elementary science conclusion.',
                'url': 'https://www.ixl.com/science/grade-5',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Physics, Biology, Earth Science, Space Science',
                'target_grade': '5',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Science - 6th Grade',
                'description': 'Sixth grade science covering 350+ skills. Cell structure, genetics, plate tectonics, energy resources, thermal energy, and scientific investigation. Middle school science foundation.',
                'url': 'https://www.ixl.com/science/grade-6',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Biology, Earth Science, Physics, Genetics',
                'target_grade': '6',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Science - 7th Grade',
                'description': 'Seventh grade science with 400+ skills. Chemical reactions, force and motion, waves, evolution, biodiversity, Earth history, and climate. Advanced middle school topics.',
                'url': 'https://www.ixl.com/science/grade-7',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Chemistry, Physics, Biology, Earth Science',
                'target_grade': '7',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Science - 8th Grade',
                'description': 'Eighth grade science covering 450+ skills. Atomic structure, periodic table, motion and forces, energy, reproduction, inheritance, and astronomy. High school science preparation.',
                'url': 'https://www.ixl.com/science/grade-8',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Chemistry, Physics, Biology, Astronomy',
                'target_grade': '8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Science - Biology',
                'description': 'High school biology curriculum with 500+ skills. Cell biology, genetics, evolution, ecology, human body systems, and scientific practices. Comprehensive life science course.',
                'url': 'https://www.ixl.com/science/biology',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Biology, Genetics, Ecology',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Science - Chemistry',
                'description': 'High school chemistry with 450+ skills. Atomic theory, chemical bonding, stoichiometry, thermodynamics, kinetics, equilibrium, and acid-base chemistry. College preparatory chemistry.',
                'url': 'https://www.ixl.com/science/chemistry',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Chemistry, Chemical Reactions',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Science - Physics',
                'description': 'High school physics covering 400+ skills. Mechanics, energy, waves, electricity, magnetism, and modern physics. Mathematical problem-solving and conceptual understanding.',
                'url': 'https://www.ixl.com/science/physics',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Physics, Mechanics, Electricity',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Science - Earth Science',
                'description': 'High school Earth science with 350+ skills. Geology, meteorology, oceanography, astronomy, and environmental science. Study Earth systems and space.',
                'url': 'https://www.ixl.com/science/earth-science',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Earth Science, Geology, Astronomy',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Additional subjects
            {
                'name': 'IXL Social Studies - Elementary (K-5)',
                'description': 'Elementary social studies covering geography, history, civics, and culture. Map skills, historical events, community, and citizenship concepts. Interactive content for young learners.',
                'url': 'https://www.ixl.com/social-studies/',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Social Studies, Geography, History',
                'target_grade': 'K-5',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Language Arts - Reading Comprehension (All Grades)',
                'description': 'Comprehensive reading comprehension across K-12. Literary analysis, informational texts, vocabulary development, and critical reading skills. Adaptive leveled passages.',
                'url': 'https://www.ixl.com/ela/',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Language Arts, Reading, Literacy',
                'target_grade': 'K-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Spanish - Elementary to High School',
                'description': 'Spanish language learning across all levels. Vocabulary, grammar, verb conjugations, reading comprehension, and cultural understanding. Interactive language practice.',
                'url': 'https://www.ixl.com/spanish/',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'World Languages, Spanish',
                'target_grade': 'K-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Analytics - Student Progress Tracking',
                'description': 'Comprehensive analytics dashboard tracking student progress, skill mastery, time spent, and areas needing improvement. Real-time insights for parents and teachers. Included with subscription.',
                'url': 'https://www.ixl.com/',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Educational Technology, Data Analytics',
                'target_grade': 'K-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'IXL Diagnostic - Adaptive Assessment',
                'description': 'Adaptive diagnostic assessment identifying student knowledge gaps and strengths across subjects. Creates personalized learning paths based on assessment results. Continuous diagnostic throughout learning.',
                'url': 'https://www.ixl.com/',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Educational Assessment, Adaptive Learning',
                'target_grade': 'K-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'IXL Awards and Certificates',
                'description': 'Motivation system with awards, certificates, and achievement tracking. Students earn awards for skill mastery, practice time, and continuous learning. Gamification elements to encourage engagement.',
                'url': 'https://www.ixl.com/',
                'source': 'IXL Learning',
                'category': 'Learning Platform',
                'stem_fields': 'Educational Motivation, Gamification',
                'target_grade': 'K-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': 'Ongoing',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Subscription',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting IXL Learning scraping...")
        print("Note: Creating IXL Learning subject/grade combinations")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating IXL Learning entries...")
        self.resources = self.create_ixl_learning_subjects()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/ixl_learning.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = IXLLearningScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
