#!/usr/bin/env python3
"""
Mystery Science Elementary Science Lessons Scraper
Scrapes video-based science lessons for grades K-5
Saves to: data/mystery_science.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class MysteryScienceScraper:
    def __init__(self):
        self.base_url = "https://mysteryscience.com"
        self.target_urls = [
            "https://mysteryscience.com/",
            "https://mysteryscience.com/school/overview",
            "https://mysteryscience.com/mini-lessons",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_mystery_science_lessons(self) -> List[Dict]:
        """Create Mystery Science lesson resources."""
        resources = [
            # Kindergarten Lessons
            {
                'name': 'Mystery Science - Kindergarten: Animal Superpowers',
                'description': 'Explore how animals use special features to survive. Video lessons on animal adaptations, camouflage, and defense mechanisms. Hands-on activities observing and comparing animal traits. 30-45 minute lessons with minimal materials.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Biology, Zoology, Animal Adaptations',
                'target_grade': 'K',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - Kindergarten: Sunlight and Weather',
                'description': 'Investigate how sunlight affects Earth and weather patterns. Video-based exploration of day/night, seasons, and temperature. Simple outdoor observations and data collection. NGSS-aligned earth science for early learners.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Weather, Astronomy, Meteorology',
                'target_grade': 'K',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - Kindergarten: Pushes and Pulls',
                'description': 'Explore forces through hands-on activities. Test how pushes and pulls affect motion using everyday objects. Video demonstrations of force concepts. Build understanding of physics through play-based learning.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Forces, Motion, Physical Science',
                'target_grade': 'K',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # 1st Grade Lessons
            {
                'name': 'Mystery Science - 1st Grade: Light and Sound',
                'description': 'Investigate how light travels and sounds are made. Hands-on exploration of shadows, reflection, vibration, and volume. Video lessons demonstrating wave properties. Simple experiments with flashlights and musical instruments.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Light, Sound, Waves, Physical Science',
                'target_grade': '1',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 1st Grade: Plant and Animal Relationships',
                'description': 'Explore how plants and animals depend on each other. Study pollination, seed dispersal, and food chains. Video-based investigation of ecosystems. Outdoor observations of local plants and animals.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Ecology, Biology, Interdependence',
                'target_grade': '1',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 1st Grade: Moon, Sun, and Stars',
                'description': 'Observe patterns in the sky. Track moon phases, explore why we have day and night, and identify star patterns. Video lessons on space science. Simple observation journals and sky watching activities.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Astronomy, Space Science, Earth Science, Patterns',
                'target_grade': '1',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # 2nd Grade Lessons
            {
                'name': 'Mystery Science - 2nd Grade: Properties of Matter',
                'description': 'Investigate materials and their properties. Test solid, liquid, and gas states. Explore heating, cooling, and reversible changes. Video demonstrations of matter transformations with hands-on experiments.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Chemistry, Matter, Physical Science, Properties',
                'target_grade': '2',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 2nd Grade: Plant Life Cycles',
                'description': 'Study how plants grow and reproduce. Plant seeds, observe germination, and track growth stages. Video lessons on pollination and seed formation. Document plant life cycles through drawings and journals.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Botany, Biology, Plant Science',
                'target_grade': '2',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 2nd Grade: Earth\'s Land and Water',
                'description': 'Explore Earth\'s diverse landscapes and water features. Study mountains, valleys, rivers, and oceans. Map local landforms and water sources. Video tours of geological formations and erosion processes.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Geology, Geography, Landforms',
                'target_grade': '2',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # 3rd Grade Lessons
            {
                'name': 'Mystery Science - 3rd Grade: Weather and Climate',
                'description': 'Investigate weather patterns and climate zones. Track temperature, precipitation, and wind over time. Video lessons on meteorology and climate science. Build weather instruments and analyze data.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Meteorology, Climate Science, Data Analysis',
                'target_grade': '3',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 3rd Grade: Forces and Interactions',
                'description': 'Explore balanced and unbalanced forces. Investigate friction, magnetism, and gravity through experiments. Video demonstrations of force concepts. Design solutions using force principles.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Forces, Motion, Engineering',
                'target_grade': '3',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 3rd Grade: Traits and Inheritance',
                'description': 'Study how organisms inherit traits from parents. Observe variation in species and family resemblances. Video lessons on genetics basics. Create family tree diagrams showing inherited characteristics.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Genetics, Biology, Heredity',
                'target_grade': '3',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 3rd Grade: Fossils and Ancient Life',
                'description': 'Discover how fossils form and what they reveal about ancient organisms. Create fossil models and study geological time. Video explorations of paleontology. Learn how scientists reconstruct ancient environments.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Paleontology, Geology, Earth Science, Evolution',
                'target_grade': '3',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # 4th Grade Lessons
            {
                'name': 'Mystery Science - 4th Grade: Energy Transfer',
                'description': 'Investigate how energy moves and changes form. Explore kinetic and potential energy, heat transfer, and electrical circuits. Video lessons on energy concepts. Build simple machines and circuits.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Energy, Engineering, Physical Science',
                'target_grade': '4',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 4th Grade: Waves and Information',
                'description': 'Study how waves transmit information. Explore light waves, sound waves, and digital communication. Video demonstrations of wave properties. Design devices that use waves to send signals.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Waves, Communication Technology, Engineering',
                'target_grade': '4',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 4th Grade: Weathering and Erosion',
                'description': 'Investigate how Earth\'s surface changes over time. Model erosion processes using wind, water, and ice. Video lessons on geological changes. Map erosion patterns in local environment.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Geology, Erosion, Environmental Science',
                'target_grade': '4',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 4th Grade: Animal Senses and Communication',
                'description': 'Explore how animals use senses to survive and communicate. Study echolocation, pheromones, and visual signals. Video lessons on animal behavior. Compare human and animal sensory systems.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Zoology, Animal Behavior, Biology',
                'target_grade': '4',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # 5th Grade Lessons
            {
                'name': 'Mystery Science - 5th Grade: Matter and Energy in Ecosystems',
                'description': 'Study how matter and energy flow through food webs. Investigate photosynthesis, decomposition, and nutrient cycling. Video lessons on ecosystem dynamics. Create food web models.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Ecology, Energy Flow, Ecosystems',
                'target_grade': '5',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 5th Grade: Earth\'s Systems',
                'description': 'Explore interactions between geosphere, hydrosphere, atmosphere, and biosphere. Study water cycle, rock cycle, and climate systems. Video lessons on Earth system science. Model system interactions.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Systems Thinking, Environmental Science, Geology',
                'target_grade': '5',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 5th Grade: Space Systems',
                'description': 'Study Earth, Moon, and Sun interactions. Investigate seasons, eclipses, and tides. Video tours of solar system. Build scale models demonstrating orbital mechanics and astronomical phenomena.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Astronomy, Space Science, Physics, Earth Science',
                'target_grade': '5',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - 5th Grade: Structure and Properties of Matter',
                'description': 'Investigate particle theory and chemical changes. Test physical vs chemical changes, mixtures vs solutions. Video demonstrations of molecular behavior. Conduct experiments measuring mass and volume.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Chemistry, Matter, Physical Science, Molecular Science',
                'target_grade': '5',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Mini-Lessons
            {
                'name': 'Mystery Science - Mini-Lesson: Why Do Leaves Change Color?',
                'description': 'Quick 15-minute lesson on autumn leaf color change. Video explaining chlorophyll breakdown and pigment reveal. Perfect for seasonal science or filling class time. Minimal materials needed.',
                'url': 'https://mysteryscience.com/mini-lessons',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Botany, Chemistry, Plant Science',
                'target_grade': '2-5',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': '15 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - Mini-Lesson: How Do Airplanes Fly?',
                'description': 'Brief exploration of flight and aerodynamics. Video demonstrating lift, drag, thrust, and weight. Simple paper airplane activity. 15-minute engaging introduction to physics.',
                'url': 'https://mysteryscience.com/mini-lessons',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Aerodynamics, Engineering, Forces',
                'target_grade': '3-5',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': '15 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - Mini-Lesson: Why Is the Ocean Salty?',
                'description': 'Quick lesson on ocean salinity and the water cycle. Video explaining mineral dissolution and evaporation. 15-minute exploration of earth science concepts. Accessible for multiple grade levels.',
                'url': 'https://mysteryscience.com/mini-lessons',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Oceanography, Chemistry, Water Science',
                'target_grade': '2-5',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': '15 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - Mini-Lesson: How Do Chameleons Change Color?',
                'description': 'Fast-paced lesson on animal adaptations and camouflage. Video revealing chromatophore cells and color-changing mechanisms. 15-minute engaging biology content for elementary students.',
                'url': 'https://mysteryscience.com/mini-lessons',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Biology, Zoology, Animal Adaptations',
                'target_grade': '1-5',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': '15 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Home Learning Version
            {
                'name': 'Mystery Science - Home Learning Edition',
                'description': 'Free access to video lessons for home learning. Parents guide children through science lessons at home. Same high-quality content adapted for family use. Minimal materials using household items.',
                'url': 'https://mysteryscience.com/',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Multi-Subject Science, At-Home Learning',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Home',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Household-Items',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            # School Subscription
            {
                'name': 'Mystery Science - School Subscription',
                'description': 'Full-access subscription for schools providing complete K-5 science curriculum. Teacher guides, assessments, and additional resources. Professional development support. NGSS-aligned comprehensive program.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Multi-Subject Science, Curriculum, Teacher Resources',
                'target_grade': 'K-5',
                'cost': 'Paid',
                'location_type': 'Classroom',
                'time_commitment': 'Full curriculum',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'School-district',
                'family_income_consideration': 'Not applicable',
                'hidden_costs_level': 'Materials',
                'cost_category': '$500-$1000',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Additional Cross-Grade Lessons
            {
                'name': 'Mystery Science - Engineering Design Challenges',
                'description': 'Cross-grade engineering projects solving real-world problems. Design, test, and improve solutions using engineering design process. Video guidance and material lists. Adaptable for grades K-5.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Engineering, Design Thinking, Problem Solving, STEM',
                'target_grade': 'K-5',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '45-60 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - Scientific Method Practice',
                'description': 'Lessons teaching inquiry skills across topics. Ask questions, make predictions, test hypotheses, analyze data, and draw conclusions. Video modeling scientific thinking. Adaptable experiments for all elementary grades.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Scientific Method, Inquiry, Critical Thinking, Research Skills',
                'target_grade': 'K-5',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - Spanish Language Lessons',
                'description': 'Select lessons available in Spanish for dual-language classrooms and Spanish-speaking families. Video content with Spanish narration. Support bilingual science education and English language learners.',
                'url': 'https://mysteryscience.com/',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Multi-Subject Science, Bilingual Education, Language Support',
                'target_grade': 'K-5',
                'cost': 'Freemium',
                'location_type': 'Classroom',
                'time_commitment': '30-45 minutes',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'School-based',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mystery Science - Free School Program',
                'description': 'Free full access for Title I schools and high-need districts. Complete K-5 science curriculum at no cost to qualifying schools. Application process for schools serving low-income communities. Equity-focused distribution.',
                'url': 'https://mysteryscience.com/school/overview',
                'source': 'Mystery Science',
                'category': 'Learning Platform',
                'stem_fields': 'Multi-Subject Science, Educational Equity, Title I Support',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': 'Full curriculum',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Application-based',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Full-access',
                'family_income_consideration': 'Title I eligibility',
                'hidden_costs_level': 'Materials',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Mystery Science scraping...")
        print("Note: Creating Mystery Science lesson resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Mystery Science entries...")
        self.resources = self.create_mystery_science_lessons()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/mystery_science.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = MysteryScienceScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
