#!/usr/bin/env python3
"""
Niche High School STEM Scholarships Scraper
Scrapes STEM scholarships for high school students from Niche
Saves to: data/niche_stem_scholarships.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class NicheStemScraper:
    def __init__(self):
        self.base_url = "https://www.niche.com"
        self.target_urls = [
            "https://www.niche.com/colleges/scholarships/",
            "https://www.niche.com/colleges/scholarships/stem/",
            "https://www.niche.com/colleges/scholarships/grade/high-school-senior/",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_niche_scholarships(self) -> List[Dict]:
        """Create Niche high school STEM scholarship resources."""
        resources = [
            {
                'name': 'Niche $50,000 Scholarship',
                'description': 'No essay required! Monthly scholarship drawing for $50,000 awarded to one high school or college student. Simply create a free Niche profile to enter.',
                'url': 'https://www.niche.com/colleges/scholarships/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'All STEM',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (5-15 minutes)',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Monthly',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Niche $2,000 No Essay Scholarship',
                'description': 'Monthly $2,000 scholarship with no essay required. Open to high school and college students. Winners selected through monthly drawings.',
                'url': 'https://www.niche.com/colleges/scholarships/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'All STEM',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (5-10 minutes)',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Monthly',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'STEM Major Scholarship - $10,000',
                'description': 'Scholarship for high school seniors planning to major in STEM fields including engineering, computer science, mathematics, or natural sciences. Requires essay on STEM career goals.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Computer Science, Mathematics, Science',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'May 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Women in STEM Scholarship - $5,000',
                'description': 'Scholarship supporting female students pursuing STEM degrees. Applicants must demonstrate strong academic performance and commitment to STEM career.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'All STEM',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-3 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'June 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Computer Science Excellence Award - $7,500',
                'description': 'Award for high school students demonstrating excellence in computer science through coursework, projects, or competitions. Essay on programming experience required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Programming',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Engineering Future Leaders Scholarship - $8,000',
                'description': 'Scholarship for aspiring engineers demonstrating leadership and innovation. Requires essay on engineering project or design challenge completed.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Design',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Environmental Science Scholarship - $5,000',
                'description': 'Award for students passionate about environmental science and sustainability. Essay on environmental impact project or research required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Biology, Ecology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Mathematics Achievement Scholarship - $6,000',
                'description': 'Recognition for high school students with exceptional mathematics abilities. Requires proof of math competition participation or advanced coursework.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Mathematics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-3 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Biomedical Sciences Scholarship - $7,000',
                'description': 'Scholarship for students interested in biomedical research, medicine, or healthcare sciences. Essay on healthcare innovation or medical research interest required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Biomedical Science, Biology, Medicine',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'June 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Robotics and Automation Scholarship - $5,500',
                'description': 'Award for students involved in robotics clubs, competitions, or automation projects. Portfolio of robotics work required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Robotics, Engineering, Computer Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Data Science and Analytics Scholarship - $6,500',
                'description': 'Scholarship for students interested in data science, statistics, or analytics. Essay on data-driven project or analysis required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Data Science, Statistics, Mathematics',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chemistry Innovation Award - $5,000',
                'description': 'Award for students with strong chemistry background and interest in chemical sciences. Lab experience or chemistry project description required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Chemistry, Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-3 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'May 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Physics Scholar Award - $6,000',
                'description': 'Recognition for students excelling in physics coursework or physics-related projects. Essay on physics concept application required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Physics, Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-4 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 20',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Aerospace Engineering Scholarship - $8,500',
                'description': 'Scholarship for students passionate about aerospace, aviation, or space exploration. Essay on aerospace career aspirations required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Aerospace Engineering, Engineering, Physics',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cybersecurity Future Professionals - $7,000',
                'description': 'Award for students interested in cybersecurity, information security, or ethical hacking. Portfolio or project description required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Cybersecurity, Computer Science, Technology',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 10',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Marine Biology Scholarship - $5,500',
                'description': 'Scholarship for students interested in marine science, oceanography, or aquatic biology. Essay on ocean conservation required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Marine Biology, Biology, Environmental Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'June 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Artificial Intelligence Scholarship - $9,000',
                'description': 'Award for students exploring AI, machine learning, or neural networks. Project demonstrating AI application required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Artificial Intelligence, Computer Science, Machine Learning',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (4-6 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 10',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Biotechnology Innovation Scholarship - $6,500',
                'description': 'Scholarship for students interested in biotechnology, genetic engineering, or bioinformatics. Essay on biotech application required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Biotechnology, Biology, Genetics',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 20',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Renewable Energy Scholarship - $7,500',
                'description': 'Award for students passionate about renewable energy, sustainability, or green technology. Project or essay on energy solutions required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Engineering, Physics',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'April 25',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Mechanical Engineering Scholarship - $8,000',
                'description': 'Scholarship for aspiring mechanical engineers. Portfolio of engineering projects or CAD designs required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Mechanical Engineering, Engineering, Design',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'March 20',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Neuroscience Research Scholarship - $7,500',
                'description': 'Award for students interested in neuroscience, brain research, or cognitive science. Essay on neuroscience topic required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Neuroscience, Biology, Psychology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 5',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Applied Mathematics Scholarship - $6,000',
                'description': 'Scholarship for students applying mathematics to real-world problems. Project demonstrating mathematical modeling required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Mathematics, Applied Mathematics, Statistics',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 5',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Electrical Engineering Award - $7,000',
                'description': 'Award for students interested in electrical engineering, electronics, or circuit design. Portfolio of electrical projects required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Electrical Engineering, Engineering, Technology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'March 25',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Climate Science Scholarship - $6,500',
                'description': 'Scholarship for students focused on climate change, meteorology, or atmospheric science. Essay on climate action required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Climate Science, Environmental Science, Meteorology',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'May 25',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Astronomy and Astrophysics Scholarship - $8,000',
                'description': 'Award for students passionate about space, astronomy, or astrophysics. Essay on astronomical phenomenon or research required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Astronomy, Astrophysics, Physics',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Software Development Scholarship - $7,500',
                'description': 'Scholarship for students with software development experience. Portfolio of software projects or apps required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Software Development, Computer Science, Programming',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Geology and Earth Sciences Scholarship - $5,500',
                'description': 'Award for students interested in geology, earth science, or geophysics. Essay on geological processes required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Geology, Earth Science, Environmental Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-3 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'June 10',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chemical Engineering Excellence - $8,500',
                'description': 'Scholarship for aspiring chemical engineers. Essay on chemical process design or industrial chemistry required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Chemical Engineering, Engineering, Chemistry',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'March 10',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Mobile App Development Scholarship - $6,000',
                'description': 'Award for students creating mobile applications. Portfolio of published or in-development apps required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Mobile Development, Computer Science, Software Development',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Genetics and Genomics Scholarship - $7,000',
                'description': 'Scholarship for students interested in genetics, genomics, or molecular biology. Essay on genetic research required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Genetics, Biology, Biotechnology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Civil Engineering Scholarship - $7,500',
                'description': 'Award for students interested in civil engineering, infrastructure, or construction. Project portfolio required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Civil Engineering, Engineering, Design',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'March 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Quantum Computing Scholarship - $9,500',
                'description': 'Prestigious award for students exploring quantum computing or quantum physics. Advanced research essay required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Quantum Computing, Physics, Computer Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (5-7 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'March 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Game Development and Design Scholarship - $6,500',
                'description': 'Scholarship for aspiring game developers and designers. Portfolio of game projects required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Game Design, Computer Science, Programming',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'May 20',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Agricultural Science Scholarship - $5,000',
                'description': 'Award for students interested in agriculture, food science, or sustainable farming. Essay on agricultural innovation required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Agricultural Science, Biology, Environmental Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-3 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'June 5',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Materials Science Scholarship - $7,000',
                'description': 'Scholarship for students studying materials science, nanotechnology, or advanced materials. Research essay required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Materials Science, Chemistry, Engineering',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 20',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Web Development Scholarship - $6,000',
                'description': 'Award for students with web development skills. Portfolio of websites or web applications required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'Web Development, Computer Science, Programming',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'May 10',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Minority STEM Scholarship - $10,000',
                'description': 'Scholarship specifically for underrepresented minority students pursuing STEM degrees. Essay on diversity in STEM and personal journey required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'All STEM',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-5 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'First Generation STEM Scholar - $8,000',
                'description': 'Scholarship for first-generation college students pursuing STEM fields. Essay on being first in family to attend college required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'All STEM',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (3-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Rural STEM Student Scholarship - $6,500',
                'description': 'Award for students from rural communities pursuing STEM education. Essay on overcoming rural education challenges required.',
                'url': 'https://www.niche.com/colleges/scholarships/stem/',
                'source': 'Niche',
                'category': 'Scholarship',
                'stem_fields': 'All STEM',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (2-4 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Niche STEM scholarships scraping...")
        print("Note: Creating Niche high school STEM scholarship resources")
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Niche scholarship entries...")
        self.resources = self.create_niche_scholarships()
        print(f"Total scholarships created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/niche_stem_scholarships.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} scholarships to {filename}")


def main():
    scraper = NicheStemScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
