#!/usr/bin/env python3
"""
NSBE Jr. (National Society of Black Engineers Junior) Programs Scraper
Scrapes STEM programs and competitions for Black K-12 students
Saves to: data/nsbe_jr.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class NSBEJrScraper:
    def __init__(self):
        self.base_url = "https://www.nsbe.org"
        self.target_urls = [
            "https://www.nsbe.org/Programs/Pre-College-Initiative.aspx",
            "https://www.nsbe.org/nsbejr",
            "https://www.nsbe.org/Get-Involved/NSBE-Jr.aspx",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_nsbe_jr_programs(self) -> List[Dict]:
        """Create NSBE Jr. program resources."""
        resources = [
            {
                'name': 'NSBE Jr. - National Membership Program',
                'description': 'National Society of Black Engineers Junior membership program for Black K-12 students interested in STEM careers. Access to local chapter meetings, workshops, and competitions. Networking with Black engineers and STEM professionals. College preparation resources and mentorship. Leadership development through chapter officer positions. Annual membership provides year-round programming and support. Focus on building pipeline of Black engineers. Access to national conferences and regional events.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Membership',
                'stem_fields': 'Engineering, Computer Science, Technology, Mathematics, Science',
                'target_grade': 'K-12',
                'cost': 'Paid',
                'location_type': 'Hybrid',
                'time_commitment': 'Year-round',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Low',
                'cost_category': '$50-$100',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Try-Engineering Competition',
                'description': 'National engineering design competition for NSBE Jr. members in grades 6-12. Teams design and build solutions to real-world engineering challenges. Categories for middle school and high school divisions. Projects judged on creativity, technical execution, and presentation. Winners receive scholarships and recognition at national conference. Emphasis on teamwork and engineering design process. Mentorship from chapter advisors and professional engineers. Virtual submission with potential in-person finals.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Competition',
                'stem_fields': 'Engineering, Design, Problem Solving, Teamwork',
                'target_grade': '6-12',
                'cost': 'Paid',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 months',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Prizes-available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Materials',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Torch Awards Competition',
                'description': 'Academic excellence and leadership competition for NSBE Jr. members. Students submit portfolios demonstrating STEM achievement, community service, and leadership. Categories for elementary, middle, and high school. Winners receive scholarships and recognition at national convention. Emphasis on well-rounded excellence. Includes essay, transcript, and recommendation letters. Preparation for college applications. National and regional awards.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Competition',
                'stem_fields': 'All STEM Fields, Leadership, Academic Excellence',
                'target_grade': 'K-12',
                'cost': 'Paid',
                'location_type': 'Virtual',
                'time_commitment': '1-2 months',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'January',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Scholarships-available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Low',
                'cost_category': '$50-$100',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Annual National Convention Youth Track',
                'description': 'Multi-day youth track at NSBE National Convention for K-12 members. Engineering workshops, college fair, career expo, and competitions. Meet Black engineers from Fortune 500 companies. Hands-on STEM activities and team challenges. Leadership development and college preparation sessions. Networking with thousands of Black STEM professionals. Awards ceremonies and scholarship announcements. Typically held in March. Registration includes convention access and materials.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Conference',
                'stem_fields': 'Engineering, Technology, Career Development, Networking',
                'target_grade': 'K-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '3-5 days',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Travel-Hotel',
                'cost_category': '$500-$1000',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Regional Leadership Conferences',
                'description': 'Regional conferences held throughout the year in NSBE regions. Leadership training, STEM workshops, and team building activities. More affordable and accessible than national convention. Opportunity to meet students from nearby chapters. Engineering challenges and academic competitions. College representatives and career panels. Typically one-day or weekend events. Lower cost alternative to national programming.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Conference',
                'stem_fields': 'Engineering, Leadership, STEM Education',
                'target_grade': 'K-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1-2 days',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Varies',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Travel',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Low',
                'regional_availability': 'Regional',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Local Chapter Meetings',
                'description': 'Weekly or monthly chapter meetings at schools or community centers. STEM activities, guest speakers, and college preparation. Homework help and tutoring from high school and college mentors. Field trips to engineering companies and universities. Community service projects applying STEM skills. Leadership opportunities through chapter officer positions. Family-friendly environment welcoming parents. Free or low-cost for members.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Program',
                'stem_fields': 'All STEM Fields, Tutoring, Mentorship',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': 'Weekly',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Low',
                'regional_availability': 'Local',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Summer Engineering Experience for Kids (SEEK)',
                'description': 'Week-long day camp introducing elementary students to engineering. Hands-on projects in different engineering disciplines each day. Build bridges, circuits, robots, and simple machines. Field trips to engineering sites. Age-appropriate activities for grades K-5. Lunch and materials provided. Held at university campuses and community centers. Emphasis on making engineering fun and accessible. Limited financial aid available.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Camp',
                'stem_fields': 'Engineering, Hands-on Projects, Design',
                'target_grade': 'K-5',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1 week',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'May',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Low',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Low',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - College Tours Program',
                'description': 'Organized visits to Historically Black Colleges and Universities (HBCUs) and other top engineering schools. Meet Black engineering students and faculty. Tour campus facilities, labs, and residence halls. Learn about admissions, scholarships, and financial aid. Understand college life and academic expectations. Typically for middle and high school students. May include overnight stays. Build excitement about college STEM pathways.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Program',
                'stem_fields': 'College Preparation, Career Exploration, Engineering Education',
                'target_grade': '6-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '1-3 days',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Varies',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Travel',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Low',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Mentorship Circles',
                'description': 'Structured mentorship pairing NSBE Jr. members with college students and professional engineers. Monthly virtual or in-person meetings. Academic guidance, career advice, and personal development. Help with college applications and scholarship essays. Exposure to different engineering careers. Long-term relationships building over years. Focus on Black engineering role models. Support navigating challenges as Black student in STEM.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Mentorship',
                'stem_fields': 'Engineering, Career Development, Academic Support',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Year-round',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - STEM Saturday Academies',
                'description': 'Monthly Saturday enrichment programs offering advanced STEM instruction. Topics include coding, robotics, 3D design, and engineering principles. Small class sizes with individualized attention. Project-based learning with take-home creations. College students and professionals as instructors. Breakfast and lunch often provided. Academic year program supplementing school curriculum. Free or low-cost for chapter members.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Program',
                'stem_fields': 'Coding, Robotics, 3D Design, Engineering',
                'target_grade': '6-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': 'Monthly',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Low',
                'cost_category': '$50-$100',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Low',
                'regional_availability': 'Local',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Parent and Family Engagement',
                'description': 'Programming designed to engage parents in supporting their children STEM education. Workshops on college planning, financial aid, and scholarship applications. Information sessions about engineering careers and pathways. Networking opportunities with other Black STEM families. Resources for advocating for children in schools. Family STEM nights and social events. Recognition that family support is critical to student success.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Program',
                'stem_fields': 'Family Engagement, College Planning, Advocacy',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Quarterly',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Academic Excellence Workshops',
                'description': 'Workshops focusing on study skills, time management, and academic success strategies. Test preparation for SAT, ACT, and AP exams. Math and science tutoring sessions. Writing workshops for essays and research papers. Learning strategies specific to STEM subjects. Building confidence in academic abilities. Peer study groups and accountability partners. Free for members.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Program',
                'stem_fields': 'Academic Skills, Test Preparation, Tutoring, Study Skills',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Monthly',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Corporate Partner Internships and Shadowing',
                'description': 'Summer internship and job shadowing opportunities with corporate partners like Boeing, Lockheed Martin, and Microsoft. High school students get real-world engineering experience. Week-long or summer-long placements. Paid internships when possible. Learn about different engineering roles and industries. Build professional skills and resume. Networking with corporate engineers. Preference given to active NSBE Jr. members.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Program',
                'stem_fields': 'Engineering, Career Experience, Professional Development',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '1-8 weeks',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Stipend-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Transportation',
                'cost_category': 'Paid-Program',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Low',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Online Learning Platform',
                'description': 'Digital platform with STEM learning resources, video tutorials, and online workshops. Self-paced courses in engineering fundamentals, coding, and mathematics. Webinars with Black engineers and STEM professionals. Virtual study halls and homework help. Competition resources and submission portals. 24/7 access to educational content. Supplementing local chapter programming. Especially valuable for students without local chapters.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Program',
                'stem_fields': 'All STEM Fields, Online Learning, Self-Paced Education',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Beginner',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NSBE Jr. - Scholarship and Financial Aid Workshops',
                'description': 'Workshops helping students and families navigate college funding. Information on NSBE scholarships, STEM scholarships, and general financial aid. Help completing FAFSA and scholarship applications. Essay writing workshops for scholarship applications. Connecting students with scholarship opportunities. Understanding costs of different colleges. Financial literacy for college students. Critical support for families new to college process.',
                'url': 'https://www.nsbe.org/nsbejr',
                'source': 'NSBE Jr.',
                'category': 'Program',
                'stem_fields': 'College Preparation, Financial Literacy, Scholarship Applications',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Quarterly',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Information-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Professional'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting NSBE Jr. Programs scraping...")
        print("Note: Creating NSBE Jr. program resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating NSBE Jr. entries...")
        self.resources = self.create_nsbe_jr_programs()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/nsbe_jr.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = NSBEJrScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
