#!/usr/bin/env python3
"""
Osmo Hands-On Learning Platform Scraper
Scrapes hands-on + digital learning games for ages 3-12
Saves to: data/osmo_learning.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class OsmoLearningScraper:
    def __init__(self):
        self.base_url = "https://www.playosmo.com"
        self.target_urls = [
            "https://www.playosmo.com/",
            "https://www.playosmo.com/en/shopping/games/",
            "https://www.playosmo.com/en/coding/",
            "https://www.playosmo.com/en/learning/",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_osmo_games(self) -> List[Dict]:
        """Create Osmo Learning game resources."""
        resources = [
            {
                'name': 'Osmo - Tangram',
                'description': 'Classic tangram puzzle game with physical pieces and digital feedback. Arrange geometric shapes to match on-screen puzzles. Develops spatial reasoning, problem-solving, and geometric thinking through 500+ puzzles with progressive difficulty.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Geometry, Spatial Reasoning, Problem Solving',
                'target_grade': 'PreK-5',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Numbers',
                'description': 'Hands-on math game using physical number tiles and on-screen challenges. Build number sense, addition, subtraction, and counting through interactive gameplay. Features multiple difficulty levels adapting to ages 5-10 with over 50 games.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Arithmetic, Number Sense, Problem Solving',
                'target_grade': 'K-4',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Words',
                'description': 'Spelling and vocabulary game with letter tiles. Guess words based on visual clues and place physical letters to spell answers. Builds literacy, vocabulary, and spelling skills for ages 5-12 with hundreds of word challenges.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Literacy, Vocabulary, Language Arts, Spelling',
                'target_grade': 'K-6',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Coding Awbie',
                'description': 'Introduction to coding using physical coding blocks. Guide Awbie character through adventures by arranging command blocks. Teaches sequencing, loops, and problem-solving to ages 5-10 through 60+ coding puzzles.',
                'url': 'https://www.playosmo.com/en/coding/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Computational Thinking, Logic',
                'target_grade': 'K-4',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Coding Jam',
                'description': 'Advanced coding game creating musical compositions. Use coding blocks to program beats, melodies, and harmonies. Combines programming fundamentals with music theory for ages 5-12. Develop computational thinking while making music.',
                'url': 'https://www.playosmo.com/en/coding/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Music, Audio Engineering',
                'target_grade': 'K-6',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Coding Duo',
                'description': 'Cooperative coding game for two players using physical blocks. Solve coding challenges together teaching teamwork, communication, and programming logic. Ages 5-10 develop collaborative problem-solving through 60+ puzzles.',
                'url': 'https://www.playosmo.com/en/coding/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Teamwork, Communication',
                'target_grade': 'K-4',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Pizza Co.',
                'description': 'Math and entrepreneurship game running virtual pizza business. Calculate change, manage toppings, and handle orders using physical coins and bills. Ages 5-12 develop money math, fractions, and business skills through gameplay.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Business, Economics, Money Math',
                'target_grade': 'K-6',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Masterpiece',
                'description': 'Digital drawing and art game with physical drawing. Transform photos into line drawings and trace with real paper and markers. Develop artistic skills, visual perception, and fine motor control for ages 5-12.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Art, Design, Visual Arts, Fine Motor Skills',
                'target_grade': 'K-6',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Monster',
                'description': 'Creative drawing game bringing drawings to life. Draw characters, objects, and scenery with physical materials while digital monster interacts. Ages 3-8 develop creativity, imagination, and artistic expression.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Art, Creativity, Design, Imagination',
                'target_grade': 'PreK-2',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Newton',
                'description': 'Physics puzzle game using real-world objects. Guide falling balls to targets by placing physical items like pencils, toys, or hands. Ages 5-12 learn physics concepts, cause-and-effect, and creative problem-solving through 60+ levels.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Engineering, Problem Solving, Creativity',
                'target_grade': 'K-6',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Detective Agency',
                'description': 'Geography and world knowledge game solving mysteries globally. Use physical magnifying glass to find clues and travel the world solving cases. Ages 5-12 develop geography, cultural awareness, and deductive reasoning through 60+ mysteries.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Geography, World Cultures, Critical Thinking, Research',
                'target_grade': 'K-6',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Squiggle Magic',
                'description': 'Early learning game for preschoolers combining drawing and letter recognition. Draw squiggles that transform into animated characters teaching letters, shapes, and creativity. Ages 3-5 develop pre-literacy and fine motor skills.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Pre-Literacy, Letters, Shapes, Fine Motor Skills',
                'target_grade': 'PreK-K',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - ABCs',
                'description': 'Alphabet learning game with physical letter tiles. Match uppercase and lowercase letters, learn letter sounds, and build early literacy. Ages 3-6 develop phonics awareness and letter recognition through interactive play.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Pre-Literacy, Alphabet, Phonics, Letter Recognition',
                'target_grade': 'PreK-1',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Stories',
                'description': 'Storytelling and reading comprehension game with physical costume pieces. Dress characters and create interactive stories developing literacy and creativity. Ages 4-7 build narrative skills and reading comprehension.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Literacy, Storytelling, Reading Comprehension, Creativity',
                'target_grade': 'PreK-2',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Costume Party',
                'description': 'Pattern recognition and matching game with costume pieces. Dress on-screen characters by matching physical costume accessories. Ages 3-5 develop visual discrimination, matching skills, and social-emotional learning.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Pattern Recognition, Visual Discrimination, Matching, Social Skills',
                'target_grade': 'PreK-K',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Creative Starter Kit',
                'description': 'Bundle including Tangram, Numbers, and Words games with Osmo Base. Complete starter package for ages 5-12 covering math, geometry, and literacy. Foundation for hands-on digital learning with three core educational games.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Geometry, Literacy, Multi-Subject',
                'target_grade': 'K-6',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Coding Starter Kit',
                'description': 'Bundle with Coding Awbie, Coding Jam, and Coding Duo plus Osmo Base. Comprehensive introduction to programming for ages 5-12 using physical coding blocks. Three games teaching sequencing, loops, and computational thinking.',
                'url': 'https://www.playosmo.com/en/coding/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Computational Thinking, Logic',
                'target_grade': 'K-6',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Little Genius Starter Kit',
                'description': 'Early learning bundle for ages 3-5 with ABCs, Squiggle Magic, Costume Party, and Stories. Comprehensive preschool curriculum covering letters, shapes, creativity, and social-emotional skills through hands-on play.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Pre-Literacy, Letters, Shapes, Creativity, Social-Emotional',
                'target_grade': 'PreK-K',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Genius Starter Kit',
                'description': 'Complete learning bundle with five core games: Tangram, Numbers, Words, Newton, and Masterpiece plus Osmo Base. Ages 6-12 comprehensive STEM and creativity education covering math, literacy, physics, and art.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Literacy, Physics, Art, Multi-Subject',
                'target_grade': '1-6',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Math Wizard Series',
                'description': 'Advanced math game series teaching addition, subtraction, multiplication, and division through magical adventures. Physical number and operation tiles solve puzzles and defeat dragons. Ages 6-10 build computational fluency.',
                'url': 'https://www.playosmo.com/en/shopping/games/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Arithmetic, Operations, Number Sense',
                'target_grade': '1-4',
                'cost': 'Paid',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Basic arithmetic',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Not available',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Parent and Teacher Dashboard',
                'description': 'Free web portal tracking child progress across all Osmo games. View skills developed, time played, levels completed, and areas for growth. Generate progress reports and set learning goals. Monitor multiple children.',
                'url': 'https://www.playosmo.com/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Educational Technology, Progress Tracking, Data Analytics',
                'target_grade': 'PreK-6',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Classroom Educator Resources',
                'description': 'Free teaching resources including lesson plans, curriculum guides, and classroom management tools. Standards-aligned activities for integrating Osmo into K-6 classrooms. Professional development materials for educators.',
                'url': 'https://www.playosmo.com/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Educational Resources, Curriculum, Teacher Professional Development',
                'target_grade': 'K-6',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Osmo - Multi-Language Support',
                'description': 'Games available in 20+ languages including Spanish, French, German, Japanese, and Chinese. Language-agnostic games like Tangram and Newton work universally. Supports English language learners and international families.',
                'url': 'https://www.playosmo.com/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Language Support, Accessibility, Inclusive Design',
                'target_grade': 'PreK-6',
                'cost': 'Free',
                'location_type': 'Feature',
                'time_commitment': 'Not applicable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Osmo - Screen Time Alternative',
                'description': 'Physical hands-on learning reducing passive screen time. Children manipulate real objects while receiving digital feedback. Promotes active learning, motor skills, and healthy tech habits for ages 3-12.',
                'url': 'https://www.playosmo.com/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Hands-On Learning, Active Learning, Healthy Technology Use',
                'target_grade': 'PreK-6',
                'cost': 'Free',
                'location_type': 'Feature',
                'time_commitment': 'Not applicable',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Osmo - Special Education Support',
                'description': 'Games designed for children with diverse learning needs including visual, tactile, and kinesthetic learners. Physical manipulation supports fine motor development and multisensory learning. Used in special education classrooms.',
                'url': 'https://www.playosmo.com/',
                'source': 'Osmo',
                'category': 'Learning Platform',
                'stem_fields': 'Special Education, Accessibility, Inclusive Design, Multi-Sensory',
                'target_grade': 'PreK-6',
                'cost': 'Free',
                'location_type': 'Feature',
                'time_commitment': 'Not applicable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Osmo Learning scraping...")
        print("Note: Creating Osmo Learning game resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Osmo Learning entries...")
        self.resources = self.create_osmo_games()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/osmo_learning.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = OsmoLearningScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
