#!/usr/bin/env python3
"""
Outschool Online STEM Classes Scraper
Scrapes STEM classes for K-12 students from Outschool
Saves to: data/outschool_stem.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class OutschoolStemScraper:
    def __init__(self):
        self.base_url = "https://outschool.com"
        self.target_urls = [
            "https://outschool.com/",
            "https://outschool.com/classes/stem",
            "https://outschool.com/classes/science",
            "https://outschool.com/classes/coding",
            "https://outschool.com/classes/math",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_outschool_classes(self) -> List[Dict]:
        """Create Outschool STEM class resources."""
        resources = [
            # Coding Classes
            {
                'name': 'Python Programming for Beginners',
                'description': 'Introduction to Python programming for ages 10-14. Learn variables, loops, functions, and create interactive projects including games and animations.',
                'url': 'https://outschool.com/classes/coding',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Computer Science, Programming, Python',
                'target_grade': '5-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '8 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Scratch Coding for Kids',
                'description': 'Learn block-based programming with Scratch. Ages 7-11 create games, animations, and interactive stories while learning coding fundamentals.',
                'url': 'https://outschool.com/classes/coding',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Computer Science, Programming, Game Design',
                'target_grade': '2-5',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '4 weeks (45 min/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Java Programming Fundamentals',
                'description': 'Comprehensive Java course for ages 13-17. Learn object-oriented programming, data structures, and prepare for AP Computer Science A.',
                'url': 'https://outschool.com/classes/coding',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Computer Science, Programming, Java',
                'target_grade': '8-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12 weeks (1.5 hours/week)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Web Development - HTML, CSS, JavaScript',
                'description': 'Build responsive websites from scratch. Ages 11-16 learn HTML, CSS, JavaScript and create portfolio-ready projects.',
                'url': 'https://outschool.com/classes/coding',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Web Development, Computer Science, Programming',
                'target_grade': '6-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '10 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Game Development with Unity',
                'description': 'Create 3D games using Unity game engine. Ages 12-17 learn C# programming, game design, and publish playable games.',
                'url': 'https://outschool.com/classes/coding',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Game Design, Computer Science, Programming',
                'target_grade': '7-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12 weeks (1.5 hours/week)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Mobile App Development for iOS',
                'description': 'Build iPhone apps using Swift. Ages 13-18 learn iOS development, UI design, and publish apps to App Store.',
                'url': 'https://outschool.com/classes/coding',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Mobile Development, Computer Science, Swift',
                'target_grade': '8-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '10 weeks (1.5 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Roblox Game Creation',
                'description': 'Design and program Roblox games using Lua. Ages 9-13 learn scripting, 3D modeling, and game mechanics.',
                'url': 'https://outschool.com/classes/coding',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Game Design, Programming, Computer Science',
                'target_grade': '4-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Minecraft Coding with Python',
                'description': 'Program Minecraft worlds using Python. Ages 10-14 learn coding while building automated structures and custom game modes.',
                'url': 'https://outschool.com/classes/coding',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Programming, Computer Science, Game Design',
                'target_grade': '5-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Math Classes
            {
                'name': 'Pre-Algebra Mastery',
                'description': 'Complete pre-algebra course for ages 11-13. Cover integers, fractions, decimals, equations, and problem-solving strategies.',
                'url': 'https://outschool.com/classes/math',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Mathematics',
                'target_grade': '6-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '16 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Algebra 1 Complete Course',
                'description': 'Full Algebra 1 curriculum for ages 12-15. Linear equations, quadratics, polynomials, and real-world applications.',
                'url': 'https://outschool.com/classes/math',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Mathematics, Algebra',
                'target_grade': '7-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '30 weeks (1.5 hours/week)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Geometry with Proofs',
                'description': 'High school geometry for ages 13-16. Euclidean geometry, proofs, transformations, and coordinate geometry.',
                'url': 'https://outschool.com/classes/math',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Mathematics, Geometry',
                'target_grade': '8-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '30 weeks (1.5 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Competition Math - AMC Prep',
                'description': 'Prepare for AMC 8/10 competitions. Ages 11-15 learn problem-solving strategies, number theory, and competition techniques.',
                'url': 'https://outschool.com/classes/math',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Mathematics, Problem Solving',
                'target_grade': '6-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12 weeks (1.5 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Calculus AB Preparation',
                'description': 'AP Calculus AB course for ages 15-18. Limits, derivatives, integrals, and applications. Full AP exam preparation.',
                'url': 'https://outschool.com/classes/math',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Mathematics, Calculus',
                'target_grade': '10-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '30 weeks (2 hours/week)',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Statistics and Probability',
                'description': 'Introduction to statistics for ages 13-17. Data analysis, probability theory, distributions, and hypothesis testing.',
                'url': 'https://outschool.com/classes/math',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Mathematics, Statistics',
                'target_grade': '8-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12 weeks (1 hour/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Math Puzzles and Logic',
                'description': 'Fun math puzzles and brain teasers for ages 8-12. Develop logical thinking through engaging challenges.',
                'url': 'https://outschool.com/classes/math',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Mathematics, Logic, Problem Solving',
                'target_grade': '3-6',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (45 min/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Science Classes
            {
                'name': 'Biology Foundations',
                'description': 'Introduction to biology for ages 12-15. Cells, genetics, evolution, ecology, and body systems.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Biology, Science',
                'target_grade': '7-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '16 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Chemistry for Teens',
                'description': 'High school chemistry course for ages 14-17. Atoms, molecules, reactions, stoichiometry, and lab demonstrations.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Chemistry, Science',
                'target_grade': '9-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '30 weeks (1.5 hours/week)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Physics Fundamentals',
                'description': 'Introduction to physics for ages 13-16. Motion, forces, energy, waves, electricity, and magnetism.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Physics, Science',
                'target_grade': '8-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '20 weeks (1.5 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Environmental Science and Ecology',
                'description': 'Study ecosystems, conservation, and environmental issues. Ages 11-15 explore sustainability and climate science.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Environmental Science, Biology, Ecology',
                'target_grade': '6-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '10 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Astronomy and Space Science',
                'description': 'Explore the universe for ages 9-14. Solar system, stars, galaxies, and space exploration.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Astronomy, Physics, Space Science',
                'target_grade': '4-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '8 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Marine Biology',
                'description': 'Study ocean life and ecosystems for ages 10-15. Marine animals, coral reefs, and ocean conservation.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Marine Biology, Biology, Environmental Science',
                'target_grade': '5-9',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Forensic Science',
                'description': 'Crime scene investigation for ages 11-16. Learn evidence collection, DNA analysis, and scientific methods.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Forensic Science, Chemistry, Biology',
                'target_grade': '6-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '8 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Genetics and DNA',
                'description': 'Learn about heredity and genetic engineering for ages 12-16. DNA structure, inheritance, and biotechnology.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Genetics, Biology, Biotechnology',
                'target_grade': '7-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Engineering and Robotics
            {
                'name': 'LEGO Robotics for Kids',
                'description': 'Build and program LEGO robots for ages 7-11. Learn engineering principles and basic coding.',
                'url': 'https://outschool.com/classes/stem',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Robotics, Engineering, Programming',
                'target_grade': '2-5',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Arduino Robotics and Electronics',
                'description': 'Build electronic projects with Arduino for ages 12-17. Circuit design, sensors, and microcontroller programming.',
                'url': 'https://outschool.com/classes/stem',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Robotics, Engineering, Electronics',
                'target_grade': '7-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '10 weeks (1.5 hours/week)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Engineering Design Challenge',
                'description': 'Solve engineering problems for ages 10-14. Design thinking, prototyping, and testing solutions.',
                'url': 'https://outschool.com/classes/stem',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Engineering, Design, Problem Solving',
                'target_grade': '5-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': '3D Design and Printing',
                'description': 'Create 3D models using Tinkercad for ages 9-14. Learn CAD design and 3D printing concepts.',
                'url': 'https://outschool.com/classes/stem',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': '3D Design, Engineering, Technology',
                'target_grade': '4-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (1 hour/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Data Science and AI
            {
                'name': 'Data Science for Teens',
                'description': 'Introduction to data analysis for ages 13-17. Python, pandas, visualization, and machine learning basics.',
                'url': 'https://outschool.com/classes/stem',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Data Science, Programming, Statistics',
                'target_grade': '8-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '12 weeks (1.5 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Artificial Intelligence Basics',
                'description': 'Introduction to AI and machine learning for ages 12-16. Neural networks, training models, and AI applications.',
                'url': 'https://outschool.com/classes/stem',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Artificial Intelligence, Computer Science, Machine Learning',
                'target_grade': '7-10',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '10 weeks (1.5 hours/week)',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Cybersecurity for Beginners',
                'description': 'Learn online safety and ethical hacking for ages 12-17. Network security, encryption, and safe computing practices.',
                'url': 'https://outschool.com/classes/stem',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Cybersecurity, Computer Science, Technology',
                'target_grade': '7-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '8 weeks (1 hour/week)',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Young Learners
            {
                'name': 'Science Explorers for Young Kids',
                'description': 'Hands-on science experiments for ages 5-8. Learn about animals, plants, weather, and simple machines.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Science, Biology, Physics',
                'target_grade': 'K-2',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (30 min/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Math Fun with Games',
                'description': 'Learn math through games for ages 6-9. Addition, subtraction, shapes, and patterns in engaging activities.',
                'url': 'https://outschool.com/classes/math',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Mathematics',
                'target_grade': '1-3',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '8 weeks (30 min/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Coding for Pre-Readers',
                'description': 'Visual coding for ages 4-7 using ScratchJr. Learn sequencing and problem-solving through play.',
                'url': 'https://outschool.com/classes/coding',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Computer Science, Programming',
                'target_grade': 'PreK-1',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '4 weeks (30 min/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Animal Science for Kids',
                'description': 'Learn about animals and habitats for ages 6-10. Zoology, animal behavior, and conservation.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Biology, Zoology, Science',
                'target_grade': '1-4',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (45 min/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Dinosaurs and Paleontology',
                'description': 'Explore prehistoric life for ages 7-11. Dinosaurs, fossils, extinction, and paleontology careers.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Paleontology, Science, Biology',
                'target_grade': '2-5',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '4 weeks (45 min/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Weather and Climate for Kids',
                'description': 'Learn about weather patterns for ages 8-12. Meteorology, clouds, storms, and climate change basics.',
                'url': 'https://outschool.com/classes/science',
                'source': 'Outschool',
                'category': 'Online Class',
                'stem_fields': 'Meteorology, Earth Science, Climate Science',
                'target_grade': '3-6',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '6 weeks (45 min/week)',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Per-Class',
                'cost_category': '$50-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Outschool STEM classes scraping...")
        print("Note: Creating Outschool online class resources")
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Outschool class entries...")
        self.resources = self.create_outschool_classes()
        print(f"Total classes created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/outschool_stem.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} classes to {filename}")


def main():
    scraper = OutschoolStemScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
