#!/usr/bin/env python3
"""
PBS Kids STEM Learning Resources Scraper
Scrapes free educational games and activities for ages 2-8
Saves to: data/pbs_kids_stem.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class PBSKidsSTEMScraper:
    def __init__(self):
        self.base_url = "https://pbskids.org"
        self.target_urls = [
            "https://pbskids.org/",
            "https://pbskids.org/games/science/",
            "https://pbskids.org/games/engineering/",
            "https://pbskids.org/games/math/",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_pbs_kids_stem_resources(self) -> List[Dict]:
        """Create PBS Kids STEM game and activity resources."""
        resources = [
            {
                'name': 'PBS Kids - Curious George: Rocket Run',
                'description': 'Build and launch rockets with Curious George. Learn physics concepts including thrust, weight, and trajectory. Design rockets by selecting fuel types and nose cones. Ages 4-7 experiment with trial and error to reach space.',
                'url': 'https://pbskids.org/games/engineering/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Engineering, Aerospace, Problem Solving',
                'target_grade': 'PreK-2',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Sid the Science Kid: Bug Garden',
                'description': 'Explore life science and ecology with Sid. Plant seeds, water gardens, and observe insect life cycles. Learn about plant growth, pollination, and ecosystems. Ages 3-6 develop observation and classification skills.',
                'url': 'https://pbskids.org/games/science/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Life Science, Biology, Ecology, Observation',
                'target_grade': 'PreK-1',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Cyberchase: Thirteen Ways of Looking at a Half',
                'description': 'Explore fractions and equivalence with Cyberchase characters. Divide shapes and quantities to understand halves, quarters, and equal parts. Ages 6-8 develop fraction sense and spatial reasoning through interactive puzzles.',
                'url': 'https://pbskids.org/games/math/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Fractions, Geometry, Problem Solving',
                'target_grade': '1-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Wild Kratts: Creature Power',
                'description': 'Learn animal biology and adaptations with Wild Kratts brothers. Activate creature powers to explore animal abilities and habitats. Ages 4-8 discover zoology, classification, and biological adaptations through interactive adventures.',
                'url': 'https://pbskids.org/games/science/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Biology, Zoology, Animal Science, Ecology',
                'target_grade': 'PreK-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Peg + Cat: Chicken Problem',
                'description': 'Solve math problems with Peg and Cat using addition and subtraction. Count chickens and solve real-world word problems. Ages 3-5 develop early numeracy, counting skills, and problem-solving strategies.',
                'url': 'https://pbskids.org/games/math/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Counting, Addition, Problem Solving',
                'target_grade': 'PreK-K',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Design Squad: Build a Skyscraper',
                'description': 'Engineering design challenge building stable structures. Test materials, design foundations, and create earthquake-resistant buildings. Ages 6-8 learn structural engineering, material properties, and iterative design.',
                'url': 'https://pbskids.org/games/engineering/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Engineering, Structural Design, Physics, Problem Solving',
                'target_grade': '1-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Dinosaur Train: Dinosaur Sorting',
                'description': 'Classification and sorting activity with dinosaurs. Sort dinosaurs by characteristics including diet, habitat, and time period. Ages 3-6 develop scientific classification, categorization, and logical thinking.',
                'url': 'https://pbskids.org/games/science/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Paleontology, Classification, Biology, Logic',
                'target_grade': 'PreK-1',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Odd Squad: Odd Squad Gadget Lab',
                'description': 'Solve math mysteries using gadgets and problem-solving. Apply arithmetic, patterns, and logic to complete agent missions. Ages 5-8 develop computational thinking and mathematical reasoning.',
                'url': 'https://pbskids.org/games/math/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Logic, Patterns, Problem Solving',
                'target_grade': 'K-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Nature Cat: Nature Explore',
                'description': 'Outdoor science exploration with Nature Cat. Investigate ecosystems, weather, and natural phenomena. Ages 3-6 learn earth science, biology, and environmental awareness through virtual nature adventures.',
                'url': 'https://pbskids.org/games/science/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Ecology, Biology, Environmental Science',
                'target_grade': 'PreK-1',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Molly of Denali: Sled Dog Dash',
                'description': 'Math and strategy game planning sled dog race routes. Calculate distances, estimate time, and manage resources. Ages 5-8 apply measurement, estimation, and problem-solving while learning Alaskan culture.',
                'url': 'https://pbskids.org/games/math/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Measurement, Estimation, Problem Solving',
                'target_grade': 'K-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Ready Jet Go!: Jet\'s Planet Pinball',
                'description': 'Space science and astronomy game exploring the solar system. Learn planet characteristics, orbits, and space facts through pinball gameplay. Ages 4-7 discover astronomy and planetary science.',
                'url': 'https://pbskids.org/games/science/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Astronomy, Space Science, Planetary Science, Physics',
                'target_grade': 'PreK-2',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Elinor Wonders Why: Backyard Exploration',
                'description': 'Scientific inquiry and observation with Elinor. Ask questions, make predictions, and test hypotheses about nature. Ages 3-6 develop scientific method, inquiry skills, and curiosity through investigation.',
                'url': 'https://pbskids.org/games/science/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Scientific Method, Inquiry, Observation, Biology',
                'target_grade': 'PreK-1',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Arthur: Cast Your Vote',
                'description': 'Data analysis and graphing activity with Arthur. Conduct surveys, collect data, and create graphs to analyze results. Ages 5-8 learn statistics, data visualization, and democratic processes.',
                'url': 'https://pbskids.org/games/math/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Statistics, Data Analysis, Graphing',
                'target_grade': 'K-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Plum Landing: Mission to Mars',
                'description': 'Space exploration engineering challenge. Design Mars rovers, plan missions, and solve planetary science problems. Ages 6-8 develop engineering design process and space science knowledge.',
                'url': 'https://pbskids.org/games/engineering/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Engineering, Space Science, Robotics, Problem Solving',
                'target_grade': '1-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Sesame Street: Cookie Monster\'s Challenge',
                'description': 'Self-regulation and problem-solving with Cookie Monster. Complete puzzles requiring patience, planning, and strategy. Ages 3-5 develop executive function, patience, and mathematical thinking.',
                'url': 'https://pbskids.org/games/math/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Logic, Problem Solving, Executive Function',
                'target_grade': 'PreK-K',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Cat in the Hat: Sorting',
                'description': 'Classification and sorting with Cat in the Hat. Sort objects by color, size, shape, and function. Ages 3-5 develop categorization, attributes recognition, and logical thinking through interactive play.',
                'url': 'https://pbskids.org/games/science/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Classification, Logic, Attributes, Scientific Thinking',
                'target_grade': 'PreK-K',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Splash and Bubbles: Coral Reef Exploration',
                'description': 'Marine biology and ocean science with underwater friends. Explore coral reefs, identify sea creatures, and learn ocean ecosystems. Ages 4-7 discover marine life, habitats, and conservation.',
                'url': 'https://pbskids.org/games/science/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Marine Biology, Ecology, Oceanography, Conservation',
                'target_grade': 'PreK-2',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Daniel Tiger: Neighborhood Helpers',
                'description': 'Social-emotional learning and community helpers. Learn about occupations including doctors, engineers, and scientists. Ages 2-4 develop career awareness and social understanding.',
                'url': 'https://pbskids.org/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Career Awareness, Community, Social Skills, STEM Careers',
                'target_grade': 'PreK',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Clifford: Measurement Fun',
                'description': 'Measurement and comparison with Clifford the Big Red Dog. Compare sizes, measure lengths, and understand relative measurements. Ages 3-6 develop measurement concepts and spatial reasoning.',
                'url': 'https://pbskids.org/games/math/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Measurement, Comparison, Spatial Reasoning',
                'target_grade': 'PreK-1',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Xavier Riddle: Historical STEM Figures',
                'description': 'Learn about historical scientists and inventors. Meet Marie Curie, Alexander Graham Bell, and other STEM pioneers. Ages 4-7 discover science history and develop growth mindset.',
                'url': 'https://pbskids.org/games/science/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Science History, Biography, STEM Careers, Inspiration',
                'target_grade': 'PreK-2',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Super Why: Letter Power',
                'description': 'Literacy meets logic with letter recognition and word building. Decode words, spell answers, and solve reading puzzles. Ages 3-6 develop phonics, decoding, and early reading skills.',
                'url': 'https://pbskids.org/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Literacy, Phonics, Logic, Problem Solving',
                'target_grade': 'PreK-1',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Hero Elementary: Superpowers of Science',
                'description': 'Science superheroes solve problems using scientific method. Investigate, experiment, and apply science to help community. Ages 4-7 learn inquiry process, observation, and critical thinking.',
                'url': 'https://pbskids.org/games/science/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Scientific Method, Inquiry, Problem Solving, Critical Thinking',
                'target_grade': 'PreK-2',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Pinkalicious: Pattern Play',
                'description': 'Pattern recognition and creation with Pinkalicious. Identify, extend, and create patterns using colors, shapes, and objects. Ages 3-6 develop algebraic thinking and pattern recognition.',
                'url': 'https://pbskids.org/games/math/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Patterns, Algebra, Logic',
                'target_grade': 'PreK-1',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - PBS Parents: STEM Activities Guide',
                'description': 'Free downloadable activities and lesson plans for parents and educators. Hands-on STEM projects, experiments, and learning extensions. Support children ages 2-8 with at-home science and math enrichment.',
                'url': 'https://pbskids.org/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'STEM Education, Parent Resources, Activity Guides, Lesson Plans',
                'target_grade': 'PreK-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Games App',
                'description': 'Free mobile app with 100+ educational games. Download for offline play on tablets and phones. Ages 2-8 access PBS Kids STEM content anywhere without internet connection.',
                'url': 'https://pbskids.org/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Multi-Subject STEM, Mobile Learning, Educational Technology',
                'target_grade': 'PreK-3',
                'cost': 'Free',
                'location_type': 'Mobile App',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Video Player: STEM Episodes',
                'description': 'Free streaming of full-length STEM educational episodes. Watch shows including Wild Kratts, Cyberchase, Sid the Science Kid, and more. Ages 2-8 access curriculum-aligned science and math content.',
                'url': 'https://pbskids.org/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Multi-Subject STEM, Educational Media, Science Communication',
                'target_grade': 'PreK-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Spanish Language Resources',
                'description': 'Bilingual STEM games and content in Spanish. Support dual language learners and Spanish-speaking families. Ages 2-8 access culturally responsive STEM education in multiple languages.',
                'url': 'https://pbskids.org/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Multi-Subject STEM, Bilingual Education, Language Support',
                'target_grade': 'PreK-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Accessibility Features',
                'description': 'Closed captions, audio descriptions, and accessible controls. Support children with disabilities and diverse learning needs. Ages 2-8 access inclusive STEM learning with adaptive features.',
                'url': 'https://pbskids.org/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'Accessible Education, Inclusive Design, Universal Design for Learning',
                'target_grade': 'PreK-3',
                'cost': 'Free',
                'location_type': 'Feature',
                'time_commitment': 'Not applicable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'PBS Kids - Educator Resources Portal',
                'description': 'Free classroom resources, lesson plans, and professional development. Standards-aligned STEM curricula for PreK-3 teachers. Access teaching guides, assessment tools, and classroom activities.',
                'url': 'https://pbskids.org/',
                'source': 'PBS Kids',
                'category': 'Learning Platform',
                'stem_fields': 'STEM Education, Teacher Resources, Professional Development, Curriculum',
                'target_grade': 'PreK-3',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting PBS Kids STEM scraping...")
        print("Note: Creating PBS Kids STEM game and activity resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating PBS Kids STEM entries...")
        self.resources = self.create_pbs_kids_stem_resources()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/pbs_kids_stem.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = PBSKidsSTEMScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
