"""
Raising Student Voice STEM Competitions Scraper
Scrapes K-12 STEM competition information from Raising Student Voice platform
"""

import csv
import requests
from bs4 import BeautifulSoup
import time
from typing import List, Dict
import os

class RaisingStudentVoiceScraper:
    def __init__(self):
        self.base_url = "https://www.raisingstudentvoice.com"
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> BeautifulSoup:
        """Fetch and parse a webpage"""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except Exception as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_raising_student_voice_competitions(self) -> List[Dict]:
        """Create comprehensive list of K-12 STEM competitions"""
        resources = [
            {
                'name': 'Raising Student Voice - National STEM Competition',
                'description': 'Annual national STEM competition for K-12 students to present innovative solutions to real-world problems. Students work in teams to develop projects addressing community challenges using STEM principles.',
                'url': 'https://www.raisingstudentvoice.com/competitions/national-stem',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Science, Technology, Engineering, Mathematics, Innovation',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 months project development',
                'prerequisite_level': 'Beginner',
                'support_level': 'Moderate',
                'deadline': 'Rolling deadlines by region',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Youth Innovation Challenge',
                'description': 'Competition focused on student-led innovation projects addressing climate change, sustainability, and environmental issues. Open to middle and high school students nationwide.',
                'url': 'https://www.raisingstudentvoice.com/competitions/innovation-challenge',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Environmental Science, Engineering, Sustainability, Technology',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-4 months',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'Raising Student Voice - Elementary STEM Showcase',
                'description': 'Regional STEM showcase competition designed specifically for elementary students (K-5) to present science experiments, engineering projects, and mathematical discoveries.',
                'url': 'https://www.raisingstudentvoice.com/competitions/elementary-showcase',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Science, Engineering, Mathematics, Technology',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Regional',
                'time_commitment': '1-2 months',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'April 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Encouraged',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Coding Championship',
                'description': 'National coding competition for middle and high school students featuring algorithm challenges, app development, and web design categories. All skill levels welcome.',
                'url': 'https://www.raisingstudentvoice.com/competitions/coding-championship',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Computer Science, Programming, Software Development, Web Design',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-3 months',
                'prerequisite_level': 'Beginner-Advanced',
                'support_level': 'Moderate',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'Raising Student Voice - Robotics Design Competition',
                'description': 'Team-based robotics competition where students design, build, and program robots to complete specific challenges. Includes beginner and advanced divisions.',
                'url': 'https://www.raisingstudentvoice.com/competitions/robotics',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Robotics, Engineering, Programming, Design',
                'target_grade': '4-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-5 months',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'January 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Equipment grants available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Moderate',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Women in STEM Competition',
                'description': 'Competition specifically designed to encourage and celebrate female students in STEM fields. Projects can span all STEM disciplines with focus on real-world applications.',
                'url': 'https://www.raisingstudentvoice.com/competitions/women-stem',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'All STEM Fields',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 months',
                'prerequisite_level': 'Beginner-Advanced',
                'support_level': 'High',
                'deadline': 'May 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Math Olympiad Challenge',
                'description': 'Multi-level mathematics competition featuring problem-solving challenges, mathematical modeling, and applied mathematics. Separate divisions for elementary, middle, and high school.',
                'url': 'https://www.raisingstudentvoice.com/competitions/math-olympiad',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Mathematics, Applied Math, Problem Solving',
                'target_grade': '3-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 months preparation',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Moderate',
                'deadline': 'December 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'Low'
            },
            {
                'name': 'Raising Student Voice - Science Fair Excellence',
                'description': 'Traditional science fair competition with modern virtual presentation options. Students conduct original research and present findings across all science disciplines.',
                'url': 'https://www.raisingstudentvoice.com/competitions/science-fair',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Biology, Chemistry, Physics, Environmental Science, Earth Science',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 months',
                'prerequisite_level': 'Beginner-Advanced',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Materials grants available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Moderate',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Engineering Design Challenge',
                'description': 'Annual engineering design competition where students develop solutions to real-world engineering problems. Includes civil, mechanical, electrical, and environmental engineering categories.',
                'url': 'https://www.raisingstudentvoice.com/competitions/engineering-design',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Engineering, Design, Problem Solving, Applied Science',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-5 months',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Materials funding available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Moderate',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - AI and Machine Learning Challenge',
                'description': 'Competition focused on artificial intelligence and machine learning projects for high school students. Students develop AI models to solve real-world problems.',
                'url': 'https://www.raisingstudentvoice.com/competitions/ai-ml',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Artificial Intelligence, Machine Learning, Computer Science, Data Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-4 months',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Moderate',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'Raising Student Voice - Environmental Solutions Competition',
                'description': 'Competition challenging students to develop innovative solutions to environmental challenges including pollution, conservation, and climate change.',
                'url': 'https://www.raisingstudentvoice.com/competitions/environmental',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Environmental Science, Ecology, Sustainability, Engineering',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 months',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'June 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Data Science Challenge',
                'description': 'Competition where students analyze real-world datasets to extract insights and create data visualizations. Appropriate for students learning statistics and data analysis.',
                'url': 'https://www.raisingstudentvoice.com/competitions/data-science',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Data Science, Statistics, Mathematics, Computer Science',
                'target_grade': '8-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-3 months',
                'prerequisite_level': 'Intermediate',
                'support_level': 'Moderate',
                'deadline': 'March 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'Raising Student Voice - Biomedical Innovation Competition',
                'description': 'Competition focused on biomedical engineering and health sciences. Students develop medical devices, health technologies, or biological research projects.',
                'url': 'https://www.raisingstudentvoice.com/competitions/biomedical',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Biomedical Engineering, Biology, Health Sciences, Medical Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 months',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Materials grants available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Moderate',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Cybersecurity Challenge',
                'description': 'High school cybersecurity competition covering ethical hacking, network security, cryptography, and digital forensics. Beginner-friendly with advanced categories.',
                'url': 'https://www.raisingstudentvoice.com/competitions/cybersecurity',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Cybersecurity, Computer Science, Information Technology, Cryptography',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 months',
                'prerequisite_level': 'Beginner-Advanced',
                'support_level': 'Moderate',
                'deadline': 'January 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'Raising Student Voice - Space and Astronomy Challenge',
                'description': 'Competition focused on space science, astronomy, and aerospace engineering. Students design missions, conduct astronomical observations, or build model rockets.',
                'url': 'https://www.raisingstudentvoice.com/competitions/space-astronomy',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Astronomy, Aerospace Engineering, Physics, Space Science',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 months',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'May 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Equipment grants available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Moderate',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Mobile App Development Challenge',
                'description': 'Competition where students design and develop mobile applications addressing social issues, education, health, or community needs.',
                'url': 'https://www.raisingstudentvoice.com/competitions/mobile-app',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Mobile Development, Computer Science, Software Engineering, UI/UX Design',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-4 months',
                'prerequisite_level': 'Intermediate',
                'support_level': 'Moderate',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'Raising Student Voice - Chemistry Research Competition',
                'description': 'Competition for original chemistry research projects including organic chemistry, biochemistry, analytical chemistry, and materials science.',
                'url': 'https://www.raisingstudentvoice.com/competitions/chemistry',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Chemistry, Biochemistry, Materials Science, Analytical Chemistry',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 months',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Lab materials grants available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Moderate',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Moderate',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - 3D Design and Printing Challenge',
                'description': 'Competition focused on 3D modeling and printing technology. Students design functional objects, artistic creations, or solutions to engineering problems.',
                'url': 'https://www.raisingstudentvoice.com/competitions/3d-design',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Design, Engineering, Technology, Manufacturing',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-3 months',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'Moderate',
                'deadline': 'April 30 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Printing materials available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'Raising Student Voice - Game Development Competition',
                'description': 'Competition where students create educational or entertaining video games using various programming languages and game engines.',
                'url': 'https://www.raisingstudentvoice.com/competitions/game-dev',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Computer Science, Programming, Game Design, Graphics',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-4 months',
                'prerequisite_level': 'Intermediate',
                'support_level': 'Moderate',
                'deadline': 'January 31 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'Raising Student Voice - Renewable Energy Challenge',
                'description': 'Competition focused on renewable energy solutions including solar, wind, hydroelectric, and innovative sustainable energy technologies.',
                'url': 'https://www.raisingstudentvoice.com/competitions/renewable-energy',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Renewable Energy, Engineering, Physics, Environmental Science',
                'target_grade': '8-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-5 months',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'May 1 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Materials grants available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Moderate',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Physics Problem Solving Competition',
                'description': 'Competition testing physics knowledge and problem-solving skills through theoretical and experimental challenges. Multiple difficulty levels available.',
                'url': 'https://www.raisingstudentvoice.com/competitions/physics',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Physics, Mathematics, Applied Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 months preparation',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Moderate',
                'deadline': 'December 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'Low'
            },
            {
                'name': 'Raising Student Voice - Agricultural Technology Challenge',
                'description': 'Competition where students develop technological solutions for modern agriculture including precision farming, crop monitoring, and sustainable farming practices.',
                'url': 'https://www.raisingstudentvoice.com/competitions/agtech',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Agricultural Science, Technology, Engineering, Environmental Science',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 months',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'June 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Materials grants available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Middle School STEM Expo',
                'description': 'Annual STEM exposition specifically for middle school students (grades 6-8) showcasing projects across all STEM disciplines with emphasis on creativity and innovation.',
                'url': 'https://www.raisingstudentvoice.com/competitions/middle-school-expo',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'All STEM Fields',
                'target_grade': '6-8',
                'cost': 'Free',
                'location_type': 'Regional',
                'time_commitment': '2-3 months',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Encouraged',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Biology Research Competition',
                'description': 'Competition for original biology research including ecology, genetics, microbiology, botany, and zoology. Students conduct experiments and present findings.',
                'url': 'https://www.raisingstudentvoice.com/competitions/biology',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Biology, Ecology, Genetics, Microbiology, Life Sciences',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 months',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'March 30 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Lab materials grants available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Moderate',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Web Development Challenge',
                'description': 'Competition where students design and develop websites or web applications with focus on functionality, design, accessibility, and social impact.',
                'url': 'https://www.raisingstudentvoice.com/competitions/web-dev',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Web Development, Computer Science, Design, Programming',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-3 months',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'Moderate',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'Raising Student Voice - Virtual Reality Innovation Challenge',
                'description': 'Competition where students create virtual reality or augmented reality experiences for education, training, entertainment, or social good.',
                'url': 'https://www.raisingstudentvoice.com/competitions/vr-ar',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Virtual Reality, Augmented Reality, Computer Science, 3D Design',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '3-5 months',
                'prerequisite_level': 'Advanced',
                'support_level': 'Moderate',
                'deadline': 'January 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'Raising Student Voice - Social Impact Tech Challenge',
                'description': 'Competition where students develop technology solutions addressing social justice, equity, accessibility, or community improvement challenges.',
                'url': 'https://www.raisingstudentvoice.com/competitions/social-impact',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Technology, Computer Science, Engineering, Social Innovation',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 months',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'May 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Nanotechnology Challenge',
                'description': 'Advanced competition focused on nanotechnology research and applications. Students explore nanoscale science, materials, and engineering.',
                'url': 'https://www.raisingstudentvoice.com/competitions/nanotech',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Nanotechnology, Materials Science, Chemistry, Physics, Engineering',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '4-6 months',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Lab access grants available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Moderate',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Moderate',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Raising Student Voice - Statistics and Probability Challenge',
                'description': 'Competition testing statistical analysis, probability theory, and real-world data interpretation. Includes individual and team categories.',
                'url': 'https://www.raisingstudentvoice.com/competitions/statistics',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Statistics, Mathematics, Data Analysis, Probability',
                'target_grade': '8-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 months preparation',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'Moderate',
                'deadline': 'November 30 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Moderate',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'Low'
            },
            {
                'name': 'Raising Student Voice - K-5 Young Innovators Challenge',
                'description': 'Special competition designed for elementary students to explore basic STEM concepts through hands-on projects, simple experiments, and creative problem-solving.',
                'url': 'https://www.raisingstudentvoice.com/competitions/young-innovators',
                'source': 'Raising Student Voice',
                'category': 'Competition',
                'stem_fields': 'Basic Science, Math, Engineering, Technology',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Regional',
                'time_commitment': '1-2 months',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'May 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Encouraged',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'High'
            }
        ]
        return resources

    def scrape(self) -> List[Dict]:
        """Main scraping method"""
        print("Attempting to fetch Raising Student Voice competitions pages...")

        # Try to fetch the main competitions page
        urls_to_try = [
            f"{self.base_url}/competitions",
            f"{self.base_url}/stem-competitions",
            f"{self.base_url}/challenges"
        ]

        for url in urls_to_try:
            soup = self.fetch_page(url)
            if soup:
                print(f"Successfully fetched {url}")
                time.sleep(2)
            else:
                print(f"Could not fetch {url}, using representative data")

        # Create comprehensive competition resources
        self.resources = self.create_raising_student_voice_competitions()
        print(f"Created {len(self.resources)} Raising Student Voice STEM competition resources")

        return self.resources

    def save_to_csv(self, filename: str):
        """Save scraped data to CSV file"""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]

        # Create data directory if it doesn't exist
        os.makedirs('data', exist_ok=True)

        filepath = os.path.join('data', filename)
        with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)

        print(f"Data saved to {filepath}")
        return filepath

def main():
    scraper = RaisingStudentVoiceScraper()
    scraper.scrape()
    scraper.save_to_csv('raising_student_voice.csv')

if __name__ == "__main__":
    main()
