#!/usr/bin/env python3
"""
RISE (Research in Science & Engineering) Programs Scraper
Scrapes high school research internship opportunities
Saves to: data/rise_research.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class RISEResearchScraper:
    def __init__(self):
        self.base_url = "https://www.riseprograms.org"
        self.target_urls = [
            "https://www.riseprograms.org/programs",
            "https://www.riseprograms.org/research-opportunities",
            "https://www.riseprograms.org/summer-programs",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_rise_programs(self) -> List[Dict]:
        """Create RISE research program resources."""
        resources = [
            {
                'name': 'RISE Germany - Research Internships in Science and Engineering',
                'description': 'Prestigious 10-12 week summer research internship program for undergraduates at top German universities and research institutions. High school students entering college may apply. Work one-on-one with PhD advisors on cutting-edge research projects. Stipend provided covering living expenses. Housing assistance and German language course included. Research fields include physics, chemistry, biology, computer science, engineering, and mathematics. Develop international research experience and cultural competency. Strong academic record required (3.5+ GPA). Application includes transcripts, essays, and letters of recommendation.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Physics, Chemistry, Biology, Computer Science, Engineering, Mathematics',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '10-12 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'December',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Travel',
                'cost_category': 'Paid-Program',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Boston University RISE Practicum',
                'description': '6-week intensive summer research program at Boston University for rising high school seniors. Students conduct original research in life sciences, physical sciences, or engineering. Work in university laboratories with faculty mentors and graduate students. Residential program with housing and meals provided. Daily research, seminars, and scientific writing workshops. Produce research poster and presentation. Competitive admissions requiring strong STEM grades and passion for research. Program fee with need-based financial aid available. College credit option.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Life Sciences, Physical Sciences, Engineering, Laboratory Research',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'MIT RISE - Research in Science and Engineering',
                'description': '7-week summer research program at MIT for underrepresented high school students. Conduct research in engineering, computer science, or life sciences. Work with MIT faculty on authentic research projects. Program completely free including housing, meals, and stipend. Academic enrichment workshops and college preparation sessions. Focus on increasing diversity in STEM research. Strong preference for students from underrepresented minorities, women, first-generation college students, and low-income backgrounds. Minimum 3.0 GPA required.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Engineering, Computer Science, Life Sciences, Research Methods',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '7 weeks',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'January',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Fully-funded',
                'family_income_consideration': 'Preferred',
                'hidden_costs_level': 'None',
                'cost_category': 'Paid-Program',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Stanford RISE Summer Research Program',
                'description': '8-week residential research program at Stanford University for high school juniors and seniors. Students work in Stanford research labs conducting biomedical, engineering, or computational research. One-on-one mentorship from graduate students and faculty. Weekly seminars on research skills, graduate school applications, and scientific careers. Housing and meals provided. Research presentation at end of summer. Need-based financial aid available reducing barriers. Preference for students from underrepresented backgrounds in STEM.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Biomedical Research, Engineering, Computational Science, Laboratory Science',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Caltech RISE Research Program',
                'description': '10-week summer research immersion at Caltech for exceptional high school students. Work full-time in Caltech research laboratories on projects in physics, chemistry, biology, or engineering. Stipend provided along with housing. Weekly seminars and research group meetings. Opportunity to present at research conferences. Highly competitive admissions emphasizing academic excellence and research potential. Strong letters of recommendation and prior research experience valued. Produce publication-quality research.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Physics, Chemistry, Biology, Engineering, Astronomy',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '10 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'January',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend-provided',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Housing-provided',
                'cost_category': 'Paid-Program',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'NIH RISE Summer Research Program',
                'description': '8-week summer research internship at National Institutes of Health for high school students interested in biomedical research. Work alongside NIH scientists on health-related research projects. Stipend provided. Commuter program in Bethesda, MD area. Research areas include cancer biology, neuroscience, genetics, immunology, and public health. Weekly seminars and career development workshops. Produce research poster. Priority for local students and those from disadvantaged backgrounds. Strong science grades required.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Biomedical Research, Cancer Biology, Neuroscience, Genetics, Immunology, Public Health',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend-provided',
                'family_income_consideration': 'Preferred',
                'hidden_costs_level': 'Commuter',
                'cost_category': 'Paid-Program',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'UC Berkeley RISE Research Internship',
                'description': '6-week summer research program at UC Berkeley for California high school students. Conduct research in life sciences, physical sciences, or engineering with Berkeley faculty. Residential option available or commuter. Research project culminating in poster presentation. College credit offered. Financial aid available for students with demonstrated need. Focus on preparing students for college-level research. Laboratory safety training and research ethics workshops included.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Life Sciences, Physical Sciences, Engineering, Environmental Science',
                'target_grade': '10-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Variable',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'State',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Carnegie Mellon RISE Computer Science Research',
                'description': '7-week summer research program focusing on computer science and robotics at Carnegie Mellon University. High school students work on AI, machine learning, human-computer interaction, or robotics projects. Mentored by CMU faculty and PhD students. Residential program with housing and meals. Weekly tech talks and professional development. Produce working prototype or research paper. Program fee with need-based scholarships available. Preference for women and underrepresented minorities in CS.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Computer Science, Artificial Intelligence, Machine Learning, Robotics, Human-Computer Interaction',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '7 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Columbia RISE Biomedical Research',
                'description': '8-week summer biomedical research program at Columbia University Medical Center for NYC-area high school students. Work in medical research laboratories studying disease mechanisms, drug development, or public health. Mentored by Columbia faculty and medical students. Commuter program with stipend. Weekly seminars on careers in medicine and research. Hospital tours and clinical exposure. Focus on students from underserved communities. Minimum 3.0 GPA in science courses.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Biomedical Research, Medicine, Drug Development, Public Health, Clinical Research',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Stipend-provided',
                'family_income_consideration': 'Preferred',
                'hidden_costs_level': 'Commuter',
                'cost_category': 'Paid-Program',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'False',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'University of Washington RISE Engineering Research',
                'description': '6-week engineering research program for Pacific Northwest high school students. Conduct research in mechanical, electrical, civil, or biomedical engineering at UW. Faculty-mentored projects addressing real-world engineering challenges. Mix of residential and commuter options. Weekly design workshops and professional development. Build engineering portfolio. Financial aid available. Emphasis on recruiting women and minorities into engineering fields.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Mechanical Engineering, Electrical Engineering, Civil Engineering, Biomedical Engineering',
                'target_grade': '10-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Variable',
                'cost_category': '$500-$1000',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Yale RISE Summer Research Program',
                'description': '8-week residential research experience at Yale University for high school students. Research in biological sciences, chemistry, physics, or environmental science. Work alongside Yale researchers on ongoing projects. Housing, meals, and stipend provided. Scientific communication workshops and graduate school preparation. Research symposium at program end. Highly selective admissions. Priority for underrepresented minorities and first-generation college-bound students. Strong academic record required.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Biological Sciences, Chemistry, Physics, Environmental Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-person',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Fully-funded',
                'family_income_consideration': 'Preferred',
                'hidden_costs_level': 'None',
                'cost_category': 'Paid-Program',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'University of Michigan RISE Research Fellows',
                'description': '7-week summer research fellowship at University of Michigan for Midwest high school students. Research in natural sciences, engineering, or mathematics. Close mentorship from U-M faculty and graduate students. Residential program with housing and meals. Weekly research seminars and career panels. Develop research proposal, conduct experiments, and present findings. Need-based financial aid available. Focus on students from rural and underserved urban areas.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Natural Sciences, Engineering, Mathematics, Research Methods',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '7 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Georgia Tech RISE Engineering and Computing',
                'description': '6-week summer research program at Georgia Institute of Technology for high school students interested in engineering and computer science. Work on research projects in robotics, cybersecurity, materials science, or sustainable engineering. Faculty mentorship and hands-on laboratory work. Residential program in Atlanta. College credit option. Financial aid available for Georgia residents and students with demonstrated need. Team-based and individual research projects.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Engineering, Computer Science, Robotics, Cybersecurity, Materials Science',
                'target_grade': '10-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'High',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'University of Texas RISE Biotech Research',
                'description': '8-week biotechnology research program at UT Austin for Texas high school students. Conduct research in genetic engineering, bioinformatics, or pharmaceutical sciences. Laboratory immersion with daily research activities. Commuter and residential options available. Weekly seminars on biotechnology careers and graduate school. Research poster presentation. Financial aid for students from low-income families. Minimum 3.0 GPA required.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Biotechnology, Genetic Engineering, Bioinformatics, Pharmaceutical Sciences',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Variable',
                'cost_category': '$500-$1000',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'State',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Northwestern RISE Materials Science Research',
                'description': '7-week summer research program at Northwestern University focusing on materials science and nanotechnology. High school students work in cutting-edge research facilities on nanomaterials, polymers, or energy materials. Mentored by materials science faculty. Residential program in Evanston, IL. Clean room and advanced microscopy training. Research presentation at end of program. Competitive admissions. Financial aid available based on need.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Materials Science, Nanotechnology, Polymers, Energy Materials, Chemistry',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '7 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Duke RISE Environmental Science Research',
                'description': '6-week environmental science research program at Duke University for rising high school seniors. Conduct field and laboratory research on climate change, ecology, or environmental policy. Work with Duke faculty in Nicholas School of Environment. Mix of field work and data analysis. Residential program with housing and meals. Sustainability-focused curriculum. Research project on local or global environmental issue. Need-based scholarships available.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Environmental Science, Climate Change, Ecology, Environmental Policy, Sustainability',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'University of Illinois RISE Physics and Astronomy',
                'description': '8-week summer research program in physics and astronomy at University of Illinois Urbana-Champaign. High school students conduct research using observatory facilities or physics laboratories. Projects in astrophysics, particle physics, or condensed matter physics. Mentored by physics faculty and graduate students. Residential program. Weekly colloquia and lab tours. Produce research paper or poster. Financial aid available for Illinois residents.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Physics, Astronomy, Astrophysics, Particle Physics, Observatory Research',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '8 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Johns Hopkins RISE Neuroscience Research',
                'description': '7-week neuroscience research program at Johns Hopkins University for high school students passionate about brain science. Work in neuroscience laboratories studying cognition, behavior, or neurological diseases. Mentored by Johns Hopkins faculty and medical students. Residential program in Baltimore. Hospital and lab tours. Weekly seminars on neuroscience careers and medical school. Research presentation at program end. Need-based financial aid available.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Neuroscience, Brain Science, Cognitive Science, Neurobiology, Medical Research',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '7 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'February',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'University of Pennsylvania RISE Bioengineering',
                'description': '6-week bioengineering research program at UPenn for high school students interested in medical devices, tissue engineering, or computational biology. Work in Penn bioengineering laboratories on cutting-edge projects. Faculty mentorship and graduate student collaboration. Residential program in Philadelphia. Engineering design workshops and medical device demonstrations. Research poster at program end. Competitive admissions. Financial aid available.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Bioengineering, Medical Devices, Tissue Engineering, Computational Biology',
                'target_grade': '11-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '6 weeks',
                'prerequisite_level': 'High',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Rice University RISE Research Experience',
                'description': '7-week summer research program at Rice University for Texas and Louisiana high school students. Research in physical sciences, life sciences, or engineering. Small cohort with individualized mentorship from Rice faculty. Residential program in Houston. Weekly workshops on scientific writing, presentations, and college applications. Research symposium showcasing student work. Need-based financial aid reducing program costs. Focus on recruiting diverse student body.',
                'url': 'https://www.riseprograms.org/programs',
                'source': 'RISE Programs',
                'category': 'Research Opportunity',
                'stem_fields': 'Physical Sciences, Life Sciences, Engineering, Research Methods',
                'target_grade': '10-12',
                'cost': 'Paid',
                'location_type': 'In-person',
                'time_commitment': '7 weeks',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'March',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Available',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Housing-included',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'True',
                'internet_dependency': 'Medium',
                'regional_availability': 'Regional',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting RISE Research Programs scraping...")
        print("Note: Creating RISE research program resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating RISE program entries...")
        self.resources = self.create_rise_programs()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/rise_research.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = RISEResearchScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
