#!/usr/bin/env python3
"""
Roblox Education Learning Resources Scraper
Scrapes free coding and game design curriculum
Saves to: data/roblox_education.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class RobloxEducationScraper:
    def __init__(self):
        self.base_url = "https://education.roblox.com"
        self.target_urls = [
            "https://education.roblox.com/",
            "https://education.roblox.com/en-us/resources",
            "https://education.roblox.com/en-us/pathway",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_roblox_education_resources(self) -> List[Dict]:
        """Create Roblox Education learning resources."""
        resources = [
            {
                'name': 'Roblox Education - Introduction to Roblox Studio',
                'description': 'Beginner course teaching basics of Roblox Studio development environment. Learn interface navigation, building tools, terrain creation, and basic scripting. Create first 3D world and learn fundamental game development concepts.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Game Design, 3D Modeling',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Coding with Lua Fundamentals',
                'description': 'Learn Lua programming language fundamentals through Roblox Studio. Cover variables, data types, conditional statements, loops, functions, and debugging. Project-based approach creating interactive game elements.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Lua',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '6-10 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Game Design and Development Pathway',
                'description': 'Comprehensive learning pathway from beginner to advanced game creator. Multi-course curriculum covering design thinking, prototyping, player experience, monetization, and publishing. Build portfolio of completed games.',
                'url': 'https://education.roblox.com/en-us/pathway',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Game Design, Programming, Entrepreneurship',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '40-60 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - 3D Modeling and Environment Design',
                'description': 'Create 3D assets and immersive environments in Roblox Studio. Learn part manipulation, mesh importing, terrain tools, lighting, and visual effects. Build detailed worlds and game settings.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Game Design, 3D Modeling, Art, Design',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '4-8 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Creating an Obby (Obstacle Course)',
                'description': 'Popular project-based course building classic Roblox obstacle course game. Learn game mechanics, challenge design, checkpoints, spawning, and player testing. Complete functional game by end of course.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Game Design, Programming, Level Design',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '3-5 hours',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Scripting with Events and Functions',
                'description': 'Intermediate Lua scripting focusing on event-driven programming and function creation. Learn player input handling, collision detection, timers, and creating reusable code. Build interactive game mechanics.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Software Engineering',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '5-8 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - User Interface (UI) Design',
                'description': 'Design and script graphical user interfaces for Roblox games. Learn GUI objects, screen positioning, buttons, health bars, menus, and player feedback systems. Create polished user experiences.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, UI/UX Design, Programming',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '4-6 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Combat and Weapon Systems',
                'description': 'Create combat mechanics for action games. Learn health systems, damage calculation, weapon tools, projectiles, and combat balancing. Understand game balance and player engagement through combat design.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Game Design, Programming, Mathematics, Systems Thinking',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '6-10 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Multiplayer Game Development',
                'description': 'Learn server-client architecture and multiplayer game programming. Understand remote events, data persistence, player synchronization, and anti-cheat basics. Build games supporting multiple concurrent players.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Network Programming, Game Design',
                'target_grade': '8-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '8-12 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Data Stores and Player Progression',
                'description': 'Implement persistent data systems saving player progress across sessions. Learn DataStore service, data serialization, leaderboards, achievements, and player inventory systems. Create engaging progression mechanics.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Database Management, Programming',
                'target_grade': '8-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '5-8 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Monetization and Game Economics',
                'description': 'Learn ethical game monetization through Developer Products and Game Passes. Understand virtual economies, pricing strategies, player value, and sustainable business models. Introduction to game entrepreneurship.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Entrepreneurship, Economics, Game Design, Business',
                'target_grade': '8-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '3-5 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Animation and Character Rigging',
                'description': 'Create custom character animations and rigs in Roblox Studio. Learn animation editor, keyframes, easing styles, and character customization. Build unique character movements and emotes.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Animation, 3D Design, Art, Game Design',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '4-7 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Sound Design and Audio Programming',
                'description': 'Integrate sound effects and music into Roblox games. Learn audio properties, 3D spatial audio, background music systems, and triggering sounds through scripts. Create immersive audio experiences.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Game Design, Audio Engineering, Programming',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '3-5 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Game Testing and Optimization',
                'description': 'Learn professional game testing methodologies, performance optimization, and debugging strategies. Understand frame rate, memory management, and creating smooth player experiences across devices.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Software Engineering, Quality Assurance',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '4-6 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Publishing and Marketing Your Game',
                'description': 'Final steps in game development lifecycle: publishing, metadata optimization, thumbnail creation, description writing, and player acquisition strategies. Learn how to grow game audience.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Entrepreneurship, Marketing, Game Design',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Roblox Education - Educator Resources and Lesson Plans',
                'description': 'Free curriculum resources for teachers using Roblox Studio in classroom. Standards-aligned lesson plans, student worksheets, assessment rubrics, and classroom management guides. Support K-12 computer science education.',
                'url': 'https://education.roblox.com/en-us/resources',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science Education, Curriculum Development',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Roblox Education - Community and Developer Forum',
                'description': 'Access to global Roblox developer community and forums. Get help from experienced developers, share projects, participate in challenges, and learn from community tutorials. Peer-to-peer learning platform.',
                'url': 'https://education.roblox.com/',
                'source': 'Roblox Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Game Design, Community Learning',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'Peer'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Roblox Education scraping...")
        print("Note: Creating Roblox Education learning resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Roblox Education entries...")
        self.resources = self.create_roblox_education_resources()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/roblox_education.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = RobloxEducationScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
