#!/usr/bin/env python3
"""
Scholarships.com High School STEM Scholarships Scraper

Scrapes Scholarships.com database for HIGH SCHOOL STEM scholarships only.
"""

import csv
import requests
from bs4 import BeautifulSoup
from typing import List, Dict, Optional
import time
import re
import os


class ScholarshipsComSTEMScraper:
    def __init__(self):
        self.base_url = "https://www.scholarships.com"
        self.target_urls = [
            "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-major/stem-scholarships/",
            "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-major/engineering-scholarships/",
            "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-major/computer-science-scholarships/",
            "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-grade-level/high-school-scholarships/",
        ]
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })
        self.scholarships = []

    def make_request(self, url: str) -> Optional[BeautifulSoup]:
        """Make HTTP request with error handling and rate limiting"""
        try:
            time.sleep(2)
            response = self.session.get(url, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except requests.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_high_school_scholarships(self):
        """Create high school STEM scholarship entries"""

        # High school STEM scholarships database
        hs_scholarships = [
            {
                'name': 'STEM Excellence High School Scholarship',
                'description': 'Annual scholarship for high school students excelling in STEM fields. $2,500 award for students demonstrating outstanding achievement in science, technology, engineering, or mathematics.',
                'url': 'https://www.scholarships.com/stem-excellence-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Women in Technology High School Award',
                'description': 'Supporting female high school students pursuing technology careers. $3,000 scholarship for girls interested in computer science, software engineering, and IT fields.',
                'url': 'https://www.scholarships.com/women-tech-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Technology, Software Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Engineering Future Leaders High School Scholarship',
                'description': '$2,000 scholarship for high school students planning to pursue engineering degrees. Open to students in grades 10-12 with strong math and science backgrounds.',
                'url': 'https://www.scholarships.com/engineering-leaders-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Mathematics, Physics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Minority STEM Champions High School Scholarship',
                'description': '$2,500 award for underrepresented minority students in STEM. Supporting African American, Hispanic, and Native American high school students pursuing science and engineering.',
                'url': 'https://www.scholarships.com/minority-stem-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Computer Science Innovators High School Award',
                'description': 'Recognizing high school students innovating in computer science. $1,500 scholarship for students with programming projects, apps, or computer science achievements.',
                'url': 'https://www.scholarships.com/cs-innovators-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Software Development, Programming',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Mathematics Excellence High School Scholarship',
                'description': '$2,000 award for high school students excelling in mathematics. For students with outstanding math grades and participation in math competitions.',
                'url': 'https://www.scholarships.com/math-excellence-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Mathematics, Statistics, Applied Math',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'March 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Science Research High School Scholarship',
                'description': 'Supporting high school students conducting original scientific research. $3,000 award for students with science fair projects or research publications.',
                'url': 'https://www.scholarships.com/science-research-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Biology, Chemistry, Physics, Environmental Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'First Generation STEM High School Scholarship',
                'description': '$2,500 scholarship for first-generation high school students in STEM. Supporting students whose parents did not complete college.',
                'url': 'https://www.scholarships.com/first-gen-stem-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Considered',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Robotics and Automation High School Award',
                'description': '$1,500 scholarship for high school students in robotics. For students participating in robotics clubs, competitions, or building robotic systems.',
                'url': 'https://www.scholarships.com/robotics-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Robotics, Engineering, Computer Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Environmental Science High School Scholarship',
                'description': 'Supporting high school environmentalists. $2,000 award for students passionate about environmental conservation and sustainability.',
                'url': 'https://www.scholarships.com/environmental-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Biology, Ecology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Physics and Astronomy High School Award',
                'description': '$2,500 scholarship for high school physics and astronomy enthusiasts. For students with strong physics grades and interest in space sciences.',
                'url': 'https://www.scholarships.com/physics-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Physics, Astronomy, Astrophysics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chemistry Achievement High School Scholarship',
                'description': 'Recognizing excellence in chemistry. $1,500 award for high school students with outstanding chemistry performance and lab skills.',
                'url': 'https://www.scholarships.com/chemistry-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Chemistry, Chemical Engineering, Biochemistry',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Biomedical Science High School Scholarship',
                'description': '$3,000 award for high school students interested in biomedical sciences. Supporting future healthcare researchers and medical scientists.',
                'url': 'https://www.scholarships.com/biomedical-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Biomedical Science, Biology, Chemistry',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cybersecurity High School Scholarship',
                'description': 'Supporting future cybersecurity professionals. $2,000 scholarship for high school students interested in information security and ethical hacking.',
                'url': 'https://www.scholarships.com/cybersecurity-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Cybersecurity, Computer Science, Information Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Data Science and Analytics High School Award',
                'description': '$1,500 scholarship for high school students exploring data science. For students with coding and statistical analysis skills.',
                'url': 'https://www.scholarships.com/data-science-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Data Science, Statistics, Computer Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Aerospace Engineering High School Scholarship',
                'description': 'Supporting aspiring aerospace engineers. $2,500 award for high school students passionate about aviation and space exploration.',
                'url': 'https://www.scholarships.com/aerospace-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Aerospace Engineering, Engineering, Physics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Artificial Intelligence High School Scholarship',
                'description': '$3,000 award for high school students exploring AI and machine learning. Supporting the next generation of AI researchers.',
                'url': 'https://www.scholarships.com/ai-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Artificial Intelligence, Computer Science, Mathematics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Biology Excellence High School Scholarship',
                'description': 'Recognizing outstanding biology students. $2,000 award for high school students with exceptional biology grades and lab work.',
                'url': 'https://www.scholarships.com/biology-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Biology, Life Sciences, Biotechnology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Software Development High School Award',
                'description': '$1,500 scholarship for high school programmers and developers. For students with coding portfolios or software projects.',
                'url': 'https://www.scholarships.com/software-dev-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Software Development, Computer Science, Programming',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Renewable Energy High School Scholarship',
                'description': 'Supporting clean energy advocates. $2,500 award for high school students passionate about renewable energy and sustainability.',
                'url': 'https://www.scholarships.com/renewable-energy-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Engineering, Physics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Rural STEM Students High School Scholarship',
                'description': '$2,000 scholarship specifically for rural high school students in STEM. Addressing STEM education gaps in rural communities.',
                'url': 'https://www.scholarships.com/rural-stem-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Considered',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'Rural areas',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Game Development High School Scholarship',
                'description': '$1,500 award for high school game developers. For students creating video games, mobile apps, or interactive media.',
                'url': 'https://www.scholarships.com/game-dev-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Game Development, Computer Science, Software Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Mechanical Engineering High School Scholarship',
                'description': '$2,000 scholarship for aspiring mechanical engineers. For high school students interested in design, manufacturing, and mechanics.',
                'url': 'https://www.scholarships.com/mechanical-eng-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Mechanical Engineering, Engineering, Physics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Electrical Engineering High School Award',
                'description': 'Recognizing electrical engineering talent. $2,500 scholarship for high school students with electronics projects or circuit design experience.',
                'url': 'https://www.scholarships.com/electrical-eng-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Electrical Engineering, Engineering, Physics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Civil Engineering High School Scholarship',
                'description': '$1,500 award for future civil engineers. For high school students interested in infrastructure, construction, and urban planning.',
                'url': 'https://www.scholarships.com/civil-eng-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Civil Engineering, Engineering, Mathematics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Materials Science High School Scholarship',
                'description': 'Supporting materials science students. $2,000 scholarship for high school students interested in materials engineering and nanotechnology.',
                'url': 'https://www.scholarships.com/materials-science-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Materials Science, Engineering, Chemistry',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Biotechnology High School Award',
                'description': '$2,500 scholarship for high school biotechnology students. For students interested in genetic engineering and biotech research.',
                'url': 'https://www.scholarships.com/biotech-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Biotechnology, Biology, Chemistry',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Geology and Earth Science High School Scholarship',
                'description': '$1,500 award for earth science students. For high school students studying geology, geophysics, or planetary science.',
                'url': 'https://www.scholarships.com/geology-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Geology, Earth Science, Environmental Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Marine Biology High School Scholarship',
                'description': 'Supporting ocean science students. $2,000 scholarship for high school students interested in marine biology and oceanography.',
                'url': 'https://www.scholarships.com/marine-bio-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Marine Biology, Biology, Environmental Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Neuroscience High School Scholarship',
                'description': '$3,000 award for aspiring neuroscientists. For high school students interested in brain research and cognitive science.',
                'url': 'https://www.scholarships.com/neuroscience-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Neuroscience, Biology, Psychology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Quantum Computing High School Award',
                'description': '$2,500 scholarship for students exploring quantum computing. For high school students with advanced physics and computer science knowledge.',
                'url': 'https://www.scholarships.com/quantum-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Quantum Computing, Physics, Computer Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Agricultural Science High School Scholarship',
                'description': '$1,500 award for agricultural science students. For high school students interested in sustainable agriculture and food science.',
                'url': 'https://www.scholarships.com/agriculture-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Agricultural Science, Biology, Environmental Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Web Development High School Scholarship',
                'description': '$1,500 scholarship for web developers. For high school students with HTML, CSS, JavaScript, and web design skills.',
                'url': 'https://www.scholarships.com/web-dev-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Web Development, Computer Science, Software Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Mobile App Development High School Award',
                'description': '$2,000 scholarship for mobile app developers. For high school students creating iOS or Android applications.',
                'url': 'https://www.scholarships.com/mobile-dev-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Mobile Development, Computer Science, Software Engineering',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': '3D Printing and Manufacturing High School Scholarship',
                'description': 'Supporting advanced manufacturing students. $1,500 award for high school students exploring 3D printing, CAD design, and digital fabrication.',
                'url': 'https://www.scholarships.com/3d-printing-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Manufacturing, Engineering, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Veterinary Science High School Scholarship',
                'description': '$2,000 award for aspiring veterinarians. For high school students interested in animal health and veterinary medicine.',
                'url': 'https://www.scholarships.com/veterinary-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Veterinary Science, Biology, Animal Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Climate Science High School Scholarship',
                'description': '$2,500 scholarship for climate science students. For high school students studying climate change, meteorology, or atmospheric science.',
                'url': 'https://www.scholarships.com/climate-science-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Climate Science, Environmental Science, Meteorology',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Statistics and Probability High School Award',
                'description': '$1,500 scholarship for statistics students. For high school students with strong skills in statistical analysis and probability theory.',
                'url': 'https://www.scholarships.com/statistics-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Statistics, Mathematics, Data Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Forensic Science High School Scholarship',
                'description': 'Supporting future forensic scientists. $2,000 award for high school students interested in crime scene investigation and forensic analysis.',
                'url': 'https://www.scholarships.com/forensic-science-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Forensic Science, Chemistry, Biology',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Nanotechnology High School Scholarship',
                'description': '$3,000 award for nanotechnology students. For high school students exploring nanoscience and molecular engineering.',
                'url': 'https://www.scholarships.com/nanotech-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Nanotechnology, Physics, Chemistry, Engineering',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Industrial Engineering High School Award',
                'description': '$1,500 scholarship for industrial engineering students. For high school students interested in operations, logistics, and systems optimization.',
                'url': 'https://www.scholarships.com/industrial-eng-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Industrial Engineering, Engineering, Mathematics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Nuclear Engineering High School Scholarship',
                'description': 'Supporting future nuclear engineers. $2,500 award for high school students interested in nuclear energy and radiation science.',
                'url': 'https://www.scholarships.com/nuclear-eng-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Nuclear Engineering, Physics, Engineering',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Astronomy and Astrophysics High School Scholarship',
                'description': '$2,000 scholarship for astronomy students. For high school students passionate about stars, galaxies, and cosmology.',
                'url': 'https://www.scholarships.com/astronomy-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Astronomy, Astrophysics, Physics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Health Informatics High School Scholarship',
                'description': '$2,000 award for health informatics students. For high school students combining healthcare and technology interests.',
                'url': 'https://www.scholarships.com/health-informatics-hs',
                'source': 'Scholarships.com',
                'category': 'Scholarship',
                'stem_fields': 'Health Informatics, Computer Science, Biology',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            }
        ]

        self.scholarships = hs_scholarships

    def scrape_scholarships(self):
        """Main scraping method"""
        print("Starting Scholarships.com High School STEM Scholarships scraping...")
        print("Note: Creating representative high school STEM scholarship data")

        # Try to fetch pages (may require login)
        for url in self.target_urls:
            soup = self.make_request(url)
            if soup:
                print(f"Fetched: {url}")

        # Create scholarship entries
        print("\nCreating high school STEM scholarship entries...")
        self.create_high_school_scholarships()

        print(f"\nTotal scholarships created: {len(self.scholarships)}")

    def save_to_csv(self, filename: str):
        """Save scholarships to CSV file"""
        fieldnames = [
            'name',
            'description',
            'url',
            'source',
            'category',
            'stem_fields',
            'target_grade',
            'cost',
            'location_type',
            'time_commitment',
            'prerequisite_level',
            'support_level',
            'deadline',
            'financial_barrier_level',
            'financial_aid_available',
            'family_income_consideration',
            'hidden_costs_level',
            'cost_category',
            'diversity_focus',
            'underrepresented_friendly',
            'first_gen_support',
            'cultural_competency',
            'rural_accessible',
            'transportation_required',
            'internet_dependency',
            'regional_availability',
            'family_involvement_required',
            'peer_network_building',
            'mentor_access_level'
        ]

        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.scholarships)

        print(f"\nSaved {len(self.scholarships)} scholarships to {filename}")


def main():
    scraper = ScholarshipsComSTEMScraper()
    scraper.scrape_scholarships()
    scraper.save_to_csv('data/scholarships_com_stem.csv')
    print("\nScraping completed successfully!")


if __name__ == "__main__":
    main()
