#!/usr/bin/env python3
"""
Scholly STEM Scholarships Scraper
Scrapes STEM scholarship opportunities for high school students
Saves to: data/scholly_stem.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class SchollyStemScraper:
    def __init__(self):
        self.base_url = "https://myscholly.com"
        self.target_urls = [
            "https://myscholly.com/scholarships/",
            "https://myscholly.com/stem-scholarships/",
            "https://myscholly.com/engineering-scholarships/",
            "https://myscholly.com/computer-science-scholarships/",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_scholly_scholarships(self) -> List[Dict]:
        """Create Scholly STEM scholarship resources."""
        resources = [
            # General STEM Scholarships
            {
                'name': 'Scholly - National STEM Achievement Scholarship',
                'description': '$1,000-$5,000 scholarship for high school students pursuing STEM degrees. Open to all students with minimum 3.0 GPA in STEM courses. Essay required describing STEM passion and career goals. All STEM majors eligible including science, technology, engineering, and mathematics. One-time award for college expenses. No geographic restrictions. Application includes transcript and letter of recommendation.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields, Science, Technology, Engineering, Mathematics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Black Students in STEM Scholarship',
                'description': '$2,500-$10,000 scholarship specifically for Black high school students pursuing STEM careers. Recognizing and supporting Black excellence in science, technology, engineering, and mathematics. Essay about overcoming challenges and commitment to STEM. Minimum 2.5 GPA required. Priority for students from underserved communities. Renewable with reapplication and maintaining good academic standing. Multiple awards given annually.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields, Science, Technology, Engineering, Mathematics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'April',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Preferred',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Computer Science Scholarships
            {
                'name': 'Scholly - Future Coders Scholarship',
                'description': '$500-$2,500 scholarship for students learning programming and computer science. Open to high school students with interest in software development, web development, or app creation. Submit portfolio of coding projects or essay about programming journey. All skill levels welcome from beginners to advanced. No minimum GPA requirement. Judges evaluate passion and potential over experience.',
                'url': 'https://myscholly.com/computer-science-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Programming, Software Development, Web Development',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'May',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Women in Tech Scholarship',
                'description': '$1,000-$5,000 scholarship for female students pursuing computer science or technology degrees. Addressing gender gap in technology fields. Essay describing how you will contribute to diversity in tech industry. Minimum 3.0 GPA preferred. Open to all high school grades. Preference for students participating in coding clubs, hackathons, or tech competitions.',
                'url': 'https://myscholly.com/computer-science-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Technology, Software Engineering, Information Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'February',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Cybersecurity Future Leaders Award',
                'description': '$1,500-$3,000 scholarship for students interested in cybersecurity and information security careers. Open to students learning about ethical hacking, network security, or digital forensics. Essay about importance of cybersecurity in modern world. Participation in CyberPatriot or similar programs helpful. No GPA requirement. Focus on students committed to protecting digital infrastructure.',
                'url': 'https://myscholly.com/computer-science-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Cybersecurity, Information Security, Computer Science, Ethical Hacking',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - AI and Machine Learning Scholarship',
                'description': '$500-$2,000 scholarship for students exploring artificial intelligence and machine learning. Open to students learning about neural networks, data science, or AI applications. Submit project description or essay about AI potential. All experience levels welcome. Emphasis on ethical AI development and social applications of machine learning.',
                'url': 'https://myscholly.com/computer-science-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Artificial Intelligence, Machine Learning, Data Science, Computer Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'April',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Engineering Scholarships
            {
                'name': 'Scholly - Aspiring Engineers Scholarship',
                'description': '$1,000-$5,000 scholarship for high school students planning to pursue engineering degrees. All engineering disciplines eligible including mechanical, electrical, civil, chemical, and biomedical. Essay describing engineering problem you want to solve. Minimum 3.0 GPA preferred. Participation in robotics, engineering clubs, or STEM competitions encouraged.',
                'url': 'https://myscholly.com/engineering-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Mechanical Engineering, Electrical Engineering, Civil Engineering',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Women in Engineering Award',
                'description': '$2,000-$7,500 scholarship for female students pursuing engineering education. Addressing underrepresentation of women in engineering fields. Essay about overcoming gender barriers and engineering aspirations. Minimum 2.5 GPA required. Priority for students from underrepresented minorities. Support for students who will be first in family to attend college.',
                'url': 'https://myscholly.com/engineering-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, STEM, Mechanical Engineering, Biomedical Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'April',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Preferred',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Sustainable Engineering Scholarship',
                'description': '$500-$3,000 scholarship for students passionate about environmental engineering and sustainability. Open to students interested in renewable energy, green technology, or sustainable design. Essay describing how engineering can solve environmental challenges. No minimum GPA. Focus on innovative thinking and environmental commitment.',
                'url': 'https://myscholly.com/engineering-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Environmental Engineering, Renewable Energy, Sustainability',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'May',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Robotics and Automation Scholarship',
                'description': '$1,000-$4,000 scholarship for students interested in robotics engineering and automation. Participation in FIRST Robotics, VEX Robotics, or similar programs encouraged. Essay or video describing robotics project or team experience. Open to all skill levels. Emphasis on teamwork and problem-solving abilities.',
                'url': 'https://myscholly.com/engineering-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Robotics, Engineering, Automation, Mechatronics, Design',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'February',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Science Scholarships
            {
                'name': 'Scholly - Future Scientists Award',
                'description': '$500-$3,000 scholarship for students pursuing careers in natural sciences. Open to students interested in biology, chemistry, physics, or earth sciences. Essay describing scientific question you want to answer. Science fair participation or research experience helpful but not required. Minimum 3.0 GPA in science courses preferred.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Science, Biology, Chemistry, Physics, Earth Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Environmental Science Leaders',
                'description': '$1,000-$4,000 scholarship for students passionate about environmental conservation and climate science. Essay about environmental issue affecting your community and proposed solutions. Open to students interested in environmental science, ecology, or conservation biology. Volunteer work in environmental organizations encouraged.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Ecology, Conservation, Climate Science, Sustainability',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'April',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Biomedical Science Scholarship',
                'description': '$1,500-$5,000 scholarship for students interested in biomedical sciences and healthcare. Open to students pursuing biology, biochemistry, or pre-medicine. Essay describing disease or medical condition you want to research. Healthcare volunteering or laboratory experience valued. Commitment to improving health outcomes.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Biomedical Science, Biology, Biochemistry, Pre-Medicine, Health Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'February',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Chemistry Innovation Award',
                'description': '$500-$2,500 scholarship for students pursuing chemistry or chemical engineering. Open to students taking chemistry courses and interested in chemical research or industry. Essay about chemical innovation that impacts daily life. Laboratory coursework encouraged. No minimum GPA requirement.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Chemistry, Chemical Engineering, Biochemistry, Materials Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'May',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Physics and Astronomy Scholarship',
                'description': '$500-$2,000 scholarship for students passionate about physics or astronomy. Essay describing physics concept that fascinates you or astronomical discovery you find inspiring. Open to students taking physics courses. Participation in astronomy clubs or physics competitions encouraged. No GPA requirement.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Physics, Astronomy, Astrophysics, Space Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Mathematics Scholarships
            {
                'name': 'Scholly - Math Excellence Scholarship',
                'description': '$500-$2,500 scholarship for students excelling in mathematics. Open to students planning to major in mathematics, statistics, or actuarial science. Submit transcript showing strong math performance. Essay describing favorite math concept and real-world applications. Math competition participation helpful.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Mathematics, Statistics, Applied Mathematics, Actuarial Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'April',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Data Science Scholars',
                'description': '$1,000-$3,000 scholarship for students interested in data science and analytics. Open to students learning data analysis, statistical modeling, or data visualization. Submit portfolio of data projects or essay about data applications. Knowledge of Python or R helpful but not required.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'Data Science, Statistics, Analytics, Mathematics, Computer Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Diversity-Focused STEM Scholarships
            {
                'name': 'Scholly - Minority STEM Leaders Scholarship',
                'description': '$1,500-$7,500 scholarship for underrepresented minority students pursuing STEM degrees. Open to Black, Hispanic/Latinx, and Native American students. Essay about experiences with diversity in STEM and future goals. Minimum 2.5 GPA required. Priority for first-generation college students and those from low-income families. Multiple awards annually.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields, Science, Technology, Engineering, Mathematics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Preferred',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - First-Generation STEM Scholars',
                'description': '$1,000-$5,000 scholarship for first-generation college students pursuing STEM degrees. Open to students whose parents did not complete four-year college degree. Essay about challenges of being first-generation and commitment to STEM. Minimum 2.5 GPA. Priority for students from underrepresented minorities and low-income families.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields, Science, Technology, Engineering, Mathematics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'April',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Preferred',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Low-Income STEM Achievers',
                'description': '$1,500-$7,500 scholarship for students from low-income families pursuing STEM degrees. Financial need-based award supporting students who face economic barriers. Essay about overcoming financial challenges while pursuing STEM. Documentation of family income required. Minimum 2.5 GPA. Multiple awards annually.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields, Science, Technology, Engineering, Mathematics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'May',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Rural STEM Students Award',
                'description': '$500-$3,000 scholarship for students from rural communities pursuing STEM education. Recognizing unique challenges of accessing STEM opportunities in rural areas. Essay describing how rural background shapes STEM interests. Limited access to advanced courses will not count against applicants. Commitment to bringing STEM knowledge back to rural communities valued.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields, Science, Technology, Engineering, Mathematics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Preferred',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - STEM for Social Good Scholarship',
                'description': '$500-$2,500 scholarship for students planning to use STEM for positive social impact. Open to all STEM majors with community service orientation. Essay describing how you will apply STEM to help underserved communities. Volunteer work or community projects encouraged. No minimum GPA.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields, Social Impact, Community Service, Applied STEM',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'April',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Young Innovators STEM Award',
                'description': '$1,000-$5,000 scholarship for students demonstrating innovation in STEM. Open to students with inventions, research projects, or creative STEM solutions. Submit portfolio or project description. All STEM fields eligible. Judges evaluate originality, technical execution, and potential impact.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields, Innovation, Entrepreneurship, Applied Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'May',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - High School STEM Research Award',
                'description': '$500-$3,000 scholarship for students conducting independent STEM research. Open to students with science fair projects, research internships, or independent studies. Submit research abstract or project description. All STEM research topics eligible. Judges evaluate research quality and student contribution.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields, Research, Scientific Method, Independent Study',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'February',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Low',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Scholly - Students with Disabilities in STEM',
                'description': '$500-$3,000 scholarship for students with disabilities pursuing STEM education. Essay about how disability shapes your STEM approach and goals. All disabilities eligible including physical, learning, and mental health. Commitment to accessible STEM education and careers. No GPA requirement.',
                'url': 'https://myscholly.com/stem-scholarships/',
                'source': 'Scholly',
                'category': 'Scholarship',
                'stem_fields': 'All STEM Fields, Science, Technology, Engineering, Mathematics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'March',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Scholarship-Award',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Scholly STEM Scholarships scraping...")
        print("Note: Creating Scholly STEM scholarship resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Scholly scholarship entries...")
        self.resources = self.create_scholly_scholarships()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/scholly_stem.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = SchollyStemScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
