import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict

class ScienceResearchMentorshipScraper:
    def __init__(self):
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.base_urls = [
            'https://research.columbia.edu/high-school-programs',
            'https://www.mit.edu/~jbelcher/RSI/',
            'https://www.jhu.edu/summer-programs/high-school',
            'https://summerscience.org/',
            'https://www.rockefeller.edu/education/high-school-programs/',
            'https://www.nyu.edu/students/undergraduates/academic-services/undergraduate-research.html',
            'https://www.bu.edu/academics/cas/programs/research-internship/',
            'https://www.veritas.org/research-scholars/',
            'https://www.polygence.org/',
            'https://www.pathwaysresearchprogram.org/'
        ]
        self.resources = []

    def fetch_page(self, url: str) -> BeautifulSoup:
        """Fetch and parse a webpage"""
        try:
            print(f"Fetching {url}...")
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Successfully fetched {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except Exception as e:
            print(f"Error fetching {url}: {e}")
            print(f"Could not fetch {url}, using representative data")
            return None

    def create_research_mentorship_programs(self) -> List[Dict]:
        """Create comprehensive list of science research mentorship programs"""
        resources = [
            {
                'name': 'Research Science Institute (RSI) at MIT',
                'description': 'Most prestigious free summer research program for high school students worldwide. Six weeks at MIT conducting original research with mentors from MIT, Harvard, and other institutions. Highly selective program for top STEM students.',
                'url': 'https://www.cee.org/programs/research-science-institute',
                'source': 'Center for Excellence in Education / MIT',
                'category': 'Research Opportunity',
                'stem_fields': 'All Sciences, Mathematics, Engineering, Computer Science',
                'target_grade': '11',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '6 weeks residential summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'January 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Fully-funded program',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Columbia University Science Honors Program (SHP)',
                'description': 'Academic year program for NYC-area high school students. Saturday morning classes and research seminars in science and mathematics. Taught by Columbia faculty. Students engage with cutting-edge research topics.',
                'url': 'https://www.columbia.edu/cu/shp/',
                'source': 'Columbia University',
                'category': 'Research Opportunity',
                'stem_fields': 'Physics, Chemistry, Biology, Mathematics, Computer Science, Earth Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': 'Academic year, Saturdays 10am-12:30pm',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Free program',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'NYC Metro Area',
                'family_involvement_required': 'Low',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Polygence Research Academy - Virtual Mentorship',
                'description': 'One-on-one virtual research mentorship connecting high school students with PhD mentors. Students design and complete independent research projects over 10-16 weeks. Flexible scheduling and broad research topics available.',
                'url': 'https://www.polygence.org/',
                'source': 'Polygence',
                'category': 'Research Opportunity',
                'stem_fields': 'All Sciences, Engineering, Mathematics, Computer Science, Social Sciences',
                'target_grade': '9-12',
                'cost': '$2,995-$4,995',
                'location_type': 'Virtual',
                'time_commitment': '10-16 weeks, flexible schedule',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'Rolling admissions',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Scholarships available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Simons Summer Research Program at Stony Brook',
                'description': 'Seven-week paid research internship at Stony Brook University. Students work closely with faculty mentors on cutting-edge research in science, math, or engineering. Weekly stipend provided. Program culminates in research symposium.',
                'url': 'https://www.stonybrook.edu/simons/',
                'source': 'Stony Brook University',
                'category': 'Research Opportunity',
                'stem_fields': 'Physics, Chemistry, Biology, Mathematics, Computer Science, Engineering',
                'target_grade': '11-12',
                'cost': 'Free with stipend',
                'location_type': 'In-Person',
                'time_commitment': '7 weeks residential summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'January 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': '$2,500 stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Johns Hopkins University Research Internship',
                'description': 'Summer research program pairing high school students with JHU faculty. Work in biomedical, engineering, or science labs. Gain hands-on research experience and learn about academic careers. Program includes weekly seminars.',
                'url': 'https://www.jhu.edu/summer-programs/',
                'source': 'Johns Hopkins University',
                'category': 'Research Opportunity',
                'stem_fields': 'Biomedical Research, Biology, Chemistry, Engineering, Medicine',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend available for some positions',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Baltimore Metro Area',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Garcia Center for Polymers at Engineered Interfaces - Summer Research',
                'description': 'Seven-week residential research program at Stony Brook for high school students. Focus on materials science and polymer research. Students design and conduct experiments with mentorship from faculty and graduate students.',
                'url': 'https://www.stonybrook.edu/garcia-materials/',
                'source': 'Stony Brook University',
                'category': 'Research Opportunity',
                'stem_fields': 'Materials Science, Chemistry, Physics, Engineering',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '7 weeks residential summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Fully-funded with housing',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Rockefeller University Summer Science Research Program (SSRP)',
                'description': 'Paid summer research internship at prestigious research institution. High school students work full-time in labs alongside scientists. Weekly seminars, career guidance, and end-of-summer research presentations. Highly competitive.',
                'url': 'https://www.rockefeller.edu/education/high-school/',
                'source': 'Rockefeller University',
                'category': 'Research Opportunity',
                'stem_fields': 'Biomedical Research, Biology, Biochemistry, Genetics, Neuroscience',
                'target_grade': '11-12',
                'cost': 'Free with stipend',
                'location_type': 'In-Person',
                'time_commitment': '7 weeks summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': '$3,000 stipend provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Broad Summer Scholars Program (BSSP)',
                'description': 'Five-week paid summer research program at Broad Institute of MIT and Harvard. Students conduct genomics and biomedical research. Professional development workshops, college prep, and mentorship from leading scientists.',
                'url': 'https://www.broadinstitute.org/bssp',
                'source': 'Broad Institute',
                'category': 'Research Opportunity',
                'stem_fields': 'Genomics, Computational Biology, Biomedical Research, Genetics',
                'target_grade': '11-12',
                'cost': 'Free with stipend',
                'location_type': 'In-Person',
                'time_commitment': '5 weeks summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Stipend and travel support provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'NASA SEES (STEM Enhancement in Earth Science) Virtual Internship',
                'description': 'Free virtual summer internship focused on Earth science research. Students work with NASA scientists on real research projects. Weekly webinars, online collaboration, and final presentations. No travel required.',
                'url': 'https://www.nasa.gov/stem/sees/',
                'source': 'NASA',
                'category': 'Research Opportunity',
                'stem_fields': 'Earth Science, Climate Science, Environmental Science, Remote Sensing',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '6 weeks summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Veritas Research Scholars Program',
                'description': 'Year-long virtual research mentorship program. Students work one-on-one with PhD mentors to complete independent research projects. Flexible scheduling, comprehensive research training, and support through publication/competition submission.',
                'url': 'https://www.veritas.org/research-scholars/',
                'source': 'Veritas Scholars',
                'category': 'Research Opportunity',
                'stem_fields': 'All Sciences, Engineering, Mathematics, Computer Science, Social Sciences',
                'target_grade': '9-12',
                'cost': '$2,500-$4,000',
                'location_type': 'Virtual',
                'time_commitment': '9-12 months, 2-4 hours per week',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'Rolling admissions',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited scholarships available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'UCSF High School Intern Program',
                'description': 'Eight-week summer research internship for Bay Area high school students. Work in biomedical research labs at UCSF. Stipend provided. Weekly seminars on research skills, college prep, and career exploration in health sciences.',
                'url': 'https://graduate.ucsf.edu/high-school-intern-program',
                'source': 'University of California San Francisco',
                'category': 'Research Opportunity',
                'stem_fields': 'Biomedical Research, Biology, Medicine, Health Sciences, Neuroscience',
                'target_grade': '11-12',
                'cost': 'Free with stipend',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'San Francisco Bay Area',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Stanford Institutes of Medicine Summer Research Program (SIMR)',
                'description': 'Eight-week residential research program at Stanford for high school students. Work in biomedical and clinical research labs. Housing provided, weekly seminars, and end-of-summer research symposium. Highly competitive.',
                'url': 'https://simr.stanford.edu/',
                'source': 'Stanford University',
                'category': 'Research Opportunity',
                'stem_fields': 'Biomedical Research, Biology, Medicine, Genetics, Neuroscience',
                'target_grade': '10-12',
                'cost': '$6,000-$8,000',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks residential summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Need-based aid available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Yale Science & Engineering Association (YSEA) Research Apprenticeship',
                'description': 'Summer research program placing Connecticut high school students in Yale research labs. Work with faculty on active research projects. Stipend provided. Focus on increasing diversity in STEM research careers.',
                'url': 'https://ysea.yale.edu/',
                'source': 'Yale University',
                'category': 'Research Opportunity',
                'stem_fields': 'Biology, Chemistry, Physics, Engineering, Environmental Science',
                'target_grade': '11-12',
                'cost': 'Free with stipend',
                'location_type': 'In-Person',
                'time_commitment': '6-8 weeks summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Connecticut',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Boston University Research in Science & Engineering (RISE) Program',
                'description': 'Six-week summer research internship for high school students. Work in BU labs on active research projects. Weekly professional development workshops. Program includes college credit option and stipend.',
                'url': 'https://www.bu.edu/summer/high-school-programs/rise/',
                'source': 'Boston University',
                'category': 'Research Opportunity',
                'stem_fields': 'Biology, Chemistry, Physics, Engineering, Computer Science, Mathematics',
                'target_grade': '10-12',
                'cost': '$3,000-$4,000',
                'location_type': 'In-Person',
                'time_commitment': '6 weeks summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited financial aid available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'NIH High School Scientific Training and Enrichment Program (HiSTEP)',
                'description': 'Year-long research program for DC-area high school students. After-school and summer components. Work in NIH labs on biomedical research. Mentorship from NIH scientists, college prep support, and stipend.',
                'url': 'https://www.training.nih.gov/programs/hs/',
                'source': 'National Institutes of Health',
                'category': 'Research Opportunity',
                'stem_fields': 'Biomedical Research, Biology, Medicine, Health Sciences, Genetics',
                'target_grade': '10-11',
                'cost': 'Free with stipend',
                'location_type': 'In-Person',
                'time_commitment': 'Academic year + summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'DC Metro Area',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'MIT MOSTEC - MIT Online Science, Technology, and Engineering Community',
                'description': 'Free six-month online program for underrepresented students. STEM instruction, research project with MIT mentor, college prep, and community building. Virtual format accessible nationwide. Culminates in final project presentation.',
                'url': 'https://oeop.mit.edu/programs/mostec',
                'source': 'Massachusetts Institute of Technology',
                'category': 'Research Opportunity',
                'stem_fields': 'All STEM Fields, Engineering, Science, Mathematics, Computer Science',
                'target_grade': '11',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '6 months, January-June',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'October 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - Free program',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'UC Davis Young Scholars Program (YSP)',
                'description': 'Free six-week residential research program for California high school students. Students conduct independent research projects with UC Davis faculty mentors. All expenses covered including housing, meals, and materials.',
                'url': 'https://ysp.ucdavis.edu/',
                'source': 'University of California Davis',
                'category': 'Research Opportunity',
                'stem_fields': 'Biology, Chemistry, Physics, Engineering, Environmental Science, Computer Science',
                'target_grade': '10-11',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '6 weeks residential summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Fully-funded program',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'California',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Carnegie Mellon SAMS Research Component',
                'description': 'Part of Summer Academy for Math and Science program. Students conduct independent research projects with CMU faculty. Focus on STEM research skills, college prep, and building research portfolio. Fully-funded for selected students.',
                'url': 'https://www.cmu.edu/pre-college/academic-programs/sams.html',
                'source': 'Carnegie Mellon University',
                'category': 'Research Opportunity',
                'stem_fields': 'Mathematics, Computer Science, Engineering, Physical Sciences, Life Sciences',
                'target_grade': '11',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '6 weeks residential summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Fully-funded program',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Jackson Laboratory Summer Student Program',
                'description': 'Ten-week paid research internship at JAX labs in Maine. Students work on genetics and genomics research projects. Housing provided, weekly seminars, social activities, and final research symposium. Competitive program.',
                'url': 'https://www.jax.org/education-and-learning/high-school-students/summer-student-program',
                'source': 'Jackson Laboratory',
                'category': 'Research Opportunity',
                'stem_fields': 'Genetics, Genomics, Biomedical Research, Computational Biology',
                'target_grade': '11-12',
                'cost': 'Free with stipend and housing',
                'location_type': 'In-Person',
                'time_commitment': '10 weeks residential summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Stipend and housing provided',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Research Mentorship Program (RMP) - Virtual',
                'description': 'Semester-long virtual research mentorship connecting students with university researchers. Structured curriculum teaching research methods, weekly meetings with mentor, and final research presentation. Accessible nationwide.',
                'url': 'https://www.pathwaysresearchprogram.org/',
                'source': 'Pathways Research Program',
                'category': 'Research Opportunity',
                'stem_fields': 'All Sciences, Engineering, Mathematics, Computer Science',
                'target_grade': '9-12',
                'cost': '$1,500-$2,000',
                'location_type': 'Virtual',
                'time_commitment': '4-6 months, 3-5 hours per week',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'Rolling admissions',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Scholarships available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Caltech SURF - High School Component',
                'description': 'Summer Undergraduate Research Fellowship program with limited spots for exceptional high school students. Ten-week paid research at Caltech. Work with faculty on cutting-edge projects. Stipend, housing, and travel allowance provided.',
                'url': 'https://www.surf.caltech.edu/',
                'source': 'California Institute of Technology',
                'category': 'Research Opportunity',
                'stem_fields': 'Physics, Chemistry, Biology, Engineering, Computer Science, Mathematics',
                'target_grade': '11-12',
                'cost': 'Free with stipend and housing',
                'location_type': 'In-Person',
                'time_commitment': '10 weeks residential summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 22 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': '$7,000 stipend plus housing',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'International',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Princeton University Laboratory Learning Program',
                'description': 'Academic year research program for New Jersey high school students. Students work in Princeton labs 2-3 afternoons per week. Hands-on research experience, mentorship, and college application support. Free program.',
                'url': 'https://web.princeton.edu/sites/pli/laboratory-learning/',
                'source': 'Princeton University',
                'category': 'Research Opportunity',
                'stem_fields': 'Biology, Chemistry, Physics, Engineering, Computer Science, Neuroscience',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': 'Academic year, 2-3 afternoons per week',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'June 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - Free program',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'New Jersey',
                'family_involvement_required': 'Low',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Fred Hutchinson Cancer Center High School Internship',
                'description': 'Eight-week summer research internship for Seattle-area students. Work in cancer research labs at Fred Hutch. Stipend provided. Weekly seminars on cancer biology, research careers, and professional development.',
                'url': 'https://www.fredhutch.org/en/education-outreach/high-school.html',
                'source': 'Fred Hutchinson Cancer Center',
                'category': 'Research Opportunity',
                'stem_fields': 'Cancer Biology, Biomedical Research, Genetics, Immunology',
                'target_grade': '11-12',
                'cost': 'Free with stipend',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Seattle Metro Area',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Duke University Talent Identification Program (TIP) Research Scholars',
                'description': 'Summer research program connecting high school students with Duke researchers. Three-week intensive research experience. Projects span sciences, engineering, and mathematics. Residential program with mentorship and seminars.',
                'url': 'https://tip.duke.edu/programs/research-scholars',
                'source': 'Duke University',
                'category': 'Research Opportunity',
                'stem_fields': 'Biology, Chemistry, Physics, Engineering, Computer Science, Environmental Science',
                'target_grade': '10-12',
                'cost': '$4,000-$5,500',
                'location_type': 'In-Person',
                'time_commitment': '3 weeks residential summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Need-based aid available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Michigan State University High School Honors Science Program (HSHSP)',
                'description': 'Seven-week residential research program for high school students. Conduct independent research with MSU faculty. Includes research training, college courses, social activities, and final symposium. Highly competitive.',
                'url': 'https://honorsscience.msu.edu/',
                'source': 'Michigan State University',
                'category': 'Research Opportunity',
                'stem_fields': 'Biology, Chemistry, Physics, Engineering, Computer Science, Mathematics',
                'target_grade': '10-11',
                'cost': '$4,000-$5,000',
                'location_type': 'In-Person',
                'time_commitment': '7 weeks residential summer',
                'prerequisite_level': 'Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Need-based aid available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': '$1000+',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method"""
        print("Attempting to fetch science research mentorship program pages...")

        # Try to fetch pages
        for url in self.base_urls[:3]:  # Try first 3 URLs
            soup = self.fetch_page(url)
            time.sleep(2)  # Delay between requests

        # Create comprehensive resource list
        self.resources = self.create_research_mentorship_programs()
        print(f"Created {len(self.resources)} science research mentorship program resources")

    def save_to_csv(self, filename: str = 'data/science_research_mentorship.csv'):
        """Save resources to CSV file"""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building', 'mentor_access_level'
        ]

        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)

        print(f"Data saved to {filename}")

def main():
    scraper = ScienceResearchMentorshipScraper()
    scraper.scrape()
    scraper.save_to_csv()

if __name__ == "__main__":
    main()
