#!/usr/bin/env python3
"""
Sphero Education K-12 STEAM Programs Scraper
Scrapes K-12 robotics and coding programs from Sphero Education
Saves to: data/sphero_education.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class SpheroEducationScraper:
    def __init__(self):
        self.base_url = "https://sphero.com"
        self.target_urls = [
            "https://sphero.com/pages/education",
            "https://sphero.com/collections/all-education",
            "https://edu.sphero.com/",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_sphero_education_resources(self) -> List[Dict]:
        """Create Sphero Education K-12 STEAM resources."""
        resources = [
            # Sphero Robot Programs
            {
                'name': 'Sphero BOLT Coding Activities',
                'description': 'Learn coding with Sphero BOLT programmable robot. Block-based and JavaScript coding lessons for middle school. LED matrix programming, sensors, and advanced robotics.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Coding, Engineering, Computer Science',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero Mini Edu Elementary Coding',
                'description': 'Introduction to coding for elementary students using Sphero Mini robot. Face-drive, block coding, and simple programming concepts through play-based learning.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Coding, Computer Science',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero RVR Robot Programming',
                'description': 'Advanced robotics with Sphero RVR programmable robot. Python, JavaScript, Scratch, and sensor programming for high school. Build autonomous vehicles and custom projects.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Engineering, Programming, Computer Science',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero SPRK+ STEAM Lessons',
                'description': 'STEAM curriculum for middle school using Sphero SPRK+ robot. Cross-curricular activities integrating art, math, science, and coding.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Curriculum',
                'stem_fields': 'Robotics, Coding, Art, Mathematics, Science',
                'target_grade': '5-8',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Sphero Edu App Resources
            {
                'name': 'Sphero Edu App - Beginner Activities',
                'description': 'Free beginner coding activities in Sphero Edu app. Draw mode, block coding, and text coding progressions. No robot required for some activities.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Coding, Programming',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '30-60 minutes per activity',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Optional Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Sphero Edu App - JavaScript Programming',
                'description': 'Learn JavaScript programming through Sphero Edu app. Text-based coding for advanced students. Includes API documentation and project examples.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, JavaScript',
                'target_grade': '8-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            # littleBits (now Sphero) Resources
            {
                'name': 'littleBits Electronic Building Kits for Kids',
                'description': 'Magnetic electronic building blocks for K-8. Learn circuits, electronics, and invention through snap-together modules. STEAM activities and invention challenges.',
                'url': 'https://sphero.com/pages/education',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Engineering, Invention, STEAM',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'littleBits Code Kit Programming',
                'description': 'Learn coding and electronics together with littleBits Code Kit. Block-based programming for physical computing projects. Sensors, motors, and outputs.',
                'url': 'https://sphero.com/pages/education',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Coding, Engineering, Physical Computing',
                'target_grade': '3-8',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Curriculum and Lesson Plans
            {
                'name': 'Sphero Computer Science Foundations Course',
                'description': 'Complete computer science curriculum for middle school. Sequencing, loops, functions, variables, and algorithms using Sphero robots. Standards-aligned lessons.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Curriculum',
                'stem_fields': 'Computer Science, Programming, Algorithms',
                'target_grade': '6-8',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '12-16 weeks',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero STEAM Lesson Library',
                'description': 'Library of cross-curricular STEAM lessons using Sphero robots. Math, science, art, and social studies integration. Teacher guides and student worksheets.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Curriculum',
                'stem_fields': 'STEAM, Mathematics, Science, Art, Engineering',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero Physics Lab Activities',
                'description': 'Physics experiments using Sphero robots as data collection tools. Measure speed, acceleration, force, and angles. Graphing and data analysis.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Science, Mathematics, Data Science',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-2 hours per lab',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero Math Maze Activities',
                'description': 'Mathematics practice through maze navigation. Geometry, measurement, angles, and problem-solving. Sphero robots navigate mathematical challenges.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Geometry, Problem Solving',
                'target_grade': '3-8',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '30-60 minutes per activity',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Challenges and Projects
            {
                'name': 'Sphero Robotics Design Challenges',
                'description': 'Engineering design challenges using Sphero robots. Build accessories, create games, solve real-world problems. Collaborative project-based learning.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Engineering, Robotics, Design, Problem Solving',
                'target_grade': '4-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-5 hours per challenge',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware-Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero Art and Animation Projects',
                'description': 'Create art using Sphero robots. Light painting, drawing with robots, programmed art installations. STEAM integration of technology and creativity.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Art, Technology, Programming, STEAM',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-3 hours per project',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware-Art Supplies',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero Storytelling and Narrative Coding',
                'description': 'Create interactive stories by programming Sphero robots. Combine literacy, creativity, and coding. Character development and plot sequences.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Coding, Literacy, Creativity, STEAM',
                'target_grade': '2-8',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 hours per project',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Advanced Programming
            {
                'name': 'Sphero Python Programming Course',
                'description': 'Learn Python programming using Sphero RVR robot. Text-based coding for advanced students. Real-world programming applications and sensor integration.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Python, Programming, Robotics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '12-16 weeks',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero Sensor Programming and Data Science',
                'description': 'Advanced robotics using Sphero sensors. Collect environmental data, analyze trends, build data-driven applications. STEM integration.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Data Science, Robotics, Programming, Science',
                'target_grade': '8-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Teacher Professional Development
            {
                'name': 'Sphero Teacher Training and Certification',
                'description': 'Free professional development for educators. Learn to integrate Sphero robots into curriculum. Best practices, classroom management, and lesson planning.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Professional Development',
                'stem_fields': 'STEAM Education, Teaching, Curriculum',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'Sphero Classroom Setup and Implementation Guide',
                'description': 'Resources for implementing Sphero robotics in classrooms. Device management, student grouping strategies, assessment tools, and troubleshooting.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Professional Development',
                'stem_fields': 'STEAM Education, Teaching',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'Professional'
            },
            # Special Programs
            {
                'name': 'Sphero Star Wars Droid Coding',
                'description': 'Learn coding through Star Wars-themed activities. Program BB-8, R2-D2, and other Star Wars droids. Engaging introduction to robotics for all ages.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Coding, Programming',
                'target_grade': '2-8',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero indi Early Learning Robot',
                'description': 'Screen-free coding robot for early elementary. Color-based programming, problem-solving, and computational thinking without screens. Ages 4-7.',
                'url': 'https://sphero.com/pages/education',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Coding, Problem Solving, Computational Thinking',
                'target_grade': 'PreK-2',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'None',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Competition and Community
            {
                'name': 'Sphero Global Challenge Competition',
                'description': 'Annual robotics competition for students worldwide. Design challenges, coding competitions, and creative projects. Virtual and in-person events.',
                'url': 'https://sphero.com/pages/education',
                'source': 'Sphero Education',
                'category': 'Competition',
                'stem_fields': 'Robotics, Engineering, Coding, Design',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Competition season',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Annual',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero Community Projects and Sharing',
                'description': 'Online community for sharing Sphero projects and programs. Learn from other educators and students. Collaborative coding and project galleries.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Coding, Robotics, Community Learning',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Optional Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Community'
            },
            # Standards-Aligned Courses
            {
                'name': 'Sphero NGSS Science Curriculum',
                'description': 'Next Generation Science Standards-aligned activities. Use Sphero robots to teach science concepts, conduct experiments, and collect data.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Curriculum',
                'stem_fields': 'Science, Physics, Engineering, Data Science',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero CSTA Computer Science Standards Pathway',
                'description': 'CSTA standards-aligned computer science curriculum. Progressive learning pathway from K-12. Covers all CS concepts using Sphero robots.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Curriculum',
                'stem_fields': 'Computer Science, Programming, Algorithms',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Home Learning
            {
                'name': 'Sphero At-Home Learning Activities',
                'description': 'Activities designed for home learning and parent engagement. No teacher required. Self-guided lessons for families learning together.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'STEAM, Coding, Robotics',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Home',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Sphero Parent and Educator Resources',
                'description': 'Guides for parents and educators new to robotics. Setup instructions, activity ideas, troubleshooting, and learning progression recommendations.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'STEAM Education, Robotics',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Accessibility and Inclusion
            {
                'name': 'Sphero Accessible Coding Features',
                'description': 'Accessibility features in Sphero robots and apps. Voice commands, screen readers, switch control, and adaptive programming for students with disabilities.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Accessibility, Inclusive Design',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Sphero Multilingual Learning Resources',
                'description': 'Sphero Edu app and resources available in multiple languages. Global accessibility for non-English speaking students and international classrooms.',
                'url': 'https://edu.sphero.com/',
                'source': 'Sphero Education',
                'category': 'Learning Platform',
                'stem_fields': 'STEAM, Coding, Robotics',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Hardware',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Sphero Education scraping...")
        print("Note: Creating Sphero Education K-12 STEAM resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Sphero Education entries...")
        self.resources = self.create_sphero_education_resources()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/sphero_education.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = SpheroEducationScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
