#!/usr/bin/env python3
"""
SplashLearn Elementary Math and Reading Platform Scraper
Scrapes game-based learning for PreK-5
Saves to: data/splashlearn.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class SplashLearnScraper:
    def __init__(self):
        self.base_url = "https://www.splashlearn.com"
        self.target_urls = [
            "https://www.splashlearn.com/",
            "https://www.splashlearn.com/math",
            "https://www.splashlearn.com/ela",
            "https://www.splashlearn.com/parents",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_splashlearn_programs(self) -> List[Dict]:
        """Create SplashLearn grade/subject programs."""
        resources = [
            # Math by grade
            {
                'name': 'SplashLearn Math - Pre-Kindergarten',
                'description': 'Game-based PreK math program covering counting 1-10, number recognition, basic shapes, colors, patterns, and comparisons. Interactive games and activities designed for early learners. Free and premium content available.',
                'url': 'https://www.splashlearn.com/math/preschool',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Early Math, Counting',
                'target_grade': 'PreK',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Math - Kindergarten',
                'description': 'Kindergarten math games covering counting to 20, addition and subtraction basics, place value, measurement, shapes, and data. Aligned to Common Core standards with engaging characters and rewards.',
                'url': 'https://www.splashlearn.com/math/kindergarten',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Arithmetic, Geometry',
                'target_grade': 'K',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Math - 1st Grade',
                'description': 'First grade math curriculum with 350+ games. Addition and subtraction within 20, place value to 100, measurement, time, money, and geometry. Personalized learning paths adapt to student progress.',
                'url': 'https://www.splashlearn.com/math/grade-1',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Addition, Subtraction, Place Value',
                'target_grade': '1',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Math - 2nd Grade',
                'description': 'Second grade math with 400+ interactive games. Addition and subtraction within 100, place value to 1000, multiplication foundations, measurement, time, money, and data. Real-time progress tracking.',
                'url': 'https://www.splashlearn.com/math/grade-2',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Multiplication, Place Value, Measurement',
                'target_grade': '2',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Math - 3rd Grade',
                'description': 'Third grade math featuring 450+ games. Multiplication and division, fractions, area and perimeter, time, measurement, and data analysis. Adaptive difficulty adjusts to student mastery level.',
                'url': 'https://www.splashlearn.com/math/grade-3',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Multiplication, Division, Fractions',
                'target_grade': '3',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Math - 4th Grade',
                'description': 'Fourth grade math with 500+ engaging games. Multi-digit multiplication and division, fractions and decimals, measurement conversions, geometry, and data interpretation. Standards-aligned curriculum.',
                'url': 'https://www.splashlearn.com/math/grade-4',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Fractions, Decimals, Geometry',
                'target_grade': '4',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Math - 5th Grade',
                'description': 'Fifth grade math curriculum with 550+ games. Decimal operations, fraction operations, volume, coordinate planes, and algebraic thinking. Prepares students for middle school mathematics.',
                'url': 'https://www.splashlearn.com/math/grade-5',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Decimals, Fractions, Algebra Basics',
                'target_grade': '5',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Reading/ELA by grade
            {
                'name': 'SplashLearn Reading - Pre-Kindergarten',
                'description': 'PreK reading program introducing letter recognition, phonics basics, sight words, and pre-reading skills. Interactive stories and activities build early literacy foundation through play.',
                'url': 'https://www.splashlearn.com/ela/preschool',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Reading, Literacy, Phonics',
                'target_grade': 'PreK',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Reading - Kindergarten',
                'description': 'Kindergarten reading curriculum with phonics, sight words, letter sounds, simple sentences, and reading comprehension. Engaging stories and games develop foundational reading skills.',
                'url': 'https://www.splashlearn.com/ela/kindergarten',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Reading, Phonics, Literacy, Sight Words',
                'target_grade': 'K',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Reading - 1st Grade',
                'description': 'First grade reading program covering phonics rules, sight words, vocabulary development, reading fluency, and comprehension strategies. Interactive leveled readers with comprehension questions.',
                'url': 'https://www.splashlearn.com/ela/grade-1',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Reading, Phonics, Comprehension, Vocabulary',
                'target_grade': '1',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Reading - 2nd Grade',
                'description': 'Second grade reading with advanced phonics, vocabulary expansion, reading comprehension, and writing basics. Diverse texts including fiction, nonfiction, and poetry with skill-building activities.',
                'url': 'https://www.splashlearn.com/ela/grade-2',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Reading, Comprehension, Vocabulary, Writing',
                'target_grade': '2',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Reading - 3rd Grade',
                'description': 'Third grade reading focusing on fluency, comprehension strategies, literary analysis, vocabulary development, and grammar. Complex texts with higher-level thinking questions.',
                'url': 'https://www.splashlearn.com/ela/grade-3',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Reading, Comprehension, Grammar, Literary Analysis',
                'target_grade': '3',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Parent Dashboard',
                'description': 'Comprehensive parent dashboard with real-time progress tracking, skill mastery reports, time spent learning, and personalized recommendations. Monitor child learning and identify areas for improvement.',
                'url': 'https://www.splashlearn.com/parents',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Educational Technology, Parent Engagement',
                'target_grade': 'PreK-5',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'SplashLearn Rewards and Motivation System',
                'description': 'Gamification features with virtual coins, pet customization, rewards, and achievement badges. Motivate children to practice regularly through engaging game mechanics and personalized avatars.',
                'url': 'https://www.splashlearn.com/',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Educational Gamification, Motivation',
                'target_grade': 'PreK-5',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SplashLearn Adaptive Learning Engine',
                'description': 'AI-powered adaptive learning technology that personalizes difficulty, pacing, and content based on individual student performance. Identifies knowledge gaps and provides targeted practice for mastery.',
                'url': 'https://www.splashlearn.com/',
                'source': 'SplashLearn',
                'category': 'Learning Platform',
                'stem_fields': 'Educational Technology, Adaptive Learning, AI',
                'target_grade': 'PreK-5',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting SplashLearn scraping...")
        print("Note: Creating SplashLearn grade/subject programs")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating SplashLearn entries...")
        self.resources = self.create_splashlearn_programs()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/splashlearn.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = SplashLearnScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
