#!/usr/bin/env python3
"""
STEMfinity K-12 STEM Resources Scraper
Scrapes K-12 STEM educational resources and programs
Saves to: data/stemfinity.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class STEMfinityScraper:
    def __init__(self):
        self.base_url = "https://www.stemfinity.com"
        self.target_urls = [
            "https://www.stemfinity.com/",
            "https://www.stemfinity.com/STEM-Education",
            "https://www.stemfinity.com/Free-STEM-Activities",
            "https://www.stemfinity.com/STEM-Competitions",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_stemfinity_resources(self) -> List[Dict]:
        """Create STEMfinity K-12 STEM resources."""
        resources = [
            # Free STEM Activities
            {
                'name': 'STEMfinity Free Elementary Science Activities',
                'description': 'Collection of free hands-on science activities for elementary grades. Includes experiments in physics, chemistry, biology, and earth science with minimal materials.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Physics, Chemistry, Biology',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '30-60 minutes per activity',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Household Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'STEMfinity Free Middle School STEM Challenges',
                'description': 'Engineering design challenges and STEM projects for middle school students. Downloadable activities covering robotics, coding, engineering, and mathematics.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Engineering, Robotics, Programming, Mathematics',
                'target_grade': '6-8',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-2 hours per challenge',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Basic Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'STEMfinity Free High School STEM Labs',
                'description': 'Advanced STEM laboratory activities for high school. Physics, chemistry, biology, and engineering labs with detailed procedures and analysis questions.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Science, Physics, Chemistry, Biology, Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-3 hours per lab',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Lab Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Robotics Resources
            {
                'name': 'STEMfinity LEGO Education Resources',
                'description': 'Comprehensive LEGO robotics curriculum guides, lesson plans, and competition resources. Support for LEGO WeDo and EV3 platforms for all grade levels.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Curriculum',
                'stem_fields': 'Robotics, Engineering, Programming',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'None',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity VEX Robotics Curriculum',
                'description': 'VEX robotics lesson plans and project guides for middle and high school. Competition prep materials and engineering notebooks templates.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Curriculum',
                'stem_fields': 'Robotics, Engineering, Programming',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'None',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Arduino Education Materials',
                'description': 'Arduino project guides and coding tutorials for students. Learn electronics, sensors, and microcontroller programming through hands-on projects.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Programming, Engineering',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 hours per project',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Variable'
            },
            # Competition Resources
            {
                'name': 'STEMfinity FIRST Robotics Competition Prep',
                'description': 'Resources for teams preparing for FIRST robotics competitions. Strategy guides, engineering tips, and project management tools for FLL, FTC, and FRC.',
                'url': 'https://www.stemfinity.com/STEM-Competitions',
                'source': 'STEMfinity',
                'category': 'Competition',
                'stem_fields': 'Robotics, Engineering, Programming',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Season-long',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Competition seasons',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Equipment-Travel',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'Variable',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Science Fair Project Resources',
                'description': 'Complete science fair project guides from topic selection through presentation. Includes research methods, experimental design, and display tips for all grade levels.',
                'url': 'https://www.stemfinity.com/STEM-Competitions',
                'source': 'STEMfinity',
                'category': 'Competition',
                'stem_fields': 'Science, Engineering, Research',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '4-12 weeks',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'School fair dates',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Project Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Math Competition Prep',
                'description': 'Practice problems and study guides for math competitions including MATHCOUNTS, AMC 8/10/12. Problem-solving strategies and competition tips.',
                'url': 'https://www.stemfinity.com/STEM-Competitions',
                'source': 'STEMfinity',
                'category': 'Competition',
                'stem_fields': 'Mathematics, Problem Solving',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Competition dates',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Competition Fees',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Coding Resources
            {
                'name': 'STEMfinity Python Programming for Beginners',
                'description': 'Introductory Python programming lessons and projects for middle and high school students. Learn variables, loops, functions, and data structures.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Python',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'STEMfinity Scratch Coding Activities',
                'description': 'Block-based coding projects using Scratch for elementary and middle school. Create games, animations, and interactive stories while learning programming concepts.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Game Design',
                'target_grade': '2-8',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '30-90 minutes per project',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'STEMfinity Web Development Basics',
                'description': 'Learn HTML, CSS, and JavaScript to build websites. Step-by-step tutorials for creating responsive web pages and interactive features.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Web Development, Computer Science, Programming',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            # Engineering Resources
            {
                'name': 'STEMfinity Engineering Design Process Guide',
                'description': 'Complete guide to the engineering design process for K-12. Templates, worksheets, and examples for defining problems, brainstorming, prototyping, and testing.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Curriculum',
                'stem_fields': 'Engineering, Design, Problem Solving',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Basic Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Bridge Building Challenge',
                'description': 'Structural engineering challenge where students design and build bridges using everyday materials. Includes load testing and optimization activities.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Engineering, Physics, Design',
                'target_grade': '4-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Household Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Rocketry Projects',
                'description': 'Design, build, and launch model rockets. Learn about aerodynamics, propulsion, and flight stability through hands-on aerospace engineering.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Aerospace, Engineering, Physics',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 hours',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Rocket Kit',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Science Resources
            {
                'name': 'STEMfinity Physics Labs and Experiments',
                'description': 'Collection of physics experiments covering motion, forces, energy, electricity, and magnetism. Suitable for middle and high school with minimal equipment.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Science',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-2 hours per lab',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Household Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Chemistry Experiments',
                'description': 'Safe chemistry experiments and demonstrations for all grade levels. Learn about reactions, states of matter, acids and bases using household items.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Chemistry, Science',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '30-90 minutes per experiment',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Household Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Biology and Life Science Activities',
                'description': 'Hands-on biology activities including dissections, cell models, genetics simulations, and ecosystem studies. Age-appropriate for all grade levels.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Biology, Life Science',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-3 hours per activity',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Basic Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Earth Science and Geology',
                'description': 'Earth science activities covering rocks and minerals, weather, climate, plate tectonics, and space. Includes virtual simulations and hands-on experiments.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Earth Science, Geology, Meteorology',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-2 hours per activity',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Household Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Math Resources
            {
                'name': 'STEMfinity Elementary Math Games and Activities',
                'description': 'Fun math activities for elementary students covering number sense, operations, geometry, and measurement. Hands-on games and manipulatives.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '20-45 minutes per activity',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Household Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Algebra Problem Sets',
                'description': 'Algebra practice problems with detailed solutions. Topics include equations, inequalities, functions, and graphing for middle and high school.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Algebra',
                'target_grade': '7-10',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'STEMfinity Geometry Projects',
                'description': 'Hands-on geometry projects and explorations. Learn about shapes, angles, transformations, and proofs through construction and visualization.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Geometry',
                'target_grade': '6-10',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-2 hours per project',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Basic Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Statistics and Data Analysis',
                'description': 'Learn statistics through real-world data analysis projects. Topics include data collection, graphs, measures of center, and probability.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Statistics, Data Science',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 hours per project',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Maker and Technology
            {
                'name': 'STEMfinity 3D Printing Projects',
                'description': 'Introduction to 3D design and printing. Learn Tinkercad and other CAD software to create models for 3D printing. Project files and tutorials included.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, Technology, Engineering',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 hours per project',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': '3D Printer Access',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Variable'
            },
            {
                'name': 'STEMfinity Maker Projects and Crafts',
                'description': 'Creative maker projects combining art, engineering, and technology. Build electronic greeting cards, LED projects, and simple circuits.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Engineering, Electronics, Art',
                'target_grade': '3-8',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '1-3 hours per project',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Craft Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Variable'
            },
            {
                'name': 'STEMfinity Drone Technology Basics',
                'description': 'Introduction to drones, flight principles, and programming. Learn about aeronautics, sensors, and autonomous flight for middle and high school.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Aerospace, Programming',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Drone Equipment',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Teacher Resources
            {
                'name': 'STEMfinity Teacher Curriculum Guides',
                'description': 'Comprehensive curriculum guides for K-12 STEM teachers. Lesson plans, standards alignment, assessment tools, and classroom management strategies.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Professional Development',
                'stem_fields': 'STEM Education, Curriculum',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'STEMfinity STEM Classroom Setup Guide',
                'description': 'Resources for setting up STEM classrooms, makerspaces, and robotics labs. Equipment recommendations, layout ideas, and budget planning.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Professional Development',
                'stem_fields': 'STEM Education, Teaching',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'STEMfinity Grant Writing Resources',
                'description': 'Guide to finding and applying for STEM education grants. Sample proposals, tips for success, and database of funding opportunities for schools.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Professional Development',
                'stem_fields': 'STEM Education, Funding',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Grant deadlines',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'Professional'
            },
            # Environmental/Green STEM
            {
                'name': 'STEMfinity Renewable Energy Projects',
                'description': 'Hands-on projects exploring solar, wind, and hydroelectric power. Build working models and learn about sustainable energy solutions.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Environmental Science, Engineering, Energy',
                'target_grade': '4-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-4 hours per project',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Basic Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Environmental Engineering Challenges',
                'description': 'Design solutions to environmental problems like water filtration, pollution reduction, and habitat restoration. Real-world engineering challenges.',
                'url': 'https://www.stemfinity.com/Free-STEM-Activities',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Environmental Engineering, Science, Design',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 hours per challenge',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Household Materials',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'STEMfinity Climate Science Education',
                'description': 'Learn about climate change, greenhouse effect, and environmental impact through data analysis and modeling activities.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'Environmental Science, Climate Science, Data Science',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            # Career Exploration
            {
                'name': 'STEMfinity STEM Career Exploration',
                'description': 'Explore diverse STEM careers through videos, interviews, and virtual job shadowing. Learn about education pathways and career opportunities.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'STEM Careers, Career Exploration',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'STEMfinity Women in STEM Profiles',
                'description': 'Profiles of women scientists, engineers, and technologists. Inspiring stories and career paths to encourage girls in STEM fields.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'STEM Careers, Diversity',
                'target_grade': '4-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-directed',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Professional'
            },
            {
                'name': 'STEMfinity Diversity in STEM Resources',
                'description': 'Resources highlighting contributions of underrepresented groups in STEM. Biographical content, discussion guides, and inclusive teaching practices.',
                'url': 'https://www.stemfinity.com/STEM-Education',
                'source': 'STEMfinity',
                'category': 'Learning Platform',
                'stem_fields': 'STEM Education, Diversity, Inclusion',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'None',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting STEMfinity scraping...")
        print("Note: Creating STEMfinity K-12 STEM resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating STEMfinity entries...")
        self.resources = self.create_stemfinity_resources()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/stemfinity.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = STEMfinityScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
