"""
Society of Women Engineers High School Programs Scraper
Scrapes SWE scholarships, camps, competitions for girls in engineering
"""

import csv
import requests
from bs4 import BeautifulSoup
import time
from typing import List, Dict
import os

class SWEHighSchoolScraper:
    def __init__(self):
        self.base_url = "https://swe.org"
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> BeautifulSoup:
        """Fetch and parse a webpage"""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except Exception as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_swe_programs(self) -> List[Dict]:
        """Create comprehensive list of SWE high school programs and scholarships"""
        resources = [
            {
                'name': 'SWE - High School Scholarship Program',
                'description': 'Annual scholarship for female high school seniors planning to pursue ABET-accredited engineering programs. Awards range from $1,000-$5,000 based on academic achievement, leadership, and commitment to engineering. Multiple scholarships available.',
                'url': 'https://swe.org/scholarships/high-school/',
                'source': 'Society of Women Engineers',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Technology, Computer Engineering',
                'target_grade': '12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours application',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SWE - SWENext Club Program',
                'description': 'Year-round club program for middle and high school girls interested in engineering. Clubs meet regularly to explore engineering through projects, guest speakers, field trips, and competitions. Access to SWE mentors and resources.',
                'url': 'https://alltogether.swe.org/swenext/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, Technology, All Engineering Fields',
                'target_grade': '6-12',
                'cost': 'Free with school sponsorship',
                'location_type': 'In-Person',
                'time_commitment': 'Monthly meetings throughout school year',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Rolling - clubs can start anytime',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Engineering Design Competition for High School',
                'description': 'Annual engineering design competition where teams of high school girls solve real-world engineering challenges. Teams design, build, and present solutions. Includes mentorship from professional engineers and cash prizes.',
                'url': 'https://swe.org/k-12-outreach/competitions/',
                'source': 'Society of Women Engineers',
                'category': 'Competition',
                'stem_fields': 'Engineering, Design, Problem Solving, All Engineering Fields',
                'target_grade': '9-12',
                'cost': 'Free to enter',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 months project development',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Materials grants available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Summer Engineering Camp for Girls',
                'description': 'Week-long residential summer camp for high school girls to explore engineering fields. Hands-on projects, lab tours, college campus visits, and mentorship from women engineers. Includes all meals and housing.',
                'url': 'https://swe.org/k-12-outreach/summer-camps/',
                'source': 'Society of Women Engineers',
                'category': 'Camp',
                'stem_fields': 'Engineering, Technology, All Engineering Disciplines',
                'target_grade': '9-11',
                'cost': '$500-$800',
                'location_type': 'In-Person',
                'time_commitment': '1 week residential summer',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Scholarships available based on need',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$500-$1000',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Multiple university locations',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Collegiate Section Mentorship Program for HS Students',
                'description': 'Mentorship program connecting high school girls with women engineering students and professionals. Monthly meetings, career guidance, college prep support, and networking opportunities.',
                'url': 'https://swe.org/membership/collegiate-mentorship/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, Career Development, All Engineering Fields',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Monthly meetings during school year',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'September 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Varies',
                'internet_dependency': 'Moderate',
                'regional_availability': 'Regions with SWE collegiate sections',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - WE Local Conference High School Track',
                'description': 'Day-long conference for high school girls at regional SWE conferences. Attend workshops, hear from women engineers, participate in hands-on activities, and network with role models.',
                'url': 'https://we-local.swe.org/high-school-track/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, Technology, Professional Development',
                'target_grade': '9-12',
                'cost': '$25-$50 registration',
                'location_type': 'In-Person',
                'time_commitment': '1 day',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Varies by conference location',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Fee waivers available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$50-$100',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Multiple cities nationwide',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Engineering Exploration Day',
                'description': 'Free one-day event for middle and high school girls to explore engineering through hands-on activities, lab tours, and interactions with women engineers. Hosted at universities and companies nationwide.',
                'url': 'https://swe.org/k-12-outreach/exploration-days/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, Technology, All Engineering Fields',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '4-6 hours',
                'prerequisite_level': 'Beginner',
                'support_level': 'Moderate',
                'deadline': 'Registration typically 2 weeks prior',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Multiple locations nationwide',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'SWE - Invent It. Build It. Competition',
                'description': 'National competition for high school teams to invent and build engineering solutions to societal challenges. Teams receive mentorship, present at regional events, and winners compete nationally.',
                'url': 'https://swe.org/k-12-outreach/invent-it-build-it/',
                'source': 'Society of Women Engineers',
                'category': 'Competition',
                'stem_fields': 'Engineering, Innovation, Design, Problem Solving',
                'target_grade': '9-12',
                'cost': 'Free to enter',
                'location_type': 'Hybrid',
                'time_commitment': '4-6 months',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Materials stipends provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional for finals',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Virtual Career Exploration Series for High School',
                'description': 'Monthly virtual events featuring women engineers from various industries. Learn about engineering careers, ask questions, and explore different engineering paths. Free and accessible nationwide.',
                'url': 'https://swe.org/k-12-outreach/virtual-career-series/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, Career Exploration, All Engineering Fields',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '1 hour monthly sessions',
                'prerequisite_level': 'Beginner',
                'support_level': 'Moderate',
                'deadline': 'No deadline - ongoing program',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National - Virtual',
                'family_involvement_required': 'No',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'SWE - Engineering Leadership Institute for High School Girls',
                'description': 'Multi-day residential program focused on engineering leadership skills for high school girls. Workshops on teamwork, communication, project management, and engineering ethics. Includes college prep guidance.',
                'url': 'https://swe.org/k-12-outreach/leadership-institute/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, Leadership, Professional Development',
                'target_grade': '10-12',
                'cost': '$600-$900',
                'location_type': 'In-Person',
                'time_commitment': '3-5 days residential summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 31 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Need-based scholarships available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': '$500-$1000',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Hosted at universities',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - College Preparation Workshops for Engineering',
                'description': 'Series of workshops helping high school girls prepare for engineering college applications. Topics include essay writing, college selection, financial aid, and scholarship applications.',
                'url': 'https://swe.org/k-12-outreach/college-prep/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, College Preparation, Career Planning',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '2-3 workshops, 2 hours each',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Fall and spring sessions',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Varies',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Engineering Innovation Showcase',
                'description': 'Annual showcase where high school girls present engineering projects to judges, peers, and industry professionals. Opportunity to demonstrate skills, receive feedback, and win recognition awards.',
                'url': 'https://swe.org/k-12-outreach/innovation-showcase/',
                'source': 'Society of Women Engineers',
                'category': 'Competition',
                'stem_fields': 'Engineering, Innovation, All Engineering Fields',
                'target_grade': '9-12',
                'cost': 'Free to participate',
                'location_type': 'Hybrid',
                'time_commitment': '3-6 months project development',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Project support available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'SWE - Women of Color in Engineering Scholarship',
                'description': '$2,500 scholarship specifically for Black, Hispanic, and Native American female high school seniors pursuing engineering. Emphasizes diversity and inclusion in engineering fields.',
                'url': 'https://swe.org/scholarships/women-of-color/',
                'source': 'Society of Women Engineers',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, All Engineering Disciplines',
                'target_grade': '12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours application',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Low',
                'mentor_access_level': 'None'
            },
            {
                'name': 'SWE - First Generation Scholar in Engineering Program',
                'description': '$3,000 scholarship and mentorship program for first-generation college-bound female students pursuing engineering. Includes year-long mentorship from SWE professional members.',
                'url': 'https://swe.org/scholarships/first-generation/',
                'source': 'Society of Women Engineers',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, All Engineering Fields',
                'target_grade': '12',
                'cost': 'Free to apply',
                'location_type': 'Virtual',
                'time_commitment': '1-2 hours application, ongoing mentorship',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A - This is financial aid',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Engineering Ambassador Program for High School',
                'description': 'Program training high school girls to become engineering ambassadors in their communities. Lead outreach, organize events, and inspire younger students. Includes leadership training and SWE certification.',
                'url': 'https://swe.org/k-12-outreach/ambassador-program/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, Leadership, Outreach',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': 'Flexible, minimum 20 hours per year',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'September 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Varies',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Code It! Programming Competition for Girls',
                'description': 'Programming competition for high school girls to solve coding challenges and build software projects. Beginner and advanced divisions. Includes workshops and mentorship from women software engineers.',
                'url': 'https://swe.org/k-12-outreach/code-it/',
                'source': 'Society of Women Engineers',
                'category': 'Competition',
                'stem_fields': 'Computer Engineering, Software Engineering, Programming, Computer Science',
                'target_grade': '9-12',
                'cost': 'Free to enter',
                'location_type': 'Virtual',
                'time_commitment': '2-3 months',
                'prerequisite_level': 'Beginner-Advanced',
                'support_level': 'High',
                'deadline': 'January 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National - Virtual',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Engineering Internship Connection Program',
                'description': 'Program connecting high school girls with summer engineering internships at companies and research labs. Application support, interview prep, and mentor matching included.',
                'url': 'https://swe.org/k-12-outreach/internship-connection/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, All Engineering Fields, Technology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': 'Summer internships 6-10 weeks',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'January 31 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Most internships are paid',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Varies by internship location',
                'family_involvement_required': 'No',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - STEM Outreach Volunteer Leadership Program',
                'description': 'High school girls organize and lead STEM outreach activities for elementary and middle school students. Develop leadership skills while promoting engineering to younger girls.',
                'url': 'https://swe.org/k-12-outreach/volunteer-leadership/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, STEM Education, Leadership',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': 'Flexible, 5-10 hours per month',
                'prerequisite_level': 'Beginner',
                'support_level': 'Moderate',
                'deadline': 'Rolling admissions',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Local communities',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Moderate'
            },
            {
                'name': 'SWE - Engineering for Social Good Challenge',
                'description': 'Competition where high school teams develop engineering solutions to address social issues like clean water, renewable energy, or healthcare access. Winning teams receive funding to implement projects.',
                'url': 'https://swe.org/k-12-outreach/social-good-challenge/',
                'source': 'Society of Women Engineers',
                'category': 'Competition',
                'stem_fields': 'Engineering, Social Innovation, Sustainable Design',
                'target_grade': '9-12',
                'cost': 'Free to enter',
                'location_type': 'Hybrid',
                'time_commitment': '4-6 months',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Project implementation grants for winners',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Optional',
                'internet_dependency': 'Moderate',
                'regional_availability': 'National',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Engineering Portfolio Development Workshop',
                'description': 'Workshop series teaching high school girls to build professional engineering portfolios showcasing projects, skills, and achievements. Includes resume writing, GitHub setup, and presentation skills.',
                'url': 'https://swe.org/k-12-outreach/portfolio-workshop/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, Professional Development, Portfolio Building',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '4 sessions, 2 hours each',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'Multiple sessions throughout year',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National - Virtual',
                'family_involvement_required': 'No',
                'peer_network_building': 'Moderate',
                'mentor_access_level': 'High'
            },
            {
                'name': 'SWE - Annual Conference High School Registration',
                'description': 'Discounted registration for high school girls to attend the annual SWE Conference, largest conference for women in engineering. Access to career fair, workshops, and networking with 15,000+ attendees.',
                'url': 'https://we.swe.org/high-school/',
                'source': 'Society of Women Engineers',
                'category': 'Program',
                'stem_fields': 'Engineering, Career Development, All Engineering Fields',
                'target_grade': '9-12',
                'cost': '$100-$150 discounted registration',
                'location_type': 'In-Person',
                'time_commitment': '3-4 days',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'September 1 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Need-based scholarships available',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'High',
                'cost_category': '$100-$500',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Annual location varies',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            }
        ]
        return resources

    def scrape(self) -> List[Dict]:
        """Main scraping method"""
        print("Attempting to fetch SWE high school program pages...")

        # Try to fetch SWE pages
        urls_to_try = [
            "https://swe.org/scholarships/",
            "https://alltogether.swe.org/",
            "https://swe.org/k-12-outreach/"
        ]

        for url in urls_to_try:
            soup = self.fetch_page(url)
            if soup:
                print(f"Successfully fetched {url}")
                time.sleep(2)
            else:
                print(f"Could not fetch {url}, using representative data")

        # Create comprehensive SWE program resources
        self.resources = self.create_swe_programs()
        print(f"Created {len(self.resources)} SWE high school program resources")

        return self.resources

    def save_to_csv(self, filename: str):
        """Save scraped data to CSV file"""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]

        # Create data directory if it doesn't exist
        os.makedirs('data', exist_ok=True)

        filepath = os.path.join('data', filename)
        with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)

        print(f"Data saved to {filepath}")
        return filepath

def main():
    scraper = SWEHighSchoolScraper()
    scraper.scrape()
    scraper.save_to_csv('swe_high_school.csv')

if __name__ == "__main__":
    main()
