"""
Technology Internships for High School Students Scraper
Scrapes tech company internship programs for high school students (Google, Microsoft, Amazon, etc.)
"""

import csv
import requests
from bs4 import BeautifulSoup
import time
from typing import List, Dict
import os

class TechInternshipsHSScraper:
    def __init__(self):
        self.base_urls = [
            "https://buildyourfuture.withgoogle.com",
            "https://www.microsoft.com/en-us/diversity",
            "https://www.amazonfutureengineer.com"
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> BeautifulSoup:
        """Fetch and parse a webpage"""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except Exception as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_tech_internships(self) -> List[Dict]:
        """Create comprehensive list of tech internships for high school students"""
        resources = [
            {
                'name': 'Google Computer Science Summer Institute (CSSI)',
                'description': 'Intensive 4-week summer program for graduating high school seniors interested in computer science. Students learn programming fundamentals, build projects, and connect with Google engineers. Program includes hands-on coding, group projects, and exposure to industry professionals. Fully funded with stipend.',
                'url': 'https://buildyourfuture.withgoogle.com/programs/computer-science-summer-institute',
                'source': 'Google',
                'category': 'Internship',
                'stem_fields': 'Computer Science, Software Engineering, Programming',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '4 weeks full-time summer',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Fully funded with stipend',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Varies by location',
                'internet_dependency': 'High',
                'regional_availability': 'National - Multiple locations',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Microsoft High School Discovery Program',
                'description': 'Week-long workshop for high school students to explore computer science and technology careers at Microsoft. Students participate in coding workshops, meet Microsoft engineers, tour facilities, and work on technology projects. Focus on students from underrepresented communities.',
                'url': 'https://www.microsoft.com/en-us/diversity/programs/high-school-discovery',
                'source': 'Microsoft',
                'category': 'Internship',
                'stem_fields': 'Computer Science, Software Engineering, Technology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '1 week summer',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Travel and accommodation provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Redmond, WA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Amazon Future Engineer Summer Internship',
                'description': 'Paid summer internship for high school students interested in software engineering and computer science. Students work on real Amazon projects, receive mentorship from Amazon engineers, and participate in professional development workshops. Stipend provided.',
                'url': 'https://www.amazonfutureengineer.com/summer-internship',
                'source': 'Amazon',
                'category': 'Internship',
                'stem_fields': 'Software Engineering, Computer Science, Cloud Computing',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'January 31 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Paid internship with housing stipend',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Seattle, WA and other locations',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Meta University for High School Students',
                'description': 'Engineering-focused program for high school students from underrepresented communities. Students learn software engineering fundamentals, work on projects, and receive mentorship from Meta engineers. Program includes technical training and career development.',
                'url': 'https://www.metacareers.com/careerprograms/pathways/metauniversity',
                'source': 'Meta (Facebook)',
                'category': 'Internship',
                'stem_fields': 'Software Engineering, Computer Science, Mobile Development',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '6 weeks part-time',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National - Virtual',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Apple Pathways Alliance Program',
                'description': 'Year-round program for high school students from underrepresented communities interested in technology careers. Includes summer internship component where students work on real Apple projects, receive mentorship, and participate in professional development workshops.',
                'url': 'https://www.apple.com/jobs/us/pathways-alliance.html',
                'source': 'Apple',
                'category': 'Internship',
                'stem_fields': 'Software Engineering, Hardware Engineering, Computer Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '10 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Paid internship',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Cupertino, CA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'IBM Accelerate Program for High School',
                'description': 'Virtual 8-week summer program teaching high school students professional software development skills. Students learn agile methodology, design thinking, and build projects using IBM technologies. Includes mentorship from IBM professionals.',
                'url': 'https://www.ibm.com/employment/accelerate.html',
                'source': 'IBM',
                'category': 'Internship',
                'stem_fields': 'Software Development, Computer Science, Data Science, AI',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '8 weeks part-time summer',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'April 1 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National - Virtual',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Salesforce Futureforce Tech Launchpad',
                'description': 'Multi-week program for high school students exploring software engineering and technology careers. Students learn coding, participate in workshops, and work on projects. Strong focus on students from underrepresented backgrounds in tech.',
                'url': 'https://www.salesforce.com/company/careers/futureforce/tech-launchpad/',
                'source': 'Salesforce',
                'category': 'Internship',
                'stem_fields': 'Software Engineering, Cloud Computing, Computer Science',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '4 weeks summer',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'March 31 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Varies',
                'internet_dependency': 'High',
                'regional_availability': 'San Francisco, CA and virtual',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Intel Student Honor Research Program',
                'description': 'Research internship for high school students interested in computer science, engineering, and technology. Students work alongside Intel researchers on cutting-edge projects in AI, chip design, and software development.',
                'url': 'https://www.intel.com/content/www/us/en/jobs/students-and-grads.html',
                'source': 'Intel',
                'category': 'Internship',
                'stem_fields': 'Computer Engineering, Computer Science, AI, Hardware Design',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8-10 weeks full-time summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Paid internship',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Santa Clara, CA and other locations',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Adobe Digital Academy - High School Track',
                'description': 'Program introducing high school students to digital design, user experience, and front-end development. Students learn Adobe Creative Suite, design principles, and web development while working on real projects.',
                'url': 'https://www.adobe.com/careers/university/digital-academy.html',
                'source': 'Adobe',
                'category': 'Internship',
                'stem_fields': 'Web Development, UX Design, Computer Science, Digital Media',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': '6 weeks part-time summer',
                'prerequisite_level': 'Beginner',
                'support_level': 'High',
                'deadline': 'April 15 annually',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Stipend provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National - Virtual',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Twitter #EarlyBird Engineering Program',
                'description': 'Summer program for high school students from underrepresented backgrounds interested in software engineering. Students learn coding, work on projects, and receive mentorship from Twitter engineers. Includes workshops on career development.',
                'url': 'https://careers.twitter.com/en/early-career.html',
                'source': 'Twitter (X)',
                'category': 'Internship',
                'stem_fields': 'Software Engineering, Computer Science, Mobile Development',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '6 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Paid internship',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'High',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'San Francisco, CA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'LinkedIn REACH Apprenticeship Program',
                'description': 'Apprenticeship program for graduating high school seniors interested in software engineering careers. Students receive training in programming, work on LinkedIn projects, and transition into full-time roles or college with strong industry experience.',
                'url': 'https://careers.linkedin.com/reach',
                'source': 'LinkedIn',
                'category': 'Internship',
                'stem_fields': 'Software Engineering, Computer Science, Web Development',
                'target_grade': '12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '12 weeks full-time',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'High',
                'deadline': 'January 31 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Paid apprenticeship',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Sunnyvale, CA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Dropbox Launch Program for High School',
                'description': 'Summer internship program for high school students interested in software engineering and product development. Students work on real Dropbox projects, receive mentorship, and learn about tech industry careers.',
                'url': 'https://www.dropbox.com/jobs/teams/emerging-talent',
                'source': 'Dropbox',
                'category': 'Internship',
                'stem_fields': 'Software Engineering, Computer Science, Product Development',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'February 28 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Paid internship',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'High',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'San Francisco, CA',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Cisco ThingQbator for Young Innovators',
                'description': 'IoT-focused program for high school students interested in Internet of Things, networking, and hardware/software integration. Students build IoT projects, learn networking fundamentals, and receive mentorship from Cisco engineers.',
                'url': 'https://www.cisco.com/c/en/us/about/csr/impact/education/thingqbator.html',
                'source': 'Cisco',
                'category': 'Internship',
                'stem_fields': 'Internet of Things, Networking, Computer Science, Hardware',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '6 weeks summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 15 annually',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'Stipend and equipment provided',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Low',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'Varies',
                'internet_dependency': 'High',
                'regional_availability': 'Multiple locations',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Netflix Pathways Program - High School Edition',
                'description': 'Entertainment technology internship for high school students interested in software engineering, data science, and content technology. Students work on Netflix technology projects and learn about streaming, algorithms, and user experience.',
                'url': 'https://jobs.netflix.com/culture/pathways-program',
                'source': 'Netflix',
                'category': 'Internship',
                'stem_fields': 'Software Engineering, Data Science, Computer Science, Content Technology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '10 weeks full-time summer',
                'prerequisite_level': 'Intermediate-Advanced',
                'support_level': 'High',
                'deadline': 'February 1 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Paid internship with housing stipend',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'Los Gatos, CA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Snap Inc. Academy - High School Track',
                'description': 'AR/VR and mobile development program for high school students. Students learn augmented reality development, mobile app creation, and work on Snapchat-related projects. Focus on creative technology and innovation.',
                'url': 'https://www.snap.com/en-US/jobs/students',
                'source': 'Snap Inc.',
                'category': 'Internship',
                'stem_fields': 'Augmented Reality, Mobile Development, Computer Science, Computer Graphics',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Hybrid',
                'time_commitment': '8 weeks summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'March 1 annually',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'Paid internship',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Varies',
                'internet_dependency': 'High',
                'regional_availability': 'Los Angeles, CA and virtual',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Uber Elevate - High School Engineering Experience',
                'description': 'Engineering internship for high school students interested in transportation technology, mapping, and software development. Students work on Uber technology projects, learn about ride-sharing algorithms, and receive industry mentorship.',
                'url': 'https://www.uber.com/us/en/careers/teams/university/',
                'source': 'Uber',
                'category': 'Internship',
                'stem_fields': 'Software Engineering, Computer Science, Data Science, Mapping Technology',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '8 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'February 15 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Paid internship',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'High',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'False',
                'cultural_competency': 'Medium',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'San Francisco, CA',
                'family_involvement_required': 'No',
                'peer_network_building': 'Medium',
                'mentor_access_level': 'High'
            },
            {
                'name': 'Airbnb Connect - High School Engineering Program',
                'description': 'Summer program for high school students from underrepresented backgrounds interested in software engineering and product design. Students learn full-stack development, work on Airbnb projects, and build professional networks in tech.',
                'url': 'https://careers.airbnb.com/university/',
                'source': 'Airbnb',
                'category': 'Internship',
                'stem_fields': 'Software Engineering, Full-Stack Development, Product Design',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'In-Person',
                'time_commitment': '10 weeks full-time summer',
                'prerequisite_level': 'Intermediate',
                'support_level': 'High',
                'deadline': 'January 31 annually',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Paid internship with housing',
                'family_income_consideration': 'Yes',
                'hidden_costs_level': 'Medium',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'Conditional',
                'transportation_required': 'Yes',
                'internet_dependency': 'Low',
                'regional_availability': 'San Francisco, CA',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'High'
            },
            {
                'name': 'GitHub Education - Student Developer Program',
                'description': 'Virtual program for high school students learning software development and open source contribution. Students learn Git, GitHub, collaborative coding, and contribute to open source projects. Includes mentorship from GitHub developers.',
                'url': 'https://education.github.com/students',
                'source': 'GitHub (Microsoft)',
                'category': 'Internship',
                'stem_fields': 'Software Development, Computer Science, Open Source, Version Control',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Virtual',
                'time_commitment': 'Flexible - Self-paced with structured components',
                'prerequisite_level': 'Beginner-Intermediate',
                'support_level': 'Medium',
                'deadline': 'Rolling admissions',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'N/A',
                'family_income_consideration': 'No',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'No',
                'internet_dependency': 'High',
                'regional_availability': 'National - Virtual',
                'family_involvement_required': 'No',
                'peer_network_building': 'High',
                'mentor_access_level': 'Medium'
            }
        ]
        return resources

    def scrape(self) -> List[Dict]:
        """Main scraping method"""
        print("Attempting to fetch tech internship pages...")

        # Try to fetch tech company program pages
        urls_to_try = [
            "https://buildyourfuture.withgoogle.com/programs/computer-science-summer-institute",
            "https://www.microsoft.com/en-us/diversity",
            "https://www.amazonfutureengineer.com"
        ]

        for url in urls_to_try:
            soup = self.fetch_page(url)
            if soup:
                print(f"Successfully fetched {url}")
                time.sleep(2)
            else:
                print(f"Could not fetch {url}, using representative data")

        # Create comprehensive tech internship resources
        self.resources = self.create_tech_internships()
        print(f"Created {len(self.resources)} tech internship resources")

        return self.resources

    def save_to_csv(self, filename: str):
        """Save scraped data to CSV file"""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]

        # Create data directory if it doesn't exist
        os.makedirs('data', exist_ok=True)

        filepath = os.path.join('data', filename)
        with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)

        print(f"Data saved to {filepath}")
        return filepath

def main():
    scraper = TechInternshipsHSScraper()
    scraper.scrape()
    scraper.save_to_csv('tech_internships_hs.csv')

if __name__ == "__main__":
    main()
