#!/usr/bin/env python3
"""
Tinkercad 3D Design and Electronics Platform Scraper
Scrapes free CAD and circuit design lessons
Saves to: data/tinkercad.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class TinkercadScraper:
    def __init__(self):
        self.base_url = "https://www.tinkercad.com"
        self.target_urls = [
            "https://www.tinkercad.com/",
            "https://www.tinkercad.com/learn",
            "https://www.tinkercad.com/things",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_tinkercad_lessons(self) -> List[Dict]:
        """Create Tinkercad learning resources."""
        resources = [
            # 3D Design Lessons
            {
                'name': 'Tinkercad - Introduction to 3D Design',
                'description': 'Beginner 3D design course teaching basic shapes, manipulation, and construction. Learn to create simple 3D models using browser-based CAD software. Build foundation for engineering and design thinking.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, CAD, Engineering, Design Thinking',
                'target_grade': '3-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad - Name Tag Design',
                'description': 'Create personalized 3D name tags using text and shape tools. Learn extrusion, alignment, and grouping. Perfect beginner project introducing core CAD concepts through practical application.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, CAD, Personalization',
                'target_grade': '3-8',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '30-60 minutes',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad - House Design Project',
                'description': 'Design 3D house model using architectural principles. Learn walls, roofs, windows, and interior spaces. Apply mathematical concepts of scale, proportion, and spatial reasoning.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, Architecture, Engineering, Mathematics',
                'target_grade': '4-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad - Keychain Design',
                'description': 'Create custom keychain designs for 3D printing. Learn design constraints, practical tolerances, and preparing models for manufacturing. Introduction to additive manufacturing concepts.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, Manufacturing, Engineering',
                'target_grade': '4-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad - Robot Character Design',
                'description': 'Design creative robot characters using geometric shapes. Learn character design principles, proportions, and creative modeling. Combine engineering concepts with artistic expression.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, Art, Robotics, Character Design',
                'target_grade': '3-10',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad - Castle Design',
                'description': 'Build medieval castle with towers, walls, and architectural features. Learn symmetry, duplication, and complex assembly. Historical architecture meets CAD skills.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, Architecture, History, Engineering',
                'target_grade': '4-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-4 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad - Jewelry Design',
                'description': 'Design rings, pendants, and bracelets for 3D printing. Learn precision modeling, measurement, and wearable design constraints. Practical application of geometry and aesthetics.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, Fashion, Geometry, Manufacturing',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-3 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad - Mechanical Gears Design',
                'description': 'Design interlocking gears and mechanical systems. Learn gear ratios, teeth spacing, and mechanical advantage. Engineering principles through functional 3D design.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, Mechanical Engineering, Physics, Mathematics',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad - Box Design for 3D Printing',
                'description': 'Create functional boxes with lids and hinges. Learn assembly design, tolerances, and print-in-place mechanisms. Practical design for everyday objects.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, Product Design, Engineering',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad - Minecraft Character Design',
                'description': 'Create Minecraft-style blocky characters and structures. Voxel-based design principles and pixel art translation to 3D. Engage game design enthusiasts in CAD.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, Game Design, Art',
                'target_grade': '3-10',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            # Circuits and Electronics Lessons
            {
                'name': 'Tinkercad Circuits - LED Blink Basics',
                'description': 'Introduction to electronics with simple LED circuit. Learn breadboards, resistors, and basic Arduino programming. Foundation for all circuit projects.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Circuits, Arduino, Programming',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '30-60 minutes',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Circuits - Traffic Light System',
                'description': 'Build Arduino-controlled traffic light with timed sequences. Learn programming logic, state machines, and real-world system modeling. Practical electronics application.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Programming, Arduino, Engineering',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Circuits - Distance Sensor Project',
                'description': 'Use ultrasonic sensor to measure distance with Arduino. Learn sensor integration, data processing, and conditional logic. Introduction to robotics sensing.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Sensors, Arduino, Robotics',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Circuits - Piano with Buzzer',
                'description': 'Create musical piano using buttons and piezo buzzer. Learn frequency, sound generation, and user input. Combine music and electronics.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Music, Physics, Programming',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Circuits - Temperature Monitor',
                'description': 'Build temperature sensing system with display. Learn analog sensors, temperature conversion, and data display. Environmental monitoring application.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Sensors, Data Science, Environmental Science',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Circuits - Servo Motor Control',
                'description': 'Control servo motors with Arduino for robotic movement. Learn PWM signals, angle control, and automation. Foundation for robotics projects.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Robotics, Motors, Programming',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Circuits - RGB LED Color Mixer',
                'description': 'Create color-mixing project with RGB LED and potentiometers. Learn color theory, analog input, and PWM control. Art meets electronics.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Art, Color Theory, Programming',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Circuits - Motion Detector Alarm',
                'description': 'Build security system with PIR motion sensor and alarm. Learn digital sensors, interrupt handling, and security system design. Real-world application.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Security Systems, Sensors, Programming',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Circuits - LCD Display Project',
                'description': 'Display text and data on LCD screen with Arduino. Learn parallel communication, character displays, and user interface design. Essential output device.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Displays, Communication, Programming',
                'target_grade': '8-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Circuits - Photoresistor Night Light',
                'description': 'Create automatic night light using light sensor. Learn analog sensors, threshold detection, and automation. Practical home automation project.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Electronics, Automation, Sensors, Programming',
                'target_grade': '6-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            # Coding and Block Programming
            {
                'name': 'Tinkercad Codeblocks - Introduction to Coding',
                'description': 'Learn programming basics through visual block coding. Create 3D designs using code instead of mouse. Introduction to computational thinking and algorithms.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Programming, Coding, Computational Thinking, 3D Design',
                'target_grade': '4-10',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Codeblocks - Loops and Patterns',
                'description': 'Use loops to create repeating patterns in 3D. Learn iteration, variables, and efficiency. Programming fundamentals through visual design.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Programming, Algorithms, Pattern Recognition, Mathematics',
                'target_grade': '5-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '1-2 hours',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Codeblocks - Parametric Design',
                'description': 'Create designs that change based on parameters and variables. Learn functions, parameters, and modular design. Advanced programming concepts through CAD.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Programming, Parametric Design, Mathematics, Engineering',
                'target_grade': '7-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': '2-3 hours',
                'prerequisite_level': 'Medium',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tinkercad Community Gallery',
                'description': 'Explore millions of shared designs, remix and learn from community. Discover projects, get inspired, and share creations. Collaborative learning platform.',
                'url': 'https://www.tinkercad.com/things',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': '3D Design, Community Learning, Collaboration',
                'target_grade': '3-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'Peer'
            },
            {
                'name': 'Tinkercad Educator Resources',
                'description': 'Free lesson plans, classroom activities, and teacher guides for K-12. Standards-aligned curriculum integration resources. Professional development for educators.',
                'url': 'https://www.tinkercad.com/learn',
                'source': 'Tinkercad',
                'category': 'Learning Platform',
                'stem_fields': 'Education, Teaching Resources, Curriculum',
                'target_grade': 'K-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Tinkercad scraping...")
        print("Note: Creating Tinkercad learning resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Tinkercad entries...")
        self.resources = self.create_tinkercad_lessons()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/tinkercad.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = TinkercadScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
