#!/usr/bin/env python3
"""
Tynker Coding Platform Scraper
Scrapes coding courses and programs from Tynker for K-12 students
Saves to: data/tynker.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class TynkerScraper:
    def __init__(self):
        self.base_url = "https://www.tynker.com"
        self.target_urls = [
            "https://www.tynker.com/",
            "https://www.tynker.com/k-12/",
            "https://www.tynker.com/courses/",
            "https://www.tynker.com/summer-camps/",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_tynker_resources(self) -> List[Dict]:
        """Create Tynker platform resources."""
        resources = [
            {
                'name': 'Tynker Junior - Visual Coding for Pre-Readers',
                'description': 'Visual block-based coding for ages 5-7 using pre-reader friendly interface. Learn sequencing, loops, and problem-solving through interactive games and puzzles.',
                'url': 'https://www.tynker.com/k-12/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Logic',
                'target_grade': 'K-2',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Block Coding - Grades 2-5',
                'description': 'Drag-and-drop block coding covering fundamental programming concepts. Create games, animations, and interactive stories while learning variables, conditionals, and loops.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Game Design',
                'target_grade': '2-5',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (30-60 hours)',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Python Introduction',
                'description': 'Transition from block coding to Python text-based programming. Learn Python syntax, data structures, and algorithms through guided projects and challenges.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Python, Programming',
                'target_grade': '6-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (40-80 hours)',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker JavaScript Fundamentals',
                'description': 'Learn JavaScript for web development and interactive applications. Build websites, games, and projects while mastering modern web programming.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, JavaScript, Web Development',
                'target_grade': '6-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (40-80 hours)',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Game Design Course',
                'description': 'Comprehensive game design course teaching gameplay mechanics, level design, and programming. Create platformers, adventure games, and multiplayer experiences.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Game Design, Computer Science, Programming',
                'target_grade': '3-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (50-100 hours)',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Minecraft Coding',
                'description': 'Learn coding through Minecraft modding and world creation. Program custom behaviors, build automated structures, and create mini-games within Minecraft.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Game Design',
                'target_grade': '3-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (30-60 hours)',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Mobile App Development',
                'description': 'Design and build mobile apps for iOS and Android. Learn UI design, event handling, and data management while creating functional mobile applications.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Mobile Development, App Design',
                'target_grade': '6-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (60-120 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Advanced Python Programming',
                'description': 'Advanced Python course covering object-oriented programming, data structures, algorithms, and libraries. Build complex projects and prepare for AP Computer Science.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Python, Programming',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (80-150 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Data Science & AI',
                'description': 'Introduction to data science and artificial intelligence for teens. Learn data analysis, machine learning basics, and build AI-powered projects with Python.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Data Science, Artificial Intelligence, Python',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (60-120 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Web Development Course',
                'description': 'Full-stack web development covering HTML, CSS, JavaScript, and backend basics. Build responsive websites, web apps, and interactive experiences.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Web Development, Computer Science, Programming',
                'target_grade': '6-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (70-140 hours)',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Robotics & Drones',
                'description': 'Program drones and robots using visual and text-based coding. Learn about sensors, actuators, and autonomous systems through virtual simulations.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Engineering, Programming',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (40-80 hours)',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker AR/VR Development',
                'description': 'Create augmented and virtual reality experiences. Learn 3D programming, spatial design, and immersive technology development.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Virtual Reality, Computer Science, 3D Design',
                'target_grade': '6-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (50-100 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker AP Computer Science Prep',
                'description': 'Comprehensive preparation for AP Computer Science A exam. Covers Java programming, algorithms, data structures, and problem-solving aligned with College Board curriculum.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Java, Programming',
                'target_grade': '9-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (100-200 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Creative Arts & Coding',
                'description': 'Combine art and programming to create digital animations, interactive art, and generative designs. Learn creative coding with Processing and p5.js.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Digital Art, Programming',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (40-80 hours)',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Music & Sound Programming',
                'description': 'Create music and sound effects through code. Learn music theory basics, sound synthesis, and build interactive musical instruments and compositions.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Music Technology, Computer Science, Programming',
                'target_grade': '3-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (30-60 hours)',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Math & Coding Integration',
                'description': 'Learn mathematics through coding projects. Visualize algebra, geometry, and statistics concepts while building interactive math games and simulations.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Mathematics, Computer Science, Programming',
                'target_grade': '4-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (40-80 hours)',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Physics & Simulation',
                'description': 'Build physics simulations and learn scientific concepts through code. Create gravity simulations, collision detection, and interactive physics experiments.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Physics, Computer Science, Programming',
                'target_grade': '6-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (50-100 hours)',
                'prerequisite_level': 'Low',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Storytelling & Animation',
                'description': 'Create animated stories and interactive narratives. Learn character animation, scene design, and storytelling techniques through code.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Animation, Digital Media',
                'target_grade': '2-5',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (30-60 hours)',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Puzzle & Logic Games',
                'description': 'Design puzzle and logic games while learning computational thinking. Create brain teasers, escape rooms, and strategy games with coding.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Logic, Game Design',
                'target_grade': '3-8',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (40-80 hours)',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Multiplayer Game Development',
                'description': 'Build online multiplayer games with real-time interaction. Learn networking concepts, server-client architecture, and collaborative gameplay design.',
                'url': 'https://www.tynker.com/courses/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Game Design, Computer Science, Networking',
                'target_grade': '6-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Self-paced (60-120 hours)',
                'prerequisite_level': 'Medium',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            },
            {
                'name': 'Tynker Coding for Educators',
                'description': 'Comprehensive classroom curriculum and resources for teachers. Includes lesson plans, assessment tools, and student progress tracking for K-12 coding education.',
                'url': 'https://www.tynker.com/k-12/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Education, Programming',
                'target_grade': 'K-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Academic year',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Tynker Summer Coding Camp - Game Dev',
                'description': 'Week-long online summer camp focused on game development. Create multiple games using block coding and text-based programming with live instruction.',
                'url': 'https://www.tynker.com/summer-camps/',
                'source': 'Tynker',
                'category': 'Camp',
                'stem_fields': 'Game Design, Computer Science, Programming',
                'target_grade': '3-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '1 week',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Tynker Summer Coding Camp - Python',
                'description': 'Intensive week-long Python programming camp for beginners and intermediate students. Build projects, learn syntax, and develop problem-solving skills with live instructors.',
                'url': 'https://www.tynker.com/summer-camps/',
                'source': 'Tynker',
                'category': 'Camp',
                'stem_fields': 'Computer Science, Python, Programming',
                'target_grade': '6-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '1 week',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Tynker Summer Coding Camp - Minecraft',
                'description': 'Learn coding through Minecraft modding and world creation. Week-long camp teaching programming fundamentals with popular gaming platform.',
                'url': 'https://www.tynker.com/summer-camps/',
                'source': 'Tynker',
                'category': 'Camp',
                'stem_fields': 'Computer Science, Game Design, Programming',
                'target_grade': '3-8',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '1 week',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Tynker Summer Coding Camp - Mobile Apps',
                'description': 'Design and develop mobile applications in this week-long intensive camp. Learn UI design, app logic, and deployment with experienced instructors.',
                'url': 'https://www.tynker.com/summer-camps/',
                'source': 'Tynker',
                'category': 'Camp',
                'stem_fields': 'Mobile Development, Computer Science, App Design',
                'target_grade': '6-12',
                'cost': 'Paid',
                'location_type': 'Online',
                'time_commitment': '1 week',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Medium',
                'financial_aid_available': 'True',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': '$100-$500',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Tynker Certificate Programs',
                'description': 'Earn coding certificates by completing structured learning paths. Demonstrate proficiency in various programming languages and concepts with shareable credentials.',
                'url': 'https://www.tynker.com/',
                'source': 'Tynker',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming',
                'target_grade': 'K-12',
                'cost': 'Freemium',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'Low',
                'financial_aid_available': 'False',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'Premium-Features',
                'cost_category': 'Free-Tier-Available',
                'diversity_focus': 'False',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'Medium',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'False',
                'mentor_access_level': 'None'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Tynker platform scraping...")
        print("Note: Creating Tynker coding platform resources")
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Tynker resource entries...")
        self.resources = self.create_tynker_resources()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/tynker.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = TynkerScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
