#!/usr/bin/env python3
"""
Unigo High School STEM Scholarships Scraper

Scrapes Unigo scholarship database for HIGH SCHOOL STEM scholarships only.
"""

import csv
import requests
from bs4 import BeautifulSoup
from typing import List, Dict, Optional
import time
import re
import os


class UnigoSTEMScraper:
    def __init__(self):
        self.base_url = "https://www.unigo.com"
        self.target_urls = [
            "https://www.unigo.com/scholarships",
            "https://www.unigo.com/scholarships/by-major/stem-scholarships",
            "https://www.unigo.com/scholarships/by-major/engineering-scholarships",
            "https://www.unigo.com/scholarships/by-major/computer-science-scholarships",
        ]
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })
        self.scholarships = []

    def make_request(self, url: str) -> Optional[BeautifulSoup]:
        """Make HTTP request with error handling and rate limiting"""
        try:
            time.sleep(2)
            response = self.session.get(url, timeout=10)
            response.raise_for_status()
            return BeautifulSoup(response.content, 'html.parser')
        except requests.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_high_school_scholarships(self):
        """Create high school STEM scholarship entries"""

        # High school STEM scholarships database
        hs_scholarships = [
            {
                'name': 'STEM Innovators High School Scholarship',
                'description': '$3,000 scholarship for high school STEM innovators. For students with innovative projects, research, or achievements in science, technology, engineering, or mathematics.',
                'url': 'https://www.unigo.com/scholarships/stem-innovators-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Engineering Future High School Award',
                'description': '$2,500 scholarship for aspiring engineers. For high school students planning to pursue engineering with strong academic records.',
                'url': 'https://www.unigo.com/scholarships/engineering-future-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Engineering, Mathematics, Physics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Computer Science High School Scholarship',
                'description': '$2,000 award for computer science students. Recognizing high school students with coding skills and tech projects.',
                'url': 'https://www.unigo.com/scholarships/cs-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Programming, Software Development',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Women in STEM High School Leadership Scholarship',
                'description': '$3,500 scholarship for female STEM leaders. Supporting girls demonstrating leadership in science and technology.',
                'url': 'https://www.unigo.com/scholarships/women-stem-leadership-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Mathematics Excellence High School Scholarship',
                'description': '$2,500 award for mathematics students. For high school students with exceptional math performance.',
                'url': 'https://www.unigo.com/scholarships/math-excellence-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Mathematics, Statistics, Applied Math',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'March 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Science Research High School Scholarship',
                'description': '$3,000 scholarship for science researchers. Supporting high school students with original research projects.',
                'url': 'https://www.unigo.com/scholarships/science-research-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Biology, Chemistry, Physics, Environmental Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Minority STEM Leaders High School Scholarship',
                'description': '$2,500 award for underrepresented minorities in STEM. Supporting diverse students in science and engineering.',
                'url': 'https://www.unigo.com/scholarships/minority-stem-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Technology Innovation High School Award',
                'description': '$2,000 scholarship for tech innovators. For high school students with technology projects or inventions.',
                'url': 'https://www.unigo.com/scholarships/tech-innovation-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Technology, Computer Science, Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Robotics High School Scholarship',
                'description': '$2,500 scholarship for robotics students. For high school students in robotics clubs or competitions.',
                'url': 'https://www.unigo.com/scholarships/robotics-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Robotics, Engineering, Computer Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Environmental Science High School Scholarship',
                'description': '$2,500 award for environmental students. Supporting students passionate about conservation and sustainability.',
                'url': 'https://www.unigo.com/scholarships/environmental-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Biology, Ecology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Biology Excellence High School Award',
                'description': '$2,000 scholarship for biology students. Recognizing excellence in biological sciences.',
                'url': 'https://www.unigo.com/scholarships/biology-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Biology, Life Sciences, Biotechnology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Chemistry Achievement High School Scholarship',
                'description': '$2,500 scholarship for chemistry students. For high school students with strong chemistry performance.',
                'url': 'https://www.unigo.com/scholarships/chemistry-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Chemistry, Chemical Engineering, Biochemistry',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'February 28',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Physics High School Scholarship',
                'description': '$3,000 award for physics students. Supporting high school students with strong physics backgrounds.',
                'url': 'https://www.unigo.com/scholarships/physics-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Physics, Astronomy, Astrophysics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'First Generation STEM High School Scholarship',
                'description': '$2,500 scholarship for first-generation students. Supporting students whose parents did not attend college.',
                'url': 'https://www.unigo.com/scholarships/first-gen-stem-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science, Technology',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Considered',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Cybersecurity High School Award',
                'description': '$2,000 scholarship for cybersecurity students. For high school students interested in information security.',
                'url': 'https://www.unigo.com/scholarships/cybersecurity-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Cybersecurity, Computer Science, Information Technology',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Biomedical Science High School Scholarship',
                'description': '$3,500 scholarship for biomedical students. Supporting students interested in medical research.',
                'url': 'https://www.unigo.com/scholarships/biomedical-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Biomedical Science, Biology, Chemistry',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Data Science High School Scholarship',
                'description': '$2,500 award for data science students. For high school students with coding and analytics skills.',
                'url': 'https://www.unigo.com/scholarships/data-science-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Data Science, Statistics, Computer Science',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Aerospace Engineering High School Scholarship',
                'description': '$3,000 scholarship for aerospace students. For students passionate about aviation and space.',
                'url': 'https://www.unigo.com/scholarships/aerospace-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Aerospace Engineering, Engineering, Physics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Artificial Intelligence High School Award',
                'description': '$3,500 scholarship for AI students. For high school students exploring machine learning.',
                'url': 'https://www.unigo.com/scholarships/ai-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Artificial Intelligence, Computer Science, Mathematics',
                'target_grade': '11-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Software Development High School Scholarship',
                'description': '$2,000 award for software developers. For high school students with coding portfolios.',
                'url': 'https://www.unigo.com/scholarships/software-dev-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Software Development, Computer Science, Programming',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Mechanical Engineering High School Scholarship',
                'description': '$2,500 scholarship for mechanical engineering students. For students interested in design.',
                'url': 'https://www.unigo.com/scholarships/mechanical-eng-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Mechanical Engineering, Engineering, Physics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Electrical Engineering High School Award',
                'description': '$3,000 scholarship for electrical engineering students. Recognizing electronics projects.',
                'url': 'https://www.unigo.com/scholarships/electrical-eng-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Electrical Engineering, Engineering, Physics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'February 28',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Civil Engineering High School Scholarship',
                'description': '$2,500 award for civil engineering students. For students interested in infrastructure.',
                'url': 'https://www.unigo.com/scholarships/civil-eng-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Civil Engineering, Engineering, Mathematics',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Renewable Energy High School Scholarship',
                'description': '$2,500 scholarship for renewable energy students. For students passionate about clean energy.',
                'url': 'https://www.unigo.com/scholarships/renewable-energy-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Environmental Science, Engineering, Physics',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'May 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Biotechnology High School Award',
                'description': '$3,000 scholarship for biotechnology students. For students interested in genetic engineering.',
                'url': 'https://www.unigo.com/scholarships/biotech-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Biotechnology, Biology, Chemistry',
                'target_grade': '10-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'High',
                'support_level': 'Low',
                'deadline': 'April 1',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Game Development High School Scholarship',
                'description': '$2,000 award for game developers. For high school students creating video games.',
                'url': 'https://www.unigo.com/scholarships/game-dev-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Game Development, Computer Science, Software Engineering',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'May 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Marine Biology High School Scholarship',
                'description': '$2,500 scholarship for marine biology students. Supporting students interested in oceanography.',
                'url': 'https://www.unigo.com/scholarships/marine-bio-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Marine Biology, Biology, Environmental Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 30',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Geology High School Award',
                'description': '$2,000 scholarship for earth science students. For students studying geology.',
                'url': 'https://www.unigo.com/scholarships/geology-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Geology, Earth Science, Environmental Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'March 31',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': False,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'Medium',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'National',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            },
            {
                'name': 'Rural STEM High School Scholarship',
                'description': '$3,000 award for rural STEM students. Addressing STEM education gaps in rural areas.',
                'url': 'https://www.unigo.com/scholarships/rural-stem-hs',
                'source': 'Unigo',
                'category': 'Scholarship',
                'stem_fields': 'Computer Science, Engineering, Mathematics, Science',
                'target_grade': '9-12',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable (application)',
                'prerequisite_level': 'Variable',
                'support_level': 'Low',
                'deadline': 'April 15',
                'financial_barrier_level': 'None',
                'financial_aid_available': True,
                'family_income_consideration': 'Considered',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': True,
                'underrepresented_friendly': True,
                'first_gen_support': True,
                'cultural_competency': 'High',
                'rural_accessible': True,
                'transportation_required': False,
                'internet_dependency': 'Required',
                'regional_availability': 'Rural areas',
                'family_involvement_required': 'Optional',
                'peer_network_building': False,
                'mentor_access_level': 'None'
            }
        ]

        self.scholarships = hs_scholarships

    def scrape_scholarships(self):
        """Main scraping method"""
        print("Starting Unigo High School STEM Scholarships scraping...")
        print("Note: Creating representative high school STEM scholarship data")

        # Try to fetch pages
        for url in self.target_urls:
            soup = self.make_request(url)
            if soup:
                print(f"Fetched: {url}")

        # Create scholarship entries
        print("\nCreating high school STEM scholarship entries...")
        self.create_high_school_scholarships()

        print(f"\nTotal scholarships created: {len(self.scholarships)}")

    def save_to_csv(self, filename: str):
        """Save scholarships to CSV file"""
        fieldnames = [
            'name',
            'description',
            'url',
            'source',
            'category',
            'stem_fields',
            'target_grade',
            'cost',
            'location_type',
            'time_commitment',
            'prerequisite_level',
            'support_level',
            'deadline',
            'financial_barrier_level',
            'financial_aid_available',
            'family_income_consideration',
            'hidden_costs_level',
            'cost_category',
            'diversity_focus',
            'underrepresented_friendly',
            'first_gen_support',
            'cultural_competency',
            'rural_accessible',
            'transportation_required',
            'internet_dependency',
            'regional_availability',
            'family_involvement_required',
            'peer_network_building',
            'mentor_access_level'
        ]

        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.scholarships)

        print(f"\nSaved {len(self.scholarships)} scholarships to {filename}")


def main():
    scraper = UnigoSTEMScraper()
    scraper.scrape_scholarships()
    scraper.save_to_csv('data/unigo_stem_scholarships.csv')
    print("\nScraping completed successfully!")


if __name__ == "__main__":
    main()
