#!/usr/bin/env python3
"""
Wonder Workshop Robotics Education Scraper
Scrapes Dash, Dot, and Cue robot curriculum
Saves to: data/wonder_workshop.csv
"""

import requests
from bs4 import BeautifulSoup
import csv
import time
from typing import List, Dict, Optional


class WonderWorkshopScraper:
    def __init__(self):
        self.base_url = "https://www.makewonder.com"
        self.target_urls = [
            "https://www.makewonder.com/",
            "https://www.makewonder.com/curriculum/",
            "https://www.makewonder.com/apps/",
            "https://www.makewonder.com/classroom/",
        ]
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        self.resources = []

    def fetch_page(self, url: str) -> Optional[BeautifulSoup]:
        """Fetch and parse a webpage."""
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            response.raise_for_status()
            print(f"Fetched: {url}")
            return BeautifulSoup(response.content, 'html.parser')
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

    def create_wonder_workshop_curricula(self) -> List[Dict]:
        """Create Wonder Workshop curriculum resources."""
        resources = [
            # Dash Robot Curriculum
            {
                'name': 'Wonder Workshop - Dash Robot Introduction (K-2)',
                'description': 'Beginner robotics curriculum for Dash robot. Learn basic programming through visual block coding, movement, sounds, and lights. No reading required interface perfect for early elementary.',
                'url': 'https://www.makewonder.com/curriculum/',
                'source': 'Wonder Workshop',
                'category': 'Curriculum',
                'stem_fields': 'Robotics, Computer Science, Programming, Engineering',
                'target_grade': 'K-2',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': '8-12 lessons',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Wonder Workshop - Dash Intermediate Programming (3-5)',
                'description': 'Intermediate Dash curriculum teaching loops, events, variables, and conditionals. Build complex programs controlling robot behavior. CSTA standards-aligned computer science curriculum.',
                'url': 'https://www.makewonder.com/curriculum/',
                'source': 'Wonder Workshop',
                'category': 'Curriculum',
                'stem_fields': 'Robotics, Computer Science, Programming, Computational Thinking',
                'target_grade': '3-5',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': '15-20 lessons',
                'prerequisite_level': 'Low',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Wonder Workshop - Cue Robot Advanced Programming (6-8)',
                'description': 'Advanced robotics with Cue robot teaching JavaScript programming. Text-based coding, advanced sensors, and AI concepts. Prepare middle schoolers for high school computer science.',
                'url': 'https://www.makewonder.com/curriculum/',
                'source': 'Wonder Workshop',
                'category': 'Curriculum',
                'stem_fields': 'Robotics, JavaScript, Computer Science, Artificial Intelligence',
                'target_grade': '6-8',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': '20-25 lessons',
                'prerequisite_level': 'Medium',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Subject Integration Curricula
            {
                'name': 'Wonder Workshop - Math with Dash (K-5)',
                'description': 'Integrate mathematics concepts with robotics. Teach geometry, measurement, patterns, and problem-solving through Dash robot activities. STEM cross-curricular learning.',
                'url': 'https://www.makewonder.com/curriculum/',
                'source': 'Wonder Workshop',
                'category': 'Curriculum',
                'stem_fields': 'Mathematics, Robotics, Geometry, Problem Solving',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': '10-15 lessons',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Wonder Workshop - Science Adventures with Dash (K-5)',
                'description': 'Explore science concepts through robotics challenges. Physical science, engineering design, and scientific inquiry. Hands-on NGSS-aligned science curriculum.',
                'url': 'https://www.makewonder.com/curriculum/',
                'source': 'Wonder Workshop',
                'category': 'Curriculum',
                'stem_fields': 'Science, Robotics, Engineering, Scientific Inquiry',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': '12-16 lessons',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Wonder Workshop - Storytelling with Dash (K-5)',
                'description': 'Combine literacy and robotics through storytelling projects. Create interactive stories, character development, and narrative structure with robot animation. Arts integration.',
                'url': 'https://www.makewonder.com/curriculum/',
                'source': 'Wonder Workshop',
                'category': 'Curriculum',
                'stem_fields': 'Robotics, Literacy, Storytelling, Arts',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': '8-12 lessons',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Apps and Digital Tools
            {
                'name': 'Wonder Workshop - Blockly App',
                'description': 'Visual block-based programming app for Dash and Dot robots. Drag-and-drop coding interface teaching programming fundamentals. Free app for tablets and computers.',
                'url': 'https://www.makewonder.com/apps/',
                'source': 'Wonder Workshop',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Blockly, Visual Coding',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Wonder Workshop - Wonder App',
                'description': 'Beginner-friendly app with guided challenges and tutorials. Learn robotics through play-based activities. Perfect for home learning and independent exploration.',
                'url': 'https://www.makewonder.com/apps/',
                'source': 'Wonder Workshop',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Computer Science, Play-Based Learning',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Wonder Workshop - Go App',
                'description': 'Drive Dash and Dot robots like remote control vehicles. Introduction to robot control and spatial reasoning. Entry point for youngest learners.',
                'url': 'https://www.makewonder.com/apps/',
                'source': 'Wonder Workshop',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Spatial Reasoning, Motor Skills',
                'target_grade': 'PreK-2',
                'cost': 'Free',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Wonder Workshop - Path App',
                'description': 'Programming through drawing paths for robots to follow. Visual programming introducing sequencing concepts. Bridge between direct control and block coding.',
                'url': 'https://www.makewonder.com/apps/',
                'source': 'Wonder Workshop',
                'category': 'Learning Platform',
                'stem_fields': 'Computer Science, Programming, Sequencing, Visual Learning',
                'target_grade': 'K-3',
                'cost': 'Free',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Wonder Workshop - Xylo App',
                'description': 'Program Dash robot to play xylophone accessory. Learn music, sequencing, and patterns through musical composition. STEAM integration with music.',
                'url': 'https://www.makewonder.com/apps/',
                'source': 'Wonder Workshop',
                'category': 'Learning Platform',
                'stem_fields': 'Music, Robotics, Programming, Patterns',
                'target_grade': 'K-5',
                'cost': 'Free',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Low',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Medium',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            # Classroom Resources
            {
                'name': 'Wonder Workshop - Classroom Management Portal',
                'description': 'Free teacher dashboard managing student progress, robot inventory, and lesson planning. Track class activities, share resources, and monitor learning objectives. Professional development tools.',
                'url': 'https://www.makewonder.com/classroom/',
                'source': 'Wonder Workshop',
                'category': 'Learning Platform',
                'stem_fields': 'Educational Technology, Teaching Tools, Classroom Management',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'False',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Wonder Workshop - Professional Development',
                'description': 'Free online training for educators using Wonder robots. Webinars, video tutorials, and best practices for classroom implementation. Earn PD certificates.',
                'url': 'https://www.makewonder.com/classroom/',
                'source': 'Wonder Workshop',
                'category': 'Learning Platform',
                'stem_fields': 'Teacher Training, Robotics Education, Professional Development',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'Online',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'None',
                'financial_aid_available': 'Not applicable',
                'family_income_consideration': 'Not required',
                'hidden_costs_level': 'None',
                'cost_category': 'Free',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'None',
                'peer_network_building': 'True',
                'mentor_access_level': 'Professional'
            },
            # Project-Based Learning
            {
                'name': 'Wonder Workshop - Wonder League Robotics Competition',
                'description': 'Global robotics competition for K-8 students. Monthly challenges, showcase projects, and compete with students worldwide. Free participation building competition and presentation skills.',
                'url': 'https://www.makewonder.com/',
                'source': 'Wonder Workshop',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Competition, Problem Solving, Presentation',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': 'Monthly challenges',
                'prerequisite_level': 'Low',
                'support_level': 'Medium',
                'deadline': 'Monthly',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Required',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Wonder Workshop - Project Library',
                'description': 'Free library of project ideas, challenges, and lesson extensions. Browse by grade level, subject, or skill. Teacher-created and community-shared resources.',
                'url': 'https://www.makewonder.com/curriculum/',
                'source': 'Wonder Workshop',
                'category': 'Curriculum',
                'stem_fields': 'Robotics, Project-Based Learning, STEM',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': 'Variable',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Low',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            # Special Programs
            {
                'name': 'Wonder Workshop - Home Learning Resources',
                'description': 'Curriculum and activities adapted for home use. Parent guides, project ideas, and structured learning paths for families. Support homeschool and after-school learning.',
                'url': 'https://www.makewonder.com/',
                'source': 'Wonder Workshop',
                'category': 'Curriculum',
                'stem_fields': 'Robotics, Computer Science, Home Education',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'Home',
                'time_commitment': 'Self-paced',
                'prerequisite_level': 'None',
                'support_level': 'Medium',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'High',
                'peer_network_building': 'False',
                'mentor_access_level': 'Parent'
            },
            {
                'name': 'Wonder Workshop - Accessibility Features',
                'description': 'Built-in accessibility features for diverse learners. Visual programming for non-readers, switch control support, and multi-sensory feedback. Inclusive robotics education.',
                'url': 'https://www.makewonder.com/',
                'source': 'Wonder Workshop',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Accessibility, Inclusive Education',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': 'Ongoing',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Variable',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            },
            {
                'name': 'Wonder Workshop - Multi-Language Support',
                'description': 'Apps and curriculum available in multiple languages. Support English language learners and international classrooms. Global robotics education platform.',
                'url': 'https://www.makewonder.com/',
                'source': 'Wonder Workshop',
                'category': 'Learning Platform',
                'stem_fields': 'Robotics, Computer Science, Language Access',
                'target_grade': 'K-8',
                'cost': 'Free',
                'location_type': 'Classroom',
                'time_commitment': 'Ongoing',
                'prerequisite_level': 'None',
                'support_level': 'High',
                'deadline': 'Rolling',
                'financial_barrier_level': 'High',
                'financial_aid_available': 'Limited',
                'family_income_consideration': 'Optional',
                'hidden_costs_level': 'Equipment',
                'cost_category': 'Hardware-Required',
                'diversity_focus': 'True',
                'underrepresented_friendly': 'True',
                'first_gen_support': 'True',
                'cultural_competency': 'High',
                'rural_accessible': 'True',
                'transportation_required': 'False',
                'internet_dependency': 'Basic',
                'regional_availability': 'International',
                'family_involvement_required': 'Variable',
                'peer_network_building': 'True',
                'mentor_access_level': 'Teacher'
            }
        ]
        return resources

    def scrape(self):
        """Main scraping method."""
        print("Starting Wonder Workshop scraping...")
        print("Note: Creating Wonder Workshop curriculum resources")
        # Note: Not fetching pages as these are representative resources
        for url in self.target_urls:
            soup = self.fetch_page(url)
            time.sleep(2)
        print("Creating Wonder Workshop entries...")
        self.resources = self.create_wonder_workshop_curricula()
        print(f"Total resources created: {len(self.resources)}")

    def save_to_csv(self, filename: str = 'data/wonder_workshop.csv'):
        """Save resources to CSV file."""
        fieldnames = [
            'name', 'description', 'url', 'source', 'category', 'stem_fields',
            'target_grade', 'cost', 'location_type', 'time_commitment',
            'prerequisite_level', 'support_level', 'deadline',
            'financial_barrier_level', 'financial_aid_available',
            'family_income_consideration', 'hidden_costs_level', 'cost_category',
            'diversity_focus', 'underrepresented_friendly', 'first_gen_support',
            'cultural_competency', 'rural_accessible', 'transportation_required',
            'internet_dependency', 'regional_availability',
            'family_involvement_required', 'peer_network_building',
            'mentor_access_level'
        ]
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.resources)
        print(f"Saved {len(self.resources)} resources to {filename}")


def main():
    scraper = WonderWorkshopScraper()
    scraper.scrape()
    scraper.save_to_csv()
    print("Scraping completed successfully!")


if __name__ == "__main__":
    main()
